import { chapter, concepts as c, ev, u } from "./shared.mjs";

const details = [
  chapter({
    prerequisite:"选择一个你能接触真实用户、现有流程和结果数据的问题；不要从‘做一个 Agent’开始。",
    goals:["区分用户任务、业务结果与模型能力","量化频率、价值、可行性和失败成本","建立非 AI、人工增强与自动化三层机会基线"],
    concepts:c([["AIPM01","问题空间","用户在特定情境下为取得进展而完成的任务链","痛点是否真实、频繁且可行动"],["AIPM02","AI 适配度","输入可观察性、输出可评测性和错误可恢复性共同决定可行性","是否真的需要概率模型"],["AIPM03","机会组合","按价值、频率、数据、风险和变更成本排序候选","先验证哪一个最危险假设"]]),
    thesis:"AI 产品的起点是值得改善的决策或工作，不是模型演示；一个高价值但不可评测、不可恢复的任务，通常不应先自动化。",
    problem:"销售团队说想要‘自动写跟进邮件’，真实瓶颈可能是客户信息散落、审批慢或不知道下一行动。若只生成文案，发送量上升却转化下降。应追踪从准备、查证、起草、审批、发送到结果的完整任务，并比较搜索模板、结构化表单、AI 草拟与自主发送。",
    mechanismTitle:"机会评分与反事实基线",mechanism:"先用访谈、影随和日志还原 current-state；把机会写成角色—触发—输入—判断—动作—结果—例外。AI 适合高变异输入、可形成反馈且错误可检测/恢复的环节。对每个方案定义‘若不用 AI 会怎样’的基线，避免把自然趋势或流程整理的收益归功于模型。",
    formula:"机会分不是伪精确排名，而是显式假设：$O=F\\times V\\times P(success)-C_{build}-P(error)C_{error}$。其中频率 $F$、单次价值 $V$、成功概率、实施成本和风险成本都用区间/情景分析；高风险尾部不能被平均价值抵消。",
    formulaNotes:["用户说想要的功能与真实任务是否一致","价值是否有可观测代理和时间窗口","错误能否发现、撤销和人工恢复","模型之外的数据/集成/变更成本是否计入"],
    evidence:[
      ev("2026-04-06","Stanford AI Index 2026","https://hai.stanford.edu/assets/files/ai_index_report_2026.pdf","快速变化的能力、成本和采用率怎样影响产品机会判断？","报告综合研究、产业、投资、责任和政策数据，以年度口径呈现趋势，而非把单一模型发布当市场事实。","2026 版显示能力与部署继续扩张，但成本、地区、责任事件和评测差异并存。","为机会假设提供宏观先验和反宣传材料。","宏观统计不能替代目标用户研究；不同数据源的定义和滞后需逐项检查。"),
      ev("2026-06-10","Anthropic Economic Index 2026","https://www.anthropic.com/research/economic-index-june-2026-report","真实使用中 AI 更常增强还是自动化工作，任务分布怎样变化？","报告使用聚合、隐私保护的产品使用数据，把会话映射到职业任务并区分 augmentation/automation。","结果提供任务层采用与交互模式的最新观察，而非仅调查意愿。","支持从具体任务而非职业标题寻找机会。","单一厂商用户有选择偏差，分类模型和产品设计也影响观测，不能外推全部经济。"),
    ],
    diagram:"flowchart LR\n W[真实工作/结果] --> R[影随+日志+访谈]\n R --> J[任务/例外地图]\n J --> O[机会假设]\n O --> B[非AI/人工基线]\n B --> T[最危险假设测试]\n T --> D{继续/缩小/停止}",
    caseTitle:"销售跟进工作流机会判断",case:"访谈 8 名销售和 2 名审批人，抽样 50 个机会单。发现 60% 时间花在找事实与确认权限而非写作。第一版只做证据聚合与草拟，禁止自动发送；主指标是合格跟进完成时间和后续行动率，护栏是事实错误、退订与人工修订。",
    protocol:["画现状任务链并标频率、等待、返工、例外和责任人","列至少三个非 AI/流程替代并测现状基线","为前两机会写价值区间、失败成本和退出条件","用礼宾式或人工幕后原型验证最危险假设"],
    decisions:["机会卡必须写不用 AI 的方案","首版避开错误不可恢复动作","路线图按证据风险而非功能数量排序","没有结果观测和责任归属的需求暂缓"],
    failures:["从竞品功能反推用户问题","把节省点击当业务价值","只访谈管理者不观察执行者","忽略例外与责任转移","用宏观 AI 数据代替本地验证"],
    prompt:"作为 AI 产品机会审查员，把需求重写为角色、触发、现状步骤、等待/返工、输入可观察性、输出可评测性、错误可恢复性和真实结果；给三个非 AI 基线、价值区间、最危险假设与停止条件。",
    exerciseTitle:"提交一张机会证伪卡",exercise:"观察一个真实流程至少三次，写任务链和五个例外；比较流程改造、AI 辅助和自动化，选择首个实验并解释为什么其失败最有信息量。",
    misconceptions:["所有重复劳动都适合 AI","用户要助手就是机会成立","模型能力等于产品价值","节省时间必然带来结果","越自主越先进"],
    quiz:{question:"用户频繁要求自动写邮件，但观察发现时间主要耗在查找可信客户事实，首版优先做什么？",options:["自动发送","证据聚合与可追溯草拟","训练更有文采的模型"],answer:1,explanation:"先解决主瓶颈并保持高风险动作可审查。"},
    summary:["从任务和结果而非 AI 形态出发","机会同时受价值、可评测和恢复性约束","非 AI 基线防止错误归因","先测最危险假设"],mastery:{explain:"问题价值与 AI 适配度的区别",apply:"一张含基线的机会卡",boundary:"一个不应自动化的高价值任务"},sources:[u("AI Index 2026","https://hai.stanford.edu/assets/files/ai_index_report_2026.pdf"),u("Economic Index 2026","https://www.anthropic.com/research/economic-index-june-2026-report")],
  }),
  chapter({
    prerequisite:"已有一个通过初筛的任务和可接触的执行者。",goals:["用情境访谈和日志还原真实而非理想流程","建模角色、信息、例外、责任和交接","识别新手/专家从 AI 获益不同的机制"],
    concepts:c([["AIPM04","情境研究","在任务发生处观察工具、绕行和判断依据","需求来自行为还是表态"],["AIPM05","服务蓝图","前台交互、后台系统、人工与责任在时间线上连接","AI 插入后谁的工作发生变化"],["AIPM06","专业能力差异","领域知识改变问题分解、验证与接管能力","同一功能需怎样分层控制"]]),
    thesis:"AI 不只是缩短一个步骤，它会重分配认知、核验和责任；产品研究必须观察工作怎样完成以及失败后谁来收拾。",
    problem:"专家使用代码 Agent 能给清晰任务、检查架构和发现隐蔽错误，新手可能快速产出却无法审查。若只看完成速度，产品会奖励表面产出并积累维护债务。需要按技能层级、任务复杂度和后续质量分层。",
    mechanismTitle:"工作流、认知卸载与互补性",mechanism:"影随记录触发、工具切换、信息来源、决策点、例外和交接；认知任务分析追问专家如何察觉异常。AI 可能自动化 execution、增强 judgment 或把验证劳动转移给下游。服务蓝图把模型不可见等待与人工审查一起建模。",
    formula:"端到端周期 $T=\\sum_i service_i+\\sum_j wait_j+rework$；自动化率不等于价值。分层处理效应 $\\tau(s)=E[Y(1)-Y(0)|skill=s]$ 可揭示专家/新手差异；还应量化 review debt 和返工在后续周期的滞后成本。",
    formulaNotes:["是否观察实际工作而非回忆","技能层级用行为证据还是职位","任务难度和资料完整度是否平衡","短期速度与长期维护是否同窗观测"],
    evidence:[ev("2026-06-16","Agentic Coding Expertise Study","https://www.anthropic.com/research/claude-code-expertise","专业知识怎样改变 Agentic coding 的成功？","研究分析约 40 万次编码会话，以行为信号比较不同专业程度用户的问题分解、工具使用和结果。","报告显示领域/工具熟练度与成功存在显著联系，专家更能分解、验证和恢复。","支持 AI 产品按用户能力设计脚手架和权限，而非假设工具抹平差距。","观察性产品数据存在选择与代理测量限制，不能直接推断培训的因果效果。"),ev("2026-01-29","AI Assistance and Coding Skills RCT","https://www.anthropic.com/research/AI-assistance-coding-skills","AI 加速任务时是否会削弱学习？","随机对照实验比较 AI 辅助与对照组完成编程任务后的知识测验和行为。","研究报告 AI 组技能掌握约低 17%，同时不同使用方式有差异。","提醒产品同时优化产出与能力保持。","样本、任务和短期测验限制外推；17% 不是所有工作常数。" )],
    diagram:"flowchart LR\n T[触发] --> F[前台任务]\n F --> A[AI建议/执行]\n A --> V{用户验证}\n V -->|通过| H[交接/结果]\n V -->|失败| R[修复/升级]\n B[后台数据/政策] --> A\n E[专业能力] --> V\n R --> L[学习与流程修订]",
    caseTitle:"代码助手的新手与专家工作流",case:"让两组用户完成同难度真实变更，记录计划、上下文选择、接受修改、测试、返工与一周后维护。专家模式可批量执行，新手模式强制预测输出、展示 diff 和解释风险；指标含完成、缺陷、理解测验和复现能力。",
    protocol:["影随 5—8 名执行者完成同类真实任务","画主路径、例外、交接、系统和责任泳道","按可观察技能行为分层，不用自我评价代替","验证 AI 前后等待、审查、返工与学习变化"],
    decisions:["权限与自主度随任务风险和能力分层","把验证步骤设计为产品体验","交接产物包含来源、假设和未决项","培训目标进入采用指标"],failures:["只优化单步耗时","把确认按钮当有效审查","对所有用户给同自主度","把下游返工排除在成功外","用职位代表能力"],prompt:"把该工作画成服务蓝图：角色、触发、资料、判断、AI 行为、人工验证、例外、交接、责任和最终结果；按新手/熟练/专家设计不同脚手架与权限，并写长期技能护栏。",exerciseTitle:"完成一次情境工作研究",exercise:"观察至少两人各完成一次任务，记录屏幕/工具切换、说出声判断和异常；提交服务蓝图、三处隐性知识和一个 AI 可能转移而非消除的成本。",misconceptions:["用户说法等于真实行为","自动化一步就缩短全流程","专家不需要 UX","新手有 AI 就能审查专家产物","采用率高等于能力提高"],quiz:{question:"AI 让新手更快但理解测验和维护质量下降，应怎样处理？",options:["只看速度继续扩大","加入预测/解释/验证脚手架并同时设能力保持指标","隐藏所有模型输出"],answer:1,explanation:"产品目标需同时覆盖即时产出与后续掌握/维护。"},summary:["工作流研究关注行为、例外和责任","AI 会重新分配验证劳动","专业能力影响互补收益","长期技能也是产品护栏"],mastery:{explain:"自动化率与端到端价值的差异",apply:"一张带责任的服务蓝图",boundary:"AI 提速却应限制采用的条件"},sources:[u("Claude Code Expertise","https://www.anthropic.com/research/claude-code-expertise"),u("AI Skills RCT","https://www.anthropic.com/research/AI-assistance-coding-skills")],
  }),
  chapter({
    prerequisite:"已冻结任务、用户层级、输入输出和失败成本。",goals:["用复杂度阶梯选择 prompt、RAG、workflow、agent 或训练","画能力矩阵与系统责任边界","做 build/buy 与退出可逆性决策"],
    concepts:c([["AIPM07","能力阶梯","确定性流程到开放 Agent 的不确定性逐级增加","最小方案能否达成任务"],["AIPM08","系统架构边界","模型、知识、工具、状态、策略和安全控制分层","错误由哪一层检测和恢复"],["AIPM09","Build/Buy/Portability","能力、数据权、锁定、成本和运营共同决定选型","供应商变化时能否迁移"]]),
    thesis:"模型强不等于系统应复杂；每增加检索、工具或自主循环，都必须由一种已观测失败和一套新评价证据来购买。",
    problem:"团队把 FAQ 直接设计成多 Agent，结果延迟、费用和不可复现错误暴涨。真正需求是版本化知识检索加三个确定性动作。应先用单调用+约束输出，只有跨步骤环境反馈确实必要才引入 Agent 循环。",
    mechanismTitle:"从调用到 Agent 的复杂度晋级",mechanism:"层级可写为规则/搜索→单模型结构输出→RAG→确定性 workflow→带工具单 Agent→多 Agent。知识放外部可更新层，权限由工具网关控制，状态与模型上下文分离，关键策略用代码/政策执行。每层绑定失败本体、增量收益和回退路径。",
    formula:"用 Pareto 而非单分：方案 $s$ 的向量 $(quality,latency,cost,risk,operability)$。复杂度净值 $NV_s=\\Delta V_s-\\Delta C_s-\\Delta R_s$；当更复杂方案在盲测与线上都无可重复净优势时被支配并淘汰。",
    formulaNotes:["任务是否真的需要环境反馈循环","知识更新频率与模型截止差异","工具写权限和幂等/撤销能力","供应商数据留存、可观测和出口能力"],
    evidence:[ev("2024-12-19","Building Effective Agents","https://www.anthropic.com/research/building-effective-agents","什么时候使用 workflow，什么时候使用 agent？","文章区分预定义代码路径的 workflow 与模型动态决定过程的 agent，并给出 routing、parallelization、orchestrator-worker 等模式。","实践建议从简单可组合模式开始，只在任务需要时增加自主性。","形成产品/架构共同的复杂度语言。","厂商实践文章不是独立对照实验，模式须用本地任务证据选择。"),ev("2019-01-28","Model Cards","https://arxiv.org/abs/1810.03993","购买或集成模型时需要什么能力边界？","模型卡记录用途、非用途、评测条件、群体表现和限制。","案例说明单一榜分不足以支持部署选择。","把供应商模型能力主张转成可审查输入。","卡片由提供方编写，需独立验证且常缺系统级风险。" )],
    diagram:"flowchart LR\n R[规则/搜索] --> M[单模型]\n M --> G[RAG]\n G --> W[确定性工作流]\n W --> A[工具型 Agent]\n A --> X[多 Agent]\n F[观测失败+盲测收益] -.晋级.-> G\n F -.晋级.-> A\n X --> B[可回退边界]",
    caseTitle:"企业 FAQ 到工单 Agent",case:"先用检索+引用回答，写操作必须经三个固定 workflow。只有当用户目标需跨系统追踪且预定流程覆盖率不足时，试验工具 Agent；写动作 sandbox、权限最小化、幂等键、预览确认和审计齐备。比较任务成功、人工分钟、P95、严重错误和恢复时间。",
    protocol:["列出每个失败应由知识、模型、流程或权限哪层处理","从最低复杂度实现可运行基线","每次只加一层并做盲测/成本消融","演练供应商不可用、模型降级和数据迁移"],decisions:["政策/权限不用 prompt 保证","状态独立于上下文窗口持久化","供应商合同覆盖数据权、日志和退出","多 Agent 需要证明优于单 Agent/工作流"],failures:["把 Agent 当默认 UI","模型同时承担策略与执行授权","工具无幂等和撤销","只看 token 单价不看总拥有成本","架构绑定供应商私有状态"],prompt:"针对任务给出规则、单模型、RAG、workflow、单 Agent、多 Agent 六层方案；逐层写它解决的已知失败、增量评测、成本、风险、回退和淘汰门槛，选择最小未被支配方案。",exerciseTitle:"完成一次复杂度消融",exercise:"对同一任务实现或详细设计简单方案和 Agent 方案；用 30 条盲测比较质量、延迟、成本、恢复，写出是否允许晋级的 ADR。",misconceptions:["Agent 比 workflow 更先进","模型卡等于独立验证","多模型投票必然可靠","Build 可避免锁定","Prompt 能执行权限"],quiz:{question:"固定三步审批流程被设计成自由 Agent，最合理的初始替代是什么？",options:["更多 Agent","确定性 workflow，仅让模型处理非结构输入","去掉审批"],answer:1,explanation:"固定控制路径应由代码执行，模型处理确需概率判断的部分。"},summary:["复杂度必须由失败证据购买","架构分离知识、状态、策略和权限","Pareto 选型包含运营与退出","自主性越高门禁越强"],mastery:{explain:"workflow 与 agent 的责任差异",apply:"一份复杂度阶梯 ADR",boundary:"多 Agent 不值得使用的任务"},sources:[u("Building Effective Agents","https://www.anthropic.com/research/building-effective-agents"),u("Model Cards","https://arxiv.org/abs/1810.03993")],
  }),
  chapter({
    prerequisite:"已有版本化任务合同和候选系统。",goals:["构造代表性、对抗性和时间外黄金集","把 rubric 写成可观察评分与严重错误","连接离线评测、线上实验与失败数据飞轮"],
    concepts:c([["AIPM10","评测合同","任务、样本、rubric、切片、成本和门禁的版本化协议","什么证据允许发布"],["AIPM11","黄金集与失败本体","自然样本、关键切片和事故反例形成最小真值资产","数据怎样随真实失败增值"],["AIPM12","评价器与 TEVV","自动、模型与人评是需校准的测量系统","分数是否稳定、公平且可复核"]]),
    thesis:"AI 产品最重要的专有资产往往不是 prompt，而是和真实工作绑定、持续吸收失败、能预测线上结果的评测合同。",
    problem:"团队靠 20 个 demo prompt 决策，修改一次系统 prompt 全部看起来更好，线上却在长输入和无答案上恶化。需要冻结盲集、按流量与风险采样、明确评分锚点，并防止开发者反复看到测试答案。",
    mechanismTitle:"从任务分布到发布门禁",mechanism:"数据分 natural、challenge、regression、shadow 四层；每条带来源、权限、切片、期望动作和严重度。Rubric 将正确性、支持、格式、策略遵循与任务完成拆开。评价器先用 gold 校准，再用于扩量；线上日志只经去隐私、归因和人工确认后进入回归。",
    formula:"总体估计 $\\hat M=\\sum_sw_s\\hat M_s$，同时报告最坏切片与置信区间。成对比较用同样本差值；顺序检验预先设 $\\alpha$、最小效应和停止界。风险门禁用 $N_{critical}=0$ 或上置信界，而非被平均分稀释。",
    formulaNotes:["样本权重来自真实流量还是方便数据","开发/测试污染如何审计","rubric 锚点能否让评审一致","线上代理指标是否预测用户结果"],
    evidence:[ev("2025-10-13","OpenAI GDPval","https://evals.openai.com/","前沿模型能否在真实高价值知识工作产物上比较？","GDPval 以职业任务和专家评分比较模型输出，强调产物质量而非封闭题答对率。","公开结果展示模型在不同职业任务的差异及人类专家比较。","推动产品评测接近真实工作产物。","任务样本、评分和模型版本限制外推；不能替代企业自己的流程结果。"),ev("2025-10-13","Evals Drive the Next Chapter of AI","https://openai.com/index/evals-drive-next-chapter-of-ai/","企业如何把 eval 变成产品迭代基础设施？","官方指南强调从真实任务、失败样本和 graders 建立 eval，并随模型/系统变化持续运行。","案例展示 eval 用于选型、提示和部署回归。","强化‘先评测合同后迭代’的交付流程。","厂商指南需补独立评价器、人评校准和跨供应商可移植性。" )],
    diagram:"flowchart LR\n W[真实任务/事故] --> S[采样+去隐私]\n S --> G[黄金集/切片]\n G --> R[Rubric+人评]\n R --> C[评价器校准]\n C --> P[离线门禁]\n P --> O[灰度/影子]\n O --> F[失败本体]\n F --> G",
    caseTitle:"客服 Agent 评测合同",case:"收集 500 条去隐私任务，按意图、客户价值、语言、工具权限和无答案分层；critical 包含错误退款、泄露和虚构政策。双人盲评 100 条校准 Judge。离线通过后只影子建议，再 5% 灰度；线上看一次解决率、人工分钟、投诉和严重事件。",
    protocol:["从真实工作采样并建立不可见盲集","写 rubric 正反锚点和错误严重度","校准自动/Judge 与双人盲评混淆矩阵","预注册离线门禁、灰度指标与停止规则"],decisions:["eval 数据与代码版本化但限制访问","critical 独立零容忍/上界门禁","模型/检索/prompt/tool 任一变更触发有范围回归","失败数据先归因再回流"],failures:["开发样本当测试集","只测理想可回答任务","Judge 未校准","用平均分吞掉事故","每次迭代改 rubric 追分"],prompt:"把我的 AI 任务转成 eval contract：自然/挑战/回归/影子四层数据，切片权重，rubric 锚点，critical 错误，基线，Judge—人评校准，置信区间，发布与停止规则。",exerciseTitle:"做一个 50 题可发布评测",exercise:"从真实任务建立 30 natural+10 challenge+10 regression，盲评两个系统，输出分切片指标、评价器偏差与 go/no-go 结论。",misconceptions:["公开榜单能代替产品 eval","样本越多越代表真实","Judge 分数无需置信区间","线上 A/B 可跳过安全门禁","事故样本直接训练即可"],quiz:{question:"新版本平均分提升，但出现一次错误退款，如何决策？",options:["平均分高就发布","按 critical 独立门禁阻断并归因修复","删除该样本"],answer:1,explanation:"严重错误不能由大量低风险成功抵消。"},summary:["Eval 是任务合同而非题库","黄金集需分层和防污染","评价器必须校准","风险门禁连接离线与线上"],mastery:{explain:"平均质量与风险门禁的差异",apply:"一份版本化 eval contract",boundary:"不应由 LLM Judge 决策的指标"},sources:[u("OpenAI Evals/GDPval","https://evals.openai.com/"),u("Evals Guide","https://openai.com/index/evals-drive-next-chapter-of-ai/"),u("NIST AI RMF","https://www.nist.gov/itl/ai-risk-management-framework")],
  }),
  chapter({
    prerequisite:"有评测合同和至少一个高风险未知。",goals:["选择验证最高风险假设的最小原型","区分可用性、能力和价值实验","预注册样本量、停止与回滚"],
    concepts:c([["AIPM13","风险优先原型","用最小保真度验证最不确定且最致命假设","该做纸面、礼宾、Wizard-of-Oz 还是代码"],["AIPM14","因果实验","对照、随机化和干扰控制识别产品改变的效果","观察提升是否真由系统造成"],["AIPM15","停止规则","在实验前定义成功、无效、有害与资源上限","何时停止堆功能"]]),
    thesis:"MVP 不是功能最少的产品，而是用最低成本产生最大决策信息的实验；高保真代码常常是最昂贵的学习方式。",
    problem:"自主行程规划看似需要全栈 Agent，但最大未知是用户是否愿意授权自动预订。可先由人工幕后生成方案、只让用户审阅模拟确认；若信任与控制失败，就无需先做复杂工具链。",
    mechanismTitle:"假设树、原型保真与顺序实验",mechanism:"把结果拆为 desirability、feasibility、viability、safety 假设，按不确定性×后果排序。纸面测理解，Wizard-of-Oz 测交互价值，离线回放测能力，影子模式测真实分布，受控灰度测行为结果。每阶段只增加回答下一个问题所需保真。",
    formula:"最小样本由基线 $p_0$、最小可接受效应 $\\delta$、显著性和功效决定；顺序检验必须使用有效边界，不能每天偷看后随意停止。决策价值可近似 $VOI=E[value\\ after\\ info]-value\\ now-cost\\ experiment$。",
    formulaNotes:["实验是在测可用性、模型能力还是业务因果","处理组和对照组是否同时期可比","跨用户/团队是否有污染","伤害指标是否实时可停止"],
    evidence:[ev("1984-01-01","Wizard of Oz Method","https://dl.acm.org/doi/10.1145/800049.801973","在能力尚未实现前能否研究人机交互？","由人类在幕后模拟系统响应，让用户体验目标交互并暴露需求与控制问题。","方法成为语音、对话和智能系统早期研究经典工具。","把学习与昂贵实现解耦。","人工模拟可能比真实系统更聪明/一致，必须记录可自动化性和操作成本。"),ev("2017-05-01","Online Controlled Experiments","https://experimentguide.com/","产品改动如何通过随机实验识别因果效果？","系统总结随机化单位、指标、方差、网络效应和实验诊断。","大量互联网实践表明预实验检查与护栏是可靠 A/B 基础。","为 AI 功能的价值验证提供因果骨架。","AI 输出非确定、稀有事故和长周期影响需要额外风险设计。" )],
    diagram:"flowchart LR\n H[假设树] --> R[不确定性×后果]\n R --> P[最低保真原型]\n P --> E{证据}\n E -->|无价值/有害| S[停止]\n E -->|机制不清| N[下一实验]\n E -->|通过| G[提高保真/灰度]",
    caseTitle:"自动预订旅行助手",case:"先用 Wizard-of-Oz 生成三个带证据方案，模拟但不真实下单；测用户理解、修改、授权边界与人工服务时间。只有愿意授权且后台处理可规模化才接工具 sandbox，先影子比较价格/约束，再小额可撤销灰度。",
    protocol:["画四类假设树并选最危险一个","选择能产生反证的最低保真原型","预注册主指标、护栏、样本和停止","记录人工幕后工作，判断是否可自动化"],decisions:["原型保真度随证据升级","功能路线图改为假设队列","灰度前完成撤销、客服和赔付流程","无最小效应或超预算即停止"],failures:["把可点击原型当价值证据","Wizard 人工服务不可规模化却忽略","频繁偷看 A/B","同时改多个因子","没有伤害停止开关"],prompt:"把功能计划改写为 desirability/feasibility/viability/safety 假设树，按不确定性×后果排序；为首项给最低保真原型、反证、主指标、护栏、样本和停止规则。",exerciseTitle:"用一天实验替代一个月开发",exercise:"选择一个 AI 功能，设计纸面或 Wizard-of-Oz 原型，实际找 3 人完成任务；提交观察、幕后成本、反证和下一步/停止决策。",misconceptions:["MVP 就是功能少","越像真实产品学习越多","A/B 自然无偏","没有显著差异就证明等价","用户喜欢 demo 就会付费"],quiz:{question:"最大未知是用户是否授权自动执行，最合适首个实验？",options:["先接全部生产 API","模拟执行并明确授权/撤销，观察真实选择","训练更大模型"],answer:1,explanation:"低保真可直接验证控制与信任假设。"},summary:["原型为决策信息服务","风险最高假设先测","因果实验需预注册和护栏","停止也是成功学习"],mastery:{explain:"MVP 与风险优先原型的区别",apply:"一份预注册实验卡",boundary:"高保真原型反而浪费的情形"},sources:[u("Wizard of Oz","https://dl.acm.org/doi/10.1145/800049.801973"),u("Experiment Guide","https://experimentguide.com/")],
  }),
  chapter({
    prerequisite:"有可运行原型、错误本体和明确人工责任。",goals:["设计可预测、可检查、可撤销和可接管交互","校准信任而非最大化信任","保护用户技能、知情与决策自主"],
    concepts:c([["AIPM16","不确定性表达","用证据、范围和行动后果呈现系统不知道什么","何时回答、请求信息或拒绝"],["AIPM17","人机控制","预览、确认、撤销、权限和接管形成可恢复闭环","高风险动作需要多少摩擦"],["AIPM18","信任与技能","用户依据反馈形成依赖和验证习惯","产品是否造成过度依赖或能力退化"]]),
    thesis:"好的 AI UX 不是让模型永远显得聪明，而是让用户准确预测其能力、发现错误、保持控制并从失败中恢复。",
    problem:"界面给所有建议显示同样绿色勾，用户把语言流畅当可靠；确认弹窗重复出现后形成机械点击。应按动作风险设计渐进权限，在决策点展示来源/差异/不确定，并让确认包含真正可判断的信息。",
    mechanismTitle:"信任校准与可逆行动",mechanism:"展示 uncertainty 要连接下一动作：缺资料→请求，低置信/高风险→人工，来源冲突→并列，系统限制→拒绝。预览以 diff、证据和后果呈现；确认不是‘是否继续’，而是让用户验证关键变量。可撤销、幂等与审计让错误恢复真实存在。",
    formula:"信任校准可看 reliance 与 correctness 的匹配：过度依赖 $OR=P(accept|wrong)$，低度依赖 $UR=P(reject|right)$。UX 优化需同时降低两者和任务成本；仅提升 accept rate 会鼓励错误目标。",
    formulaNotes:["置信来自校准概率还是装饰性措辞","用户是否有足够信息审查","撤销在真实系统是否完整生效","长期技能与短期速度是否并测"],
    evidence:[ev("2019-01-01","People + AI Guidebook","https://pair.withgoogle.com/guidebook/","人机 AI 产品有哪些可复用交互问题？","指南覆盖用户需求、数据、心智模型、解释、反馈、错误与控制，并以活动帮助团队落地。","大量案例把抽象责任原则转为界面和流程检查。","提供 AI PM/设计/工程共同语言。","实践指南不是因果证据；具体模式需在用户和风险场景验证。"),ev("2026-01-29","AI Assistance Coding Skills RCT","https://www.anthropic.com/research/AI-assistance-coding-skills","产品使用方式怎样影响学习？","随机实验在任务后测技能，并分析不同 AI 交互策略。","平均技能掌握下降约 17%，但主动提问、解释等模式更有利。","支持把认知参与设计成体验指标。","短期编码任务不应外推所有知识工作。" )],
    diagram:"flowchart LR\n I[用户意图] --> P[AI 计划+证据]\n P --> R{风险/不确定}\n R -->|低| A[可撤销执行]\n R -->|中| V[Diff/关键变量确认]\n R -->|高| H[人工/拒绝]\n A --> F[结果反馈]\n V --> F\n H --> F\n F --> C[心智模型/权限更新]",
    caseTitle:"财务报销审核助手",case:"低风险归类可批量预览撤销；金额、税务主体和疑似欺诈只给证据并转人工。界面高亮原文差异、显示规则来源和缺失材料，不展示未经校准百分比。测错误建议接受率、人工时间、撤销成功与一月后政策理解。",
    protocol:["列出每个 AI 状态用户需知道和能做什么","按动作后果设计自动/预览/确认/人工层级","用错误模型原型做可用性测试，不只测成功","记录 accept/reject 与真实正确性构成校准矩阵"],decisions:["不确定性必须触发具体可选动作","确认展示关键差异而非通用警告","权限从只读逐级获得且可撤销","技能保持进入长期产品指标"],failures:["用语气表达置信","弹窗疲劳代替控制","解释太长却无可行动证据","接受率当信任成功","人工接管没有上下文"],prompt:"审查 AI 交互的每个状态：用户看见什么、能验证什么、错误后能否撤销、何时接管；输出自动/预览/确认/拒绝权限矩阵，并设计过度依赖与技能保持指标。",exerciseTitle:"设计一次失败也可用的体验",exercise:"为一个写动作画正常、低置信、来源冲突、工具失败和越权五条流程；让 3 人判断是否执行，比较其选择与真实正确性。",misconceptions:["用户越信任越好","显示百分比就是透明","确认一步保证责任","可撤销按钮等于后端可恢复","解释越详细越安全"],quiz:{question:"用户总接受流畅但错误建议，应该优化什么？",options:["接受率","错误时接受概率与关键证据/控制设计","回答长度"],answer:1,explanation:"目标是信任与正确性匹配，而不是最大化依赖。"},summary:["信任要校准不是最大化","不确定性连接行动","高风险动作需要真实可逆与接管","产品也要保护用户能力"],mastery:{explain:"过度依赖和低度依赖",apply:"一个风险分级控制矩阵",boundary:"解释不能解决的控制风险"},sources:[u("PAIR Guidebook","https://pair.withgoogle.com/guidebook/"),u("AI Skills RCT","https://www.anthropic.com/research/AI-assistance-coding-skills")],
  }),
  chapter({
    prerequisite:"已有任务成功指标、风险护栏和候选架构。",goals:["建立结果—任务—系统三层指标树","测质量、延迟、成本与容量 Pareto","计算含人工、失败和平台成本的单位经济"],
    concepts:c([["AIPM19","指标树","业务结果由用户任务和系统行为逐层连接","哪个领先指标可驱动迭代"],["AIPM20","质量成本延迟","模型、检索、缓存与路由形成多目标前沿","何时用更强模型"],["AIPM21","单位经济","每个成功任务的全部可变与分摊成本","规模增加会改善还是放大亏损"]]),
    thesis:"Token 便宜不等于产品经济性改善；更长上下文、更高重试、人工审查和失败补偿可能把单次调用降价全部吃掉。",
    problem:"摘要模型单次成本降 50%，但新版本输出更长、重试更多、人工修订没有下降，客户成功团队还需处理更多争议。若只报每百万 token 价格，会错误扩张。应算每个通过质量门槛的成功任务成本。",
    mechanismTitle:"指标树与成功任务成本",mechanism:"North Star 连接客户结果，任务层记录完成/时间/修订，系统层记录召回、模型、工具、延迟和失败。路由器按风险/难度选择模型，缓存和批处理降低成本，但不能改变语义版本。容量模型用到达率、并发和服务时间预测 P95 与降级。",
    formula:"单位成功成本 $C_s=(C_{model}+C_{retrieval}+C_{tools}+C_{human}+C_{failure}+C_{platform})/N_{successful}$；毛利 $GM=(Revenue-variable\\ cost)/Revenue$。Little 定律 $L=\\lambda W$ 帮助估算并发，但长尾和限流需排队仿真。",
    formulaNotes:["成功分母是否通过质量与风险门槛","人工审查和返工是否计入","token 价格是否含缓存/批量/区域差异","高峰 P95 和故障降级是否可承受"],
    evidence:[ev("2026-04-06","AI Index 2026: Cost Trends","https://hai.stanford.edu/assets/files/ai_index_report_2026.pdf","推理成本和能力趋势怎样改变产品选型？","报告按可比较能力与时间整理训练、推理与产业数据。","显示部分能力价格快速下降，同时高端训练、能耗和采用结构继续变化。","支持动态路由和持续重算商业模型。","公开价格不等于企业实际总成本，质量基准也未必匹配产品。"),ev("2026-06-10","Economic Index 2026","https://www.anthropic.com/research/economic-index-june-2026-report","AI 使用的任务结构与自动化程度怎样影响价值估算？","任务级使用数据揭示不同职业、地区与交互形式的采用差异。","真实使用并非均匀自动化，许多场景仍是增强与多轮协作。","提醒容量和价值模型基于任务结构。","厂商平台样本与分类口径限制整体经济推断。" )],
    diagram:"flowchart TD\n B[客户结果] --> T[任务成功/时间/留存]\n T --> Q[质量/风险]\n T --> S[延迟/可用性]\n T --> C[模型+工具+人工+失败成本]\n Q --> P[Pareto/路由]\n S --> P\n C --> P\n P --> U[单位经济与定价]",
    caseTitle:"企业文档审核 SaaS",case:"按简单分类、普通抽取和高风险审查三类路由。分母只计算满足准确、证据和时限的任务；成本含 OCR、检索、模型、人工复核、重试与客户补偿。用真实到达曲线压测并设高峰降级：延迟超限转小模型/队列，高风险不降级为自动通过。",
    protocol:["画结果—任务—系统指标树","逐请求追踪 token、工具、重试和人工成本","按质量门槛画候选方案 Pareto","用高峰到达与故障场景做容量/毛利敏感性"],decisions:["用每成功任务成本而非每调用成本","高风险路由不以便宜覆盖安全","定价与价值单位而非 token 绑定","成本/质量漂移触发路由回归"],failures:["忽略人工与失败成本","用平均延迟替代 P95/P99","缓存跨权限/版本复用","把拒绝算失败但不看风险","规模预测假设重试率不变"],prompt:"建立 AI 产品指标树与单位经济：结果、任务、系统；计算每成功任务的模型/检索/工具/人工/失败/平台成本，按风险切片画质量—P95—成本 Pareto，并做 2× 流量和故障敏感性。",exerciseTitle:"算清一项 AI 功能的真实毛利",exercise:"采样 50 次任务，记录完整成本和是否通过验收；比较两模型与一路由方案，提交每成功任务成本、P95 和三种流量情景。",misconceptions:["Token 降价等于毛利提升","平均成本足够","大模型只用于高价值就合理","缓存不影响正确性","拒答一定降低价值"],quiz:{question:"单次调用降价但人工修订增加，应看哪个核心量？",options:["每百万 token 价","每个通过质量门槛的成功任务总成本","模型参数"],answer:1,explanation:"单位经济必须把人工和失败纳入同一分母。"},summary:["指标树连接系统与结果","选型是多目标 Pareto","单位成功成本含隐藏劳动","容量与降级必须情景化"],mastery:{explain:"调用成本与成功任务成本",apply:"一份端到端单位经济模型",boundary:"不能为成本自动降级的请求"},sources:[u("AI Index 2026","https://hai.stanford.edu/assets/files/ai_index_report_2026.pdf"),u("Economic Index 2026","https://www.anthropic.com/research/economic-index-june-2026-report")],
  }),
  chapter({
    prerequisite:"已有数据流、动作权限、目标市场和风险分级。",goals:["把 NIST 风险流程映射到产品生命周期","建立 ISO 42001 式责任与证据体系","按 EU AI Act 等适用规则做义务分析"],
    concepts:c([["AIPM22","AI 风险管理","治理、映射、测量、处置形成持续闭环","哪些风险被接受、缓解或禁止"],["AIPM23","隐私与安全","数据最小化、权限、攻击面和供应链共同决定控制","模型能看到和做什么"],["AIPM24","合规治理","角色、用途和地区触发不同义务与证据","谁负责批准、监测和报告"]]),
    thesis:"治理不是上线前填表，而是把允许用途、数据、动作、责任、证据和退出持续编码进产品与组织。",
    problem:"招聘助手处理简历并排序，涉及敏感信息、潜在高风险用途、供应商模型和人工决策。删姓名不足以消除代理偏差；免责声明也不能替代影响评估、数据权利、监督有效性与日志。",
    mechanismTitle:"Govern—Map—Measure—Manage 与管理体系",mechanism:"NIST AI RMF 用 GOVERN 贯穿 MAP/MEASURE/MANAGE；GAI Profile 增补生成 AI 特有风险。ISO/IEC 42001 以管理体系要求组织建立政策、角色、目标、风险、运行控制、审计和改进。法律分析先判角色、系统/用途、地区、禁止或高风险分类，再映射技术/流程证据。",
    formula:"风险登记至少含 $risk=(hazard,affected,scenario,severity,likelihood,controls,evidence,residual,owner)$。数据权限可用主体×资源×动作×目的×时间矩阵；残余风险超容忍阈值时必须缩小用途或停止，不能用收益平均。",
    formulaNotes:["法律适用日期与过渡条款","提供者/部署者/进口商等角色","人工监督是否真有时间与能力","第三方模型/数据/插件供应链责任"],
    evidence:[ev("2024-07-26","NIST AI RMF Generative AI Profile","https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence","生成 AI 风险怎样落入可执行风险管理？","Profile 在 AI RMF 四函数下组织内容来源、虚构、隐私、信息安全、人机配置等风险与行动。","提供跨行业自愿框架，可转为风险登记、TEVV 和治理控制。","建立生成 AI 产品通用风险词汇。","非强制且不替代地区法律、领域标准或具体安全论证。"),ev("2023-12-18","ISO/IEC 42001","https://www.iso.org/standard/42001","组织怎样建立可审计 AI 管理体系？","标准规定 AI 管理体系的建立、实施、维护和持续改进要求。","可用于把政策、职责、风险与内部审核制度化。","治理从单项目文档提升为组织能力。","标准付费正文且认证不证明单个模型安全或合法。"),ev("2026-08-02","EU AI Act applicability","https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai","欧盟 AI Act 到 2026 年的适用节奏与分类是什么？","官方页面说明风险分级、治理结构与分阶段适用；多数规定自 2026-08-02 起适用，高风险部分另有延展。","为面向欧盟产品提供当前日期基线。","必须把产品角色/用途映射到具体义务和时间。","官方概览不是法律意见；修订、指南与成员国执行需持续核对。" )],
    diagram:"flowchart LR\n G[GOVERN 角色/政策] --> M[MAP 用途/人群/数据]\n M --> E[MEASURE TEVV/影响]\n E --> A[MANAGE 控制/接受/停止]\n A --> O[监测/事件]\n O --> G\n L[法律/标准/合同] --> G\n L --> A",
    caseTitle:"招聘排序助手的风险控制",case:"用途限制为给招聘员整理证据，禁止自动淘汰；删除非必要敏感字段但审计代理变量。建立候选人通知/申诉、分群性能、人工覆盖、供应商数据留存、提示注入和越权测试。法务确认角色和适用地区；高风险结论保留来源和决策者。",
    protocol:["画数据、模型、工具、第三方和人类决策流","建立风险场景/受影响者/控制/证据/owner 登记","将 NIST 函数、ISO 管理项和适用法律映射","桌面演练泄露、歧视、越权与供应商中断"],decisions:["风险 owner 与功能 owner 同期任命","权限最小化并按目的/时间限制","高风险用途保留申诉和人工有效监督","合规结论记录日期、角色和法源"],failures:["匿名化等于无偏","免责声明替代控制","证书等于产品安全","人类在环只有确认按钮","用旧法律摘要做永久判断"],prompt:"为该 AI 产品建立风险登记：用途/非用途、受影响者、数据流、权限、威胁、伤害情景、控制、验证、残余风险和 owner；映射 NIST AI RMF、ISO 42001 与目标地区当前法律，标注证据日期和需法律确认项。",exerciseTitle:"完成一次影响评估",exercise:"选一个涉及个人数据或决策的功能，画数据/动作流，写至少 10 个风险场景和控制证据；用一场桌面事故演练验证接管与通知。",misconceptions:["合规是法务最后负责","去标识化消除所有隐私","有人工就不是高风险","NIST/ISO 自动满足法律","日志越多越安全"],quiz:{question:"招聘模型最后由人点击确认，是否自动构成有效监督？",options:["是","否，还需时间、信息、能力与拒绝/纠正权","只要写免责声明即可"],answer:1,explanation:"形式上的人类在环不等于能够发现和改变错误。"},summary:["治理贯穿生命周期","风险场景连接伤害、控制和证据","标准、法律和产品角色需映射","残余风险可要求缩小或停止"],mastery:{explain:"框架、管理体系与法律的差异",apply:"一份有 owner 的风险登记",boundary:"必须寻求法务/领域授权的判断"},sources:[u("NIST GAI Profile","https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence"),u("ISO 42001","https://www.iso.org/standard/42001"),u("EU AI Act","https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai")],
  }),
  chapter({
    prerequisite:"评测、权限、风险与回滚均有明确 owner。",goals:["建立多组件变更的发布门禁","设计反馈分流、事件响应和恢复","用观测性把线上失败连回可复现回归"],
    concepts:c([["AIPM25","版本与发布","模型、prompt、知识、工具、策略和评价器组成联合版本","哪些变更需哪些回归"],["AIPM26","运行反馈","用户反馈、系统信号和业务结果按机制分流","哪些数据值得进入学习闭环"],["AIPM27","事件与恢复","检测、遏制、回滚、通知和复盘限制伤害","故障时系统怎样安全降级"]]),
    thesis:"AI 产品不是发布一次，而是多个不稳定依赖持续变化的运行系统；运营核心是让每次变化可观察、可比较、可回退。",
    problem:"供应商静默升级模型后，工具调用 JSON 合法率下降；知识库同时更新使团队无法定位。若没有联合 manifest、影子流量和组件消融，只能凭感觉改 prompt，事故会反复。",
    mechanismTitle:"联合版本、灰度门禁与事件闭环",mechanism:"Release manifest 记录模型快照、prompt、检索、索引、工具 schema、策略、依赖与评价器。离线门禁→影子→内部→小流量→扩容，每阶段有主指标、护栏与自动停止。事件先冻结证据、限制权限/流量、回退稳定组合，再做无责机制复盘。",
    formula:"变更风险 $R_c=blast\\ radius\\times uncertainty\\times irreversibility$ 决定灰度比例。SLO 以任务成功、P95、严重错误和恢复时间定义；error budget 用于平衡发布速度，但安全/合规事故不被普通可用性预算抵消。",
    formulaNotes:["供应商快照是否真的固定","日志能否重放且遵守隐私","回滚是否覆盖索引/状态迁移","用户反馈是否有选择与表达偏差"],
    evidence:[ev("2017-03-01","The ML Test Score","https://research.google/pubs/the-ml-test-score-a-rubric-for-ml-production-readiness-and-technical-debt-reduction/","怎样评价机器学习系统的生产就绪而非离线分数？","Rubric 覆盖数据、模型、基础设施与监控测试，并以等级推动工程成熟。","大量生产经验展示技术债来自跨组件依赖和变化。","为 AI 发布门禁提供经典骨架。","生成式系统、Agent 权限与现代供应链需扩充，分数不等于安全认证。"),ev("2026-08-26","Independent Research on Real-World AI Use","https://www.anthropic.com/research/enabling-independent-research","如何让外部研究者持续评估真实 AI 使用和影响？","公告提供截至 2026-08 的研究访问/合作方向，强调隐私保护、独立研究与真实使用证据。","说明前沿产品治理正从内部指标扩展到外部可审查证据。","支持运营数据的独立验证与透明机制。","项目机制和可访问数据范围仍受平台约束，不能替代产品自己的监控。" )],
    diagram:"flowchart LR\n M[联合版本 manifest] --> E[离线回归]\n E --> S[影子]\n S --> C[小流量 canary]\n C --> G[渐进扩容]\n G --> O[任务/风险观测]\n O --> I{事件?}\n I -->|是| R[遏制/回滚/通知]\n R --> P[机制复盘+回归]\n P --> E",
    caseTitle:"工具型客服 Agent 的安全发布",case:"每次发布绑定 8 个组件哈希。影子重放去隐私任务，5% 灰度只读工具；写动作要预览确认。严重错误、工具越权或支持率跌破下界自动断写切换检索回答。事故保留 trace、输入/输出、政策版本与工具返回，24 小时内补回归。",
    protocol:["建立联合版本清单和可重放 trace","按风险定义离线/影子/灰度门禁","演练供应商变化、索引损坏和工具超时","把反馈按数据/检索/模型/工具/UX/政策归因"],decisions:["发布单位是系统组合而非单模型","高风险写权限单独开关","事件先遏制后根因分析","复盘行动必须对应 owner、期限和回归"],failures:["同时变更多个组件","回滚只换模型不换索引","把 thumbs-down 当真值","日志无法复现或泄露敏感信息","事故归因‘模型幻觉’后结束"],prompt:"为这次 AI 系统发布生成 manifest、分层回归、影子/canary 流量、SLO、严重错误停止、降级/回滚和事件演练；把每项监测绑定组件与 owner。",exerciseTitle:"做一次桌面发布与事故演练",exercise:"模拟模型+知识库更新，写发布清单并注入工具超时/错误权限；记录检测、遏制、回滚和补测用时，输出改进项。",misconceptions:["模型 API 名称就是固定版本","灰度只看可用性","用户差评都是模型问题","有日志即可重放","回滚天然无状态风险"],quiz:{question:"模型与知识库同时更新后质量下降，最大流程缺陷是什么？",options:["用户太少","联合版本与单因子/影子证据不足","模型温度低"],answer:1,explanation:"无法确定变化来源会阻碍可靠回退和修复。"},summary:["联合版本是发布对象","灰度需质量与风险门禁","反馈先归因再学习","事件闭环以可恢复和回归结束"],mastery:{explain:"模型版本与系统版本的差异",apply:"一份含演练的发布 runbook",boundary:"不能自动降级的安全条件"},sources:[u("ML Test Score","https://research.google/pubs/the-ml-test-score-a-rubric-for-ml-production-readiness-and-technical-debt-reduction/"),u("Independent AI Research 2026","https://www.anthropic.com/research/enabling-independent-research")],
  }),
  chapter({
    prerequisite:"完成从机会、评测、经济、治理到运营的闭环。",goals:["区分短期模型优势与可累积系统资产","设计数据权利、评测和工作流复利","把组织学习速度变成战略指标"],
    concepts:c([["AIPM28","护城河资产","专有工作流、合法数据、评价器、分发与信任能随使用增值","什么资产竞争者难以复制"],["AIPM29","学习飞轮","使用产生可归因失败，失败改善评测、系统和流程","反馈是否真的提升下一轮"],["AIPM30","组织能力","跨产品、领域、工程、风险的决策节奏与责任","团队能否比模型变化更快学习"]]),
    thesis:"当基础模型能力和价格快速商品化，持续优势来自嵌入真实工作、拥有合法反馈、能测量结果并比别人更快安全学习，而不是一组 prompt。",
    problem:"竞品可在一周内复制界面和接入同一模型；若产品没有独特分发、系统集成、领域协议、评测资产与反馈权利，先发只是短暂。相反，服务一个窄流程可积累异常、rubric、信任和转换成本。",
    mechanismTitle:"从使用到可归因学习的复利",mechanism:"有效飞轮是：真实任务→可观测结果→按机制归因→高价值失败入评测→方案实验→安全发布→更好结果/更多合意使用。任一环缺失都会变成数据堆积。组织用同一证据包做产品、架构、风险和商业决策，缩短 learning cycle time。",
    formula:"学习复利可用 $A_{t+1}=A_t+q\\cdot f\\cdot r-c$ 描述：有效资产由反馈质量 $q$、频率 $f$、可归因/转化率 $r$ 增长并扣治理成本。战略看 cohort 结果、评测预测线上相关、修复 lead time 和迁移成本，不只看 MAU。",
    formulaNotes:["反馈是否获合法权利且代表目标用户","错误能否归因到可修改层","改进是否通过盲测与真实结果验证","资产是否可迁移到模型/供应商变化"],
    evidence:[ev("2026-06-10","Economic Index 2026","https://www.anthropic.com/research/economic-index-june-2026-report","哪些任务和协作方式在真实使用中形成采用？","任务级观测展示 AI 使用嵌入不同职业活动的深度和差异。","采用集中在具体可数字化任务，增强与自动化并存。","支持以工作流深度而非通用聊天流量评估战略。","单平台选择偏差与短期使用不能直接证明长期生产率。"),ev("2026-06-16","Agentic Coding Expertise","https://www.anthropic.com/research/claude-code-expertise","工具能力相同为何结果仍因用户专业度不同？","对大规模会话分析任务分解、验证和工具行为与成功的关系。","专家更能把模型能力转成可靠结果。","表明组织流程、领域知识和使用习惯本身是互补资产。","观察性关联不证明单一培训干预会产生同等收益。"),ev("2026-04-06","AI Index 2026","https://hai.stanford.edu/assets/files/ai_index_report_2026.pdf","基础模型能力、成本与产业竞争怎样变化？","年度数据汇总模型、投资、采用、责任与政策。","快速能力扩散与价格变化削弱静态模型接入的长期稀缺性。","支持把战略重心移到互补资产和学习速度。","宏观趋势不决定单个市场，需结合客户集中与单位经济。" )],
    diagram:"flowchart LR\n U[合意真实使用] --> O[可观测结果]\n O --> F[失败归因/反馈权利]\n F --> E[专有 eval/知识]\n E --> X[产品/流程实验]\n X --> R[安全发布]\n R --> V[更高用户价值/信任]\n V --> U\n M[可替换基础模型] --> X",
    caseTitle:"垂直合规审查产品的三年飞轮",case:"第一年只覆盖一个高频文档，积累专家 rubric、条款版本和错误本体；第二年把评测预测到修订时间和事故率，扩展相邻流程；第三年用同一安全/证据底座切换模型。护城河指标是回归资产覆盖、专家分钟下降、事故修复速度、客户流程嵌入和数据授权续约。",
    protocol:["列当前资产并区分可复制功能与可复利资产","画反馈获得、授权、归因、验证和发布链","给每个资产定义增长/衰减指标","模拟基础模型免费、供应商中断和强竞品复制"],decisions:["优先拥有 eval、工作流与结果反馈接口","合同明确衍生数据和退出权","组织节奏围绕学习周期而非发布数量","不形成资产的定制需求谨慎承接"],failures:["把 prompt 当护城河","收集大量不可归因日志","以锁定客户代替创造价值","追逐每次模型发布重写产品","组织只奖励上线不奖励证伪"],prompt:"审查我的 AI 产品战略：列可一周复制的功能与会随合意使用复利的资产；为工作流、数据权、eval、分发、信任、组织能力画飞轮，给增长/衰减指标和模型商品化压力测试。",exerciseTitle:"写一份反模型战略备忘录",exercise:"假设明天同等模型免费且竞品复制 UI，列出仍存在的三项优势；若没有，设计未来 90 天可合法积累的最小评测/工作流资产。",misconceptions:["先发接模型就是护城河","用户数据天然归产品所有","锁定越强越有价值","模型越大战略越稳","功能数量形成复利"],quiz:{question:"竞品能接同一模型并复制 UI，最难复制的合理资产是什么？",options:["系统 prompt","与真实结果绑定、合法持续更新的领域评测和工作流","更多按钮"],answer:1,explanation:"可归因反馈和深度流程嵌入会随使用增值且支持切换模型。"},summary:["模型接入是可替换投入","护城河来自互补和可复利资产","反馈只有归因/授权/验证后才有价值","组织学习速度是战略能力"],mastery:{explain:"功能优势与复利资产的区别",apply:"一张有指标的学习飞轮",boundary:"看似数据飞轮其实不增值的链"},sources:[u("AI Index 2026","https://hai.stanford.edu/assets/files/ai_index_report_2026.pdf"),u("Economic Index 2026","https://www.anthropic.com/research/economic-index-june-2026-report"),u("Claude Code Expertise","https://www.anthropic.com/research/claude-code-expertise")],
  }),
];

export default {
  active:[{name:"问题空间",action:"观察一个真实工作并写任务链",evidence:"现状蓝图+非 AI 基线"},{name:"AI 适配度",action:"评估输入、评测和可恢复性",evidence:"适配度/风险表"},{name:"机会组合",action:"给候选做区间评分和停止规则",evidence:"机会证伪卡"}],
  frontierSignals:["产品竞争从能否生成转向评测、工作流、权限和结果闭环","2026 实证显示 AI 收益受领域专业度和使用方式显著调节","模型成本下降不保证每成功任务成本或毛利改善","EU AI Act 多数规则自 2026-08-02 起适用，治理日期与角色必须持续核对","可持续护城河更接近合法反馈、专有 eval、流程嵌入和组织学习"],
  projectCriteria:["真实用户观察与三层机会基线","版本化 eval contract 和 critical 门禁","从最低复杂度到候选架构的消融","信任/权限/人工接管和风险登记","单位经济、灰度、回滚和学习飞轮"],
  branchRules:["AIPM01—06 未完成前不进入 Agent 方案","已明确任务可跳到 AIPM10 建最小 eval","任何写动作必须同时学习 AIPM16—27","涉及个人决策/欧盟市场优先 AIPM22—24"],
  sourceRules:["能力/成本/采用使用官方报告并保留样本定义","产品方法用原始指南/论文并以本地实验验证","法规只引用官方现行页面并标日期/角色","厂商研究视为有价值但有选择偏差的证据"],
  ledger:[{date:"2026-01-29",label:"AI Skills RCT",url:"https://www.anthropic.com/research/AI-assistance-coding-skills",supports:"AI 辅助组短期技能掌握约低 17%",limit:"特定编码任务与样本"},{date:"2026-04-06",label:"AI Index 2026",url:"https://hai.stanford.edu/assets/files/ai_index_report_2026.pdf",supports:"能力、成本、采用与治理年度趋势",limit:"宏观数据不替代本地需求"},{date:"2026-06-10",label:"Economic Index",url:"https://www.anthropic.com/research/economic-index-june-2026-report",supports:"任务层真实使用和增强/自动化",limit:"单平台选择偏差"},{date:"2026-06-16",label:"Agentic Coding Expertise",url:"https://www.anthropic.com/research/claude-code-expertise",supports:"约 40 万会话中的专业度收益差异",limit:"观察性代理"},{date:"2026-08-02",label:"EU AI Act applicability",url:"https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai",supports:"多数条款当前适用节点",limit:"具体角色/高风险延期需法律确认"}],
  conflicts:[{title:"自动化率 vs 真实价值",body:"任务完成更快可能转移审查、返工和技能成本；必须测端到端结果。"},{title:"通用模型能力 vs 垂直护城河",body:"模型快速扩散削弱静态接入优势，却提高工作流、评测和数据权的互补价值。"}],
  updateTriggers:["基础模型价格/能力改变架构 Pareto","真实用户研究改变任务和结果定义","评价器与线上结果相关性下降","法律、标准、供应商数据条款或高风险分类变化"],
  overviewSources:[u("AI Index 2026","https://hai.stanford.edu/assets/files/ai_index_report_2026.pdf"),u("NIST GAI Profile","https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence"),u("Economic Index 2026","https://www.anthropic.com/research/economic-index-june-2026-report")],
  details,
};
