import { chapter, concepts as c, ev, u } from "./shared.mjs";

const details = [
  chapter({
    prerequisite: "无需模型前置；先选一个真实语言任务，并准备至少 30 条来自目标场景、保留上下文和来源的样本。",
    goals: ["把自然语言需求拆成单位、语境、标签与行动", "把标注分歧建模为信号而非一律当噪声", "建立数据说明、非 AI 与简单统计基线"],
    concepts: c([["NLPF01","语言任务本体","规定文本单位、上下文、输出和下游行动","任务究竟是分类、抽取、排序、生成还是交互"],["NLPF02","语料与采样","文本是由人群、平台、时间和政策共同产生的观测","语料能代表谁以及漏掉谁"],["NLPF03","标注分歧","歧义、知识差异与价值判断会形成结构化不一致","用单标签、分布标签还是升级人工裁决"]]),
    thesis: "NLP 的第一对象不是模型而是带语境的语言行为；删掉说话者、时间、指代和行动后，所谓标签常常已经改变了任务。",
    problem: "客服消息“这个月还是多扣了”不能脱离账单、上轮对话和用户身份判断。若把单句随机送给标注员做意图分类，高一致率可能来自被迫猜一个粗标签；上线后系统却要决定查询哪张账单、能否退款以及何时转人工。先冻结对话窗口、输出 schema、可行动作与不可接受错误，再谈模型。",
    mechanismTitle: "从语言事件到可学习观测",
    mechanism: "把一条样本表示为 $z=(x,c,s,t,y,a)$：文本 $x$、语境 $c$、说话者/社群 $s$、时间 $t$、标注 $y$ 和下游动作 $a$。标注员不是无噪声传感器；其判断来自潜在解释 $h$ 与指南。应保存每位标注者、理由和不确定度，通过试标—分歧审计—指南修订循环区分可消除歧义、真实多义与规范冲突。",
    formula: "Krippendorff 的 $\\alpha=1-D_o/D_e$ 比简单一致率更能扣除偶然一致；但 $\\alpha$ 低不自动等于数据差。对第 $i$ 个样本保留标签分布 $q_i(y)=\\frac1m\\sum_j\\mathbf1[y_{ij}=y]$，可用 $-\\sum_yq_i(y)\\log p_\\theta(y|x_i,c_i)$ 训练并评估分歧校准。",
    formulaNotes: ["样本单位和部署时可见语境是否一致", "标注员背景是否覆盖真实用户群", "标签集合是否允许无法判断、多标签与升级", "分歧来自指南缺陷还是合理多元解释"],
    evidence: [
      ev("2018-05-17","Data Statements for NLP","https://aclanthology.org/Q18-1041/","怎样让语言数据的适用人群和生成条件不再隐形？","论文提出描述语言变体、说话者、标注者、采集过程和用途的 data statement，使数据集声明携带社会语言学边界。","该框架被后续 NLP 数据治理广泛采用，核心产物不是一个分数，而是可审计的数据语境。","把‘数据来自哪里’升级为模型能力声明的一部分。","完整声明仍不能修复缺失群体、非法授权或错误标签，需要采样与治理动作。"),
      ev("2022-05-26","DynaSent: Dynamic Sentiment Analysis","https://aclanthology.org/2021.acl-long.186/","固定情感数据为何会让模型学到静态捷径？","数据通过模型在环迭代收集，重点加入现有模型难例并保留多标注者判断。","动态收集改变样本难度和分歧分布，暴露固定基准无法覆盖的语言现象。","支持把失败样本持续回流为数据资产。","在环收集也会受当前模型诱导，不能代表全部自然分布。"),
    ],
    diagram: "flowchart LR\n  U[用户/社群] --> E[语言事件+语境]\n  E --> S[采样与授权]\n  S --> G[指南与试标]\n  G --> A[多标注+理由]\n  A --> D{分歧审计}\n  D -->|可消除| G\n  D -->|真实多义| Q[分布标签/升级]\n  Q --> M[模型与行动评测]",
    caseTitle: "账单客服的意图与行动联合定义",
    case: "以完整会话轮次为样本，标签分为查询、异议、退款请求和无法判断，另记录账期、指代对象与期望动作。三名标注员先独立标 50 条；按现象而非只按标签统计分歧。模型评测同时报告意图 macro-F1、槽位边界 F1、无法判断校准和错误动作成本；涉及退款且证据不足必须转人工。",
    protocol: ["写任务卡：用户、语言事件、最小上下文、输出和下游动作", "分层抽取 100 条自然样本，保留时间、渠道和授权元数据", "三人试标并逐条归因分歧，修订指南但保留合理异议", "用规则/关键词和简单分类器做基线，按现象与人群切片"],
    decisions: ["PRD 绑定语言输入与实际动作而非抽象准确率", "数据表保留来源、许可、语种/变体、上下文和标注历史", "无法判断成为合法输出并绑定人工升级", "上线反馈按错误本体进入下一轮采样"],
    failures: ["把句子从对话中剥离", "强迫多义样本得到唯一真值", "随机切分同一用户或模板改写", "用多数语言平均分掩盖小语种失败", "把标注员一致当成社会共识"],
    prompt: "审查这个 NLP 需求。先输出语言事件、说话者、时间、必要语境、输出 schema、动作和错误成本；再设计采样、三人试标、分歧本体、非 AI 基线与切片。任何无法从材料确定的含义必须标为待澄清。",
    exerciseTitle: "完成一份可审计标注试验", exercise: "从真实任务抽取 30 条文本，让至少两种角色独立标注并写理由；计算一致率后逐条归类分歧，提交指南 v2、保留的合理分歧和三个会改变产品动作的反例。",
    misconceptions: ["语言标签天然客观", "更多文本自动更有代表性", "高标注一致率等于任务有效", "只要匿名就没有数据权利问题", "所有分歧都应清洗"],
    quiz: {question:"两位专家对一段投诉是否构成威胁持续分歧，首要动作是什么？",options:["删除样本","强制服从多数标签","检查语境与指南并保留理由，判断是否为合理多义或规范冲突"],answer:2,explanation:"先辨认分歧的生成机制；真实歧义不应被伪装成唯一真值。"},
    summary: ["语言样本必须携带语境和生成条件", "分歧既可能是缺陷也可能是信号", "数据说明限制能力主张", "任务输出必须连接真实行动"], mastery:{explain:"语言事件、语料代表性和标注分歧的关系",apply:"一份带理由和版本的标注指南",boundary:"一种不能用单标签学习解决的语言判断"},
    sources:[u("Data Statements","https://aclanthology.org/Q18-1041/"),u("DynaSent","https://aclanthology.org/2021.acl-long.186/"),u("Responsible NLP Checklist","https://aclanthology.org/2021.naacl-main.189/")],
  }),
  chapter({
    prerequisite:"完成 NLPF01—03，并能按语种、书写系统和文本来源切片。",
    goals:["解释字符、字节、词片与形态单位的权衡","量化不同语言的 token 膨胀和截断偏差","在开放词汇、成本与下游质量之间做选择"],
    concepts:c([["NLPF04","切分单位","字符、字节、词或子词决定模型看到的基本序列","何种单位保留结构且可覆盖新词"],["NLPF05","形态与词汇","词形变化、复合词和书写系统形成语言特定边界","是否需要形态分析或领域词保护"],["NLPF06","Tokenizer 公平性","同一语义在不同语言上的长度、成本和截断概率不同","词表与 patch 策略是否系统性伤害某些语言"]]),
    thesis:"Tokenizer 是数据压缩器、计算分配器和语言接口；它不会只影响输入长度，而会改变上下文预算、训练频率、成本与错误形态。",
    problem:"同一份跨境合同，英文 800 tokens、中文 1,100、某低资源语言 2,400。固定 2,048 上下文会让后者更早丢失签名条款，按 token 计费还提高成本。只比较英文下游分数无法发现这类结构性差异。",
    mechanismTitle:"开放词汇编码与动态 byte patch",
    mechanism:"BPE 每轮合并频率最高的相邻符号；Unigram 从候选子词集合中选择最大化语料似然的子集；byte 模型彻底消除 OOV，却显著拉长序列。BLT 不固定 token 表，而按字节熵形成动态 patch：可预测片段用大块，稀有/复杂片段用小块，从而把计算分配给信息密集区域。",
    formula:"BPE 的贪心目标可写为选择 $a,b$ 使频数 $f(ab)$ 最大；Unigram 近似最大化 $\\sum_x\\log\\sum_{s\\in S(x)}\\prod_{t\\in s}p(t)$。跨语言审计至少报告膨胀率 $r_l=\\frac{tokens_l}{characters_l}$、截断率和单位语义成本 $C_l=price\\cdot tokens_l/task$。",
    formulaNotes:["Unicode 归一化和空白规则是否改变实体","训练词表的语言/领域配比","长度比较使用字符、字节还是语义对齐段落","特殊 token、注入和反序列化是否安全"],
    evidence:[
      ev("2018-08-21","SentencePiece","https://aclanthology.org/D18-2012/","能否直接从原始句子学习语言无关的子词模型？","SentencePiece 将空格当普通符号，在固定词表下提供 Unigram/BPE 和可逆切分，避免依赖语言特定预分词。","论文在日英翻译等设置展示与传统子词管线相当或更好的结果，并简化多语言处理。","建立了现代多语言 tokenizer 的可复现基础。","语言无关实现不等于语言公平；训练混合和词表容量仍决定分配。"),
      ev("2024-12-13","Byte Latent Transformer","https://arxiv.org/abs/2412.09871","固定 token 是否是扩展语言模型的必要前提？","BLT 在字节层建模，以熵阈值形成动态 patch，并在局部 byte 编码器与全局 latent Transformer 之间传递表示。","作者报告在相近训练 FLOPs 下可匹配 token 模型，并在噪声和字符任务上表现出优势。","提供按信息复杂度而非固定词表分配计算的路线。","结果来自特定规模与训练配方；推理栈、缓存和真实多语言成本仍需独立测量。"),
    ],
    diagram:"flowchart LR\n  X[Unicode 文本] --> N[规范化]\n  N --> U{编码方案}\n  U -->|BPE/Unigram| T[固定子词]\n  U -->|Byte| B[字节流]\n  B --> P[熵驱动 patch]\n  T --> L[长度/覆盖/成本]\n  P --> L\n  L --> E[跨语言任务评测]",
    caseTitle:"中英少数语种合同 tokenizer 审计", case:"构造语义对齐的 1,000 段合同，分别统计字符、字节、token、截断位置和实体破碎率。固定语义内容与模型，比较子词和 byte/patch 方案在条款检索、金额抽取、吞吐和费用上的 Pareto；额外加入拼写噪声、混语和罕见公司名。",
    protocol:["冻结规范化、词表和模型版本","按语种/文体计算 token 膨胀、实体破碎和截断","在等上下文成本而非等 token 条件评测下游任务","对稀有词、混语、emoji、代码和注入边界做反例集"],
    decisions:["上下文窗口按最差语言预算","缓存同时保存原文、字符偏移与 token 偏移","费用/延迟看每项任务而非每 token 单价","Tokenizer 更新视为数据接口破坏性变更"],
    failures:["只报告平均 token 长度","把中文字符直接当词","训练测试使用不同规范化","忽略 offset 对抽取高亮的影响","认为无 OOV 就没有语言偏差"],
    prompt:"对给定多语言语料做 tokenizer 审计：输出每语种 token/字符、token/字节、P95、截断率、实体跨片率、噪声鲁棒性、任务质量和单位成本；列出最差 20 条并解释机制。",
    exerciseTitle:"比较子词与字节表示",exercise:"选择三种语言和一种领域文体，对同一批语义对齐文本比较至少两个 tokenizer；提交分布图、最差样本、下游抽取结果与一条词表/上下文决策。",
    misconceptions:["Tokenizer 只是工程预处理","词表越大越好","无 OOV 等于跨语言公平","更少 token 必然更强","换 tokenizer 不影响模型接口"],
    quiz:{question:"某语种答案常在长文末尾被漏掉，首先检查什么？",options:["温度","该语种 token 膨胀与实际截断位置","增加英文训练集"],answer:1,explanation:"相同字符/语义长度可能消耗不同上下文，先验证表示与截断机制。"},
    summary:["切分决定序列和计算预算","形态与书写系统改变最优粒度","公平审计需要语义对齐与下游任务","Tokenizer 版本属于模型契约"],mastery:{explain:"BPE、Unigram 与动态 byte patch 的权衡",apply:"一个三语 tokenizer 审计报告",boundary:"固定子词方案会系统性失效的输入"},
    sources:[u("SentencePiece","https://aclanthology.org/D18-2012/"),u("BLT","https://arxiv.org/abs/2412.09871"),u("BPE NMT","https://aclanthology.org/P16-1162/")],
  }),
  chapter({
    prerequisite:"掌握分词与可靠切分，能构造正例、随机负例和语义相近 hard negative。",
    goals:["区分词义、句义、主题和事实关系","解释对比学习怎样塑造向量空间","建立含 hard negative、校准与领域漂移的检索评测"],
    concepts:c([["NLPF07","分布语义","词义由上下文分布提供可学习线索但不等于世界事实","静态或上下文表示适合什么任务"],["NLPF08","句向量与度量","编码器把文本映射到可比较空间","相似函数与训练目标是否匹配检索动作"],["NLPF09","检索边界","相关、蕴含、同主题和可作为证据并不等价","候选召回后需要何种重排与验证"]]),
    thesis:"Embedding 压缩的是训练目标奖励的关系，不是通用‘意义’；高余弦可以表示同主题，也可能把否定、时间和主体差异压平。",
    problem:"查询“2026 年合同是否允许自动续期”与段落“2025 年版本允许自动续期”词面极近，却不能作为当前证据。随机负例会让模型只学主题；必须加入年份冲突、否定、不同主体和近义条款 hard negative。",
    mechanismTitle:"对比表示、各向异性与两阶段检索",
    mechanism:"word2vec 通过局部上下文预测学习静态词向量；BERT 产生依赖上下文的 token 表示；Sentence-BERT 用成对/三元组目标把句子放入可直接比较的空间。生产检索常由双塔 ANN 保召回、cross-encoder 重排关系，再由 claim-evidence 校验检查时间、主体和蕴含。",
    formula:"InfoNCE 损失 $L_i=-\\log\\frac{e^{sim(q_i,d_i^+)/\\tau}}{e^{sim(q_i,d_i^+)/\\tau}+\\sum_je^{sim(q_i,d_j^-)/\\tau}}$。它高度依赖负例分布；召回用 Recall@$k$，排序用 nDCG/MRR，但证据任务还需 entailment、时间有效率与 answerable coverage。",
    formulaNotes:["正例是否真能支持查询而非只相关","batch 内负例有没有假负例","余弦、点积和向量归一化是否与索引一致","领域、时间和语言漂移是否单独切片"],
    evidence:[ev("2019-08-27","Sentence-BERT","https://aclanthology.org/D19-1410/","怎样避免 BERT 对所有句对做昂贵交叉编码？","用孪生/三元组网络产生句向量，使语义搜索可以预编码文档并用余弦比较。","论文报告 STS 与检索效率的大幅改进，形成现代 embedding 检索基本范式。","把句表示从分类器中间态变成可索引产品接口。","独立编码损失跨文本交互，复杂否定和事实关系仍需重排。"),ev("2020-04-29","Dense Passage Retrieval","https://aclanthology.org/2020.emnlp-main.550/","开放域问答能否用稠密向量替代词法检索？","分别编码问题和段落，以 in-batch negatives 训练，并在大规模 ANN 索引召回。","在多个问答数据集上显著超过当时 BM25 基线。","证明监督稠密检索能学习超越词面重叠的匹配。","基准分布、假负例和最新性会影响真实知识库效果；不能省略 lexical/hybrid 基线。" )],
    diagram:"flowchart LR\n Q[查询] --> B[BM25/双塔召回]\n D[版本化文档] --> B\n B --> H[Hard negatives]\n H --> R[Cross-encoder 重排]\n R --> V[主体/时间/蕴含校验]\n V --> K[证据包或拒答]",
    caseTitle:"带版本冲突的政策检索",case:"为 500 个问题标注可支持段落、无答案和版本时效；候选集中加入旧政策、否定条款和相邻地区。比较 BM25、dense、hybrid 与 reranker，除 Recall@20 外报告最终支持率、旧版本误引率、P95 和每查询成本。",
    protocol:["建立随机、词面相近、时间冲突和否定四类负例","固定语料快照、分块和索引参数","分别测召回、重排、证据校验并保存掉落原因","在新文档/新领域时间外集合复测"],
    decisions:["混合检索保留词法精确匹配","索引条目携带版本、权限和有效期","检索与答案指标分层","错误查询进入 hard-negative 队列"],
    failures:["把相似当蕴含","随机负例过易","只测命中文档不测支持句","索引更新不留快照","向量模型升级不重建基准"],
    prompt:"为我的检索任务构造 hard-negative 本体，至少覆盖否定、数字、时间、主体、因果方向和同主题不同答案；设计 BM25/dense/hybrid/reranker 消融和端到端证据支持指标。",
    exerciseTitle:"做一轮可证伪语义检索",exercise:"用 50 个查询和 300 段文档构造带版本冲突的评测集；比较两种召回与一种重排，逐层画漏斗并解释 10 个高相似错误。",
    misconceptions:["余弦高就是事实一致","向量检索必然优于 BM25","更大 embedding 维度总更好","召回率高即可回答","向量库是永久记忆"],
    quiz:{question:"查询与旧版条款余弦最高但结论已废止，系统缺少哪层？",options:["更多维度","时间/版本约束和蕴含校验","更高温度"],answer:1,explanation:"语义相似不能替代证据有效性。"},
    summary:["表示空间由目标与负例塑造","相关性不等于支持关系","两阶段检索分离效率与精确交互","版本和权限必须进入索引契约"],mastery:{explain:"对比学习与 hard negative 怎样改变空间",apply:"分层检索漏斗与错误本体",boundary:"embedding 相似度不应直接驱动的决策"},sources:[u("Sentence-BERT","https://aclanthology.org/D19-1410/"),u("DPR","https://aclanthology.org/2020.emnlp-main.550/"),u("BERT","https://aclanthology.org/N19-1423/")],
  }),
  chapter({
    prerequisite:"能审计 token 与 embedding，并掌握训练/验证/测试隔离。",
    goals:["按信息流选择 encoder、decoder 或 encoder-decoder","解释 CRF、mask 和因果注意力约束","在统一数据/预算下比较轻量基线与现代编码器"],
    concepts:c([["NLPF10","序列结构","标签和输出之间存在顺序、边界与依赖","需要独立预测还是结构化解码"],["NLPF11","编码/解码信息流","双向理解、因果生成和条件生成使用不同 mask","模型架构是否匹配输出约束"],["NLPF12","高效编码器","现代长序列编码器联合改善吞吐、位置与训练配方","何时小型专用模型胜过通用生成模型"]]),
    thesis:"分类、序列标注与生成不是换一个 prompt 就相同；信息能从哪里流向哪里、输出是否需全局一致，决定架构与评价器。",
    problem:"合同实体抽取若用自由生成，可能改写公司名、漏字符或产生不存在实体；token 分类能保留偏移却可能生成非法 IOB 序列。需要对照 BiLSTM-CRF、encoder token classifier 与受约束生成，并在相同标注和延迟下选型。",
    mechanismTitle:"双向编码、因果解码与结构化约束",mechanism:"BiLSTM 汇聚左右上下文，CRF 对整条标签序列归一化并学习转移；BERT 通过 masked LM 获得双向表示；decoder 只能看前缀，适合自回归生成；T5 把任务统一为条件文本生成。ModernBERT 重新设计长上下文 encoder 的位置、注意力和训练配方，说明理解型架构仍有独立价值。",
    formula:"线性链 CRF 的 $p(y|x)=\\frac{e^{s(x,y)}}{\\sum_{y'}e^{s(x,y')}}$，$s$ 包含发射与标签转移；因果注意力令 $M_{ij}=-\\infty$ 当 $j>i$。选择应比较结构合法率、exact/span F1、校准、吞吐与内存，而非只看参数量。",
    formulaNotes:["输出是否依赖未来 token","标签之间有哪些硬约束","生成文本能否无损映射回原文 offset","最大长度与批量吞吐是否符合业务"],
    evidence:[ev("2016-08-09","BiLSTM-CRF for Sequence Tagging","https://aclanthology.org/P16-1101/","端到端神经表示怎样与标签序列约束结合？","双向 LSTM 产生上下文发射分数，CRF 联合解码完整标签序列。","在多项序列标注任务上取得当时强结果，并避免手工特征依赖。","明确区分 token 表示与结构解码两层。","长依赖、预训练和现代硬件效率不是其优势，今天主要作为可解释基线。"),ev("2024-12-18","ModernBERT","https://arxiv.org/abs/2412.13663","encoder-only 模型能否用现代配方在长文本和效率上重新竞争？","工作结合长上下文、旋转位置、局部/全局注意力和现代训练数据/工程。","作者在多种检索、分类和代码任务报告质量—速度优势。","提醒 NLP 选型不应默认所有任务都用 decoder LLM。","技术报告结果与特定硬件实现需在目标环境复验。" )],
    diagram:"flowchart TD\n X[输入序列] --> E{任务信息流}\n E -->|双向理解| EN[Encoder]\n E -->|前缀生成| DE[Decoder]\n E -->|输入到输出| ED[Encoder-Decoder]\n EN --> C[分类/Span/CRF]\n DE --> G[受约束生成]\n ED --> G\n C --> V[结构与偏移校验]\n G --> V",
    caseTitle:"合同实体与关系抽取",case:"同一数据上训练字典+规则、encoder+CRF 和 schema 约束生成。按实体精确边界、嵌套实体、关系方向、非法输出、P95 与人工修订时间评测；法律实体要求保留原文字符偏移和证据句。",
    protocol:["按实体/模板来源分组切分","实现字典、序列标注和生成三层基线","验证 IOB/schema/offset 并记录无法解析输出","对长文、嵌套、否定和跨句关系单独压力测试"],
    decisions:["高频稳定抽取优先专用 encoder","开放 schema 生成必须有语法约束和校验","保存原文 offset 与规范化值双表示","架构升级以端到端修订成本决策"],
    failures:["把生成流畅误当精确抽取","token 与字符 offset 错位","随机拆分文档模板","忽略非法标签序列","只测短句平均 F1"],
    prompt:"为该 NLP 任务画 encoder/decoder/encoder-decoder 选型表；比较信息流、结构约束、可追溯 offset、延迟、数据量和失败恢复，并给最小三基线实验。",
    exerciseTitle:"同任务三架构对照",exercise:"选一个 5 类分类或实体抽取任务，对照线性/规则、encoder 与受约束生成；提交质量—延迟 Pareto 和至少 20 个按机制归因的错误。",
    misconceptions:["decoder LLM 总能替代 encoder","CRF 已完全过时","参数大等于长文本利用好","结构化输出等于 JSON 可解析","token F1 等于实体可用"],quiz:{question:"实体抽取 JSON 合法但公司名被改写，首要指标是什么？",options:["BLEU","原文精确边界/offset 与实体 exact match","困惑度"],answer:1,explanation:"抽取必须忠实指向原文，语法合法不足以证明正确。"},summary:["信息流约束决定架构","结构解码保证全局合法性","专用 encoder 仍有质量成本优势","端到端可用性包含偏移与校验"],mastery:{explain:"三类架构的 mask 与输出差异",apply:"统一预算的三基线实验",boundary:"自由生成不适合的结构化任务"},sources:[u("BiLSTM-CRF","https://aclanthology.org/P16-1101/"),u("BERT","https://aclanthology.org/N19-1423/"),u("T5","https://jmlr.org/papers/v21/20-074.html"),u("ModernBERT","https://arxiv.org/abs/2412.13663")],
  }),
  chapter({
    prerequisite:"完成架构与评测基础，能够固定数据、模型、推理和成本版本。",goals:["说明预训练目标改变的统计行为","用证据阶梯选择 prompt、RAG、PEFT 或全量微调","审计适配数据的泄漏、遗忘和格式过拟合"],
    concepts:c([["NLPF13","预训练目标","自回归、掩码和去噪学习不同条件分布","基础表示是否匹配任务"],["NLPF14","适配阶梯","上下文、检索、参数高效和全量更新的成本/可逆性递增","最小复杂度能否达到门槛"],["NLPF15","偏好与行为塑形","监督/偏好数据改变输出策略而非自动增加事实知识","数据究竟教知识、格式还是取舍"]]),
    thesis:"适配不是默认微调；先识别缺的是上下文、可检索知识、输出格式还是新行为，再用最可逆的方法做对照。",
    problem:"模型不会回答公司最新退款政策，可能是知识截止、检索没召回、指令冲突或 schema 失败。直接用几百条答案微调会记住旧政策且掩盖检索问题。需要 capability ladder 逐级证伪。",
    mechanismTitle:"目标函数、上下文学习与参数更新",mechanism:"自回归 LM 最大化下一个 token 条件似然；masked/denoising 模型恢复被遮蔽内容。Prompt 改变条件上下文但不改权重，RAG 外接可更新证据，LoRA 用低秩增量更新少量参数，全量微调最高成本且可能遗忘。DPO 以偏好对直接调整策略相对参考模型的胜率。",
    formula:"LM 损失 $L=-\\sum_t\\log p_\\theta(x_t|x_{<t})$；LoRA 令 $W'=W+BA$ 且 $rank(BA)=r\\ll d$；DPO 优化 $-\\log\\sigma(\\beta[\\log\\frac{\\pi(y_w|x)}{\\pi_{ref}(y_w|x)}-\\log\\frac{\\pi(y_l|x)}{\\pi_{ref}(y_l|x)}])$。三者改变的对象完全不同。",
    formulaNotes:["评测集是否早于适配数据冻结","新知识能否通过版本化检索解决","偏好对是否反映真实用户取舍","基座、adapter、prompt 和 tokenizer 是否绑定版本"],
    evidence:[ev("2020-05-28","GPT-3","https://arxiv.org/abs/2005.14165","规模能否让模型仅凭上下文示例完成新任务？","自回归模型在不更新权重的 zero/one/few-shot 条件下执行多任务。","论文展示随规模增长的上下文学习能力，同时暴露基准污染、偏差和部分任务弱点。","把 prompt 变成适配接口。","上下文学习不保证稳健推理或最新事实，闭源训练数据也限制污染审计。"),ev("2023-05-29","Direct Preference Optimization","https://arxiv.org/abs/2305.18290","能否不显式训练奖励模型直接利用偏好对？","从 KL 约束奖励最优策略推导分类式目标，直接提高 chosen 相对 rejected 的对数概率。","论文在摘要、对话等任务报告与 PPO 类方法竞争的结果且训练更简单。","形成广泛使用的偏好优化基线。","偏好数据偏差、长度捷径和分布外行为不会因目标简化而消失。" )],
    diagram:"flowchart LR\n G[黄金集+失败本体] --> P[Prompt]\n P -->|未达标| R[RAG]\n R -->|行为/格式仍缺| L[PEFT]\n L -->|充分证据| F[全量/偏好训练]\n F --> E[能力+遗忘+安全回归]\n E --> G",
    caseTitle:"企业政策问答适配阶梯",case:"冻结 300 题，分最新政策、历史冲突、无答案和格式四类。依次比较 prompt、检索、LoRA 与偏好训练；每层只在明确失败上晋级，报告支持率、引用有效性、旧知识误答、通用能力回归、延迟和总拥有成本。",
    protocol:["冻结黄金集与盲测集，去重适配语料","给每个失败标知识/检索/指令/格式/偏好原因","逐级实验并保持评价器和预算一致","检查遗忘、越权、无答案和跨语言回归"],
    decisions:["事实更新优先外部知识层","稳定格式先约束解码再训练","adapter 绑定基座哈希和数据卡","只有持续净收益才进入不可逆训练"],failures:["用微调修复检索缺陷","训练测试近重复","偏好数据只奖励冗长","只测目标任务不测遗忘","把更像人说话当更真实"],prompt:"根据失败样本把需求分成上下文、知识、技能、格式和偏好五类；给出 prompt→RAG→PEFT→全量/偏好训练的晋级门槛、对照、回归集和回滚条件。",exerciseTitle:"完成适配阶梯消融",exercise:"为 40 个领域问题固定盲测集，至少比较 prompt、RAG 与一种参数适配；逐例标失败原因，并说明为什么最终方案没有再升级。",misconceptions:["微调会可靠注入最新知识","Prompt 不需要版本管理","DPO 自动对齐真实价值","LoRA 没有遗忘风险","更多示例永远更好"],quiz:{question:"模型引用不到昨天更新的制度，优先尝试什么？",options:["偏好微调","版本化检索和证据评测","增加温度"],answer:1,explanation:"动态事实更适合可更新、可追溯的知识层。"},summary:["预训练目标决定条件分布","适配从最可逆层开始","偏好塑形不等于事实学习","每次参数更新必须做遗忘与安全回归"],mastery:{explain:"Prompt、RAG、PEFT、DPO 改变的对象",apply:"一份适配晋级实验表",boundary:"不应通过微调解决的知识问题"},sources:[u("GPT-3","https://arxiv.org/abs/2005.14165"),u("LoRA","https://arxiv.org/abs/2106.09685"),u("DPO","https://arxiv.org/abs/2305.18290")],
  }),
  chapter({
    prerequisite:"能选择编码/生成架构并写 JSON Schema 或标注本体。",goals:["把实体、关系、事件与标签写成约束 schema","区分 token、span、record 和任务级指标","设计解析、校验、修复和人工升级链"],
    concepts:c([["NLPF16","结构化理解","从文本定位实体、关系、事件和属性","输出本体能否支持下游系统"],["NLPF17","约束生成","用语法、类型和业务规则限制可接受输出","哪些错误应在解码时阻止"],["NLPF18","错误本体","按边界、类型、关系、证据和解析失败归因","迭代数据、模型还是规则"]]),
    thesis:"‘输出 JSON’只是句法层；可生产的结构化 NLP 还要保证原文证据、类型约束、实体同一性、关系方向和业务完整性。",
    problem:"发票抽取返回合法 JSON，却把含税总额当未税金额、把供应商与购买方对调。字段级准确看似高，财务入账却错误。需要 schema + cross-field invariant + 原文 span + 任务级 exact record。",
    mechanismTitle:"Span、语法约束与语义验证",mechanism:"序列标注定位连续 span，span classifier 支持嵌套，生成模型适合开放 schema。JSON grammar 可在 token 选择时屏蔽非法前缀；Pydantic/JSON Schema 验类型；业务 invariant 检查金额关系和枚举；证据对齐器把每个值绑定原文偏移。修复只处理可机械确定的格式，不让模型静默猜事实。",
    formula:"实体边界 F1 基于 exact span；record exact match 要求一整条记录全部正确。若字段正确率均为 $p$, $k$ 个必要字段的独立近似成功仅 $p^k$。业务损失为 $\\sum_e C_{type(e)}N_e$，高成本角色互换应单独门禁。",
    formulaNotes:["是否允许嵌套、重叠和不连续 span","规范化值与原文值如何双向追溯","schema 合法是否仍可能语义冲突","部分正确能否安全进入下游"],
    evidence:[ev("2003-01-01","CoNLL-2003 Shared Task","https://aclanthology.org/W03-0419/","如何形成可比较的命名实体识别任务？","共享任务固定语料、PER/ORG/LOC/MISC 类型和 exact-span F1。","它成为长期 NER 基准与序列标注教学入口。","建立精确边界与实体类型的共同语言。","新闻英语/德语和窄类型无法代表嵌套、领域实体与真实系统成本。"),ev("2020-01-01","Universal Dependencies v2","https://aclanthology.org/L18-1289/","多语言句法结构能否使用统一标注框架？","UD 统一词性、形态特征与依存关系，同时允许语言特定扩展。","项目持续覆盖大量语言并维护指南、树库与验证工具。","展示 schema、社区治理和自动验证怎样共同支持跨语言资源。","统一标签仍会压平语言特性，树库质量和覆盖差异必须保留。" )],
    diagram:"flowchart LR\n T[原文+版面] --> X[Span/生成候选]\n X --> G[语法/schema]\n G --> I[跨字段 invariant]\n I --> E[原文证据对齐]\n E --> C{置信与风险}\n C -->|通过| API[结构化接口]\n C -->|不足| H[人工修订]",
    caseTitle:"发票到财务记录",case:"定义供应商、购买方、币种、未税额、税额、总额和日期；每字段保存原文 span、规范化值与置信。验证总额≈未税额+税额、币种一致和主体不互换。评测 exact field、record exact、金额绝对误差、自动通过率与错误入账率。",
    protocol:["用真实下游 API 反推 schema 与必填约束","构造版面、OCR、嵌套和角色互换难例","比较规则/encoder 与受约束生成","逐层记录解析、类型、语义、证据和业务错误"],decisions:["高风险字段不允许无证据自动填充","schema 与 prompt/model 独立版本化","业务 invariant 进入发布门禁","人工修订成为标注回流而非覆盖日志"],failures:["JSON 合法即认为正确","只算字段 micro-F1","规范化后丢失原文位置","自动修复偷偷改事实","训练集缺少完整记录级难例"],prompt:"为该抽取需求输出 JSON Schema、字段证据 offset、跨字段 invariant、错误本体、风险成本和 exact-record 验收；禁止用默认值掩盖缺失。",exerciseTitle:"实现四层校验器",exercise:"选一种票据/合同，写 schema、语法校验、两个业务 invariant 和证据对齐；用 20 条难例报告每层拦截量与仍遗漏的高风险错误。",misconceptions:["可解析等于可用","字段 F1 高则整单可靠","生成模型不需要 offset","修复器越强越好","schema 一经定义不会演化"],quiz:{question:"JSON 完全合法但总额关系不成立，应归为哪层失败？",options:["Tokenizer","语义/业务 invariant","网络"],answer:1,explanation:"句法与类型通过不代表字段组合符合业务事实。"},summary:["结构化输出含语法、类型、语义与证据四层","record 指标比字段平均更接近任务","高风险缺失应拒绝或人工升级","错误本体驱动数据与架构选择"],mastery:{explain:"span、schema 与 invariant 的层次",apply:"一个带证据的四层校验器",boundary:"无法安全自动修复的结构错误"},sources:[u("CoNLL-2003","https://aclanthology.org/W03-0419/"),u("Universal Dependencies","https://aclanthology.org/L18-1289/")],
  }),
  chapter({
    prerequisite:"掌握条件生成、证据对齐和结构校验。",goals:["区分流畅、忠实、覆盖、风格和任务成功","为摘要/翻译/对话选择可解释多指标","评测文档级一致性和真实交互闭环"],
    concepts:c([["NLPF19","条件生成","根据来源、历史或目标语言产生序列","生成内容受哪些证据和约束"],["NLPF20","交互状态","对话目标、轮次状态、修复与接管共同决定成功","单轮好答案能否完成任务"],["NLPF21","文档级一致性","术语、实体、指代、时间和篇章跨句保持一致","句级高分是否掩盖全篇冲突"]]),
    thesis:"流畅度最容易被模型和评价器共同优化，却不是摘要忠实、翻译一致或对话成功的充分条件；生成评测必须回到来源与任务状态。",
    problem:"客服摘要读起来完美，却把“用户询问退款”写成“已退款”；机器翻译每句准确但同一零件名三种译法；对话每轮有礼貌却没有完成改签。三者都要求 source-grounded 与 document/task-level 评价。",
    mechanismTitle:"自回归生成、暴露偏差与多层评价",mechanism:"Teacher forcing 训练时以真实前缀预测下一个 token，推理时依赖自身输出，错误会累积。Beam、sampling 和温度改变候选分布；复制/检索能加强来源约束但不保证蕴含。评价应组合表面重叠、语义质量、claim-level 忠实、文档一致与用户任务完成。",
    formula:"生成概率 $p(y|x)=\\prod_tp(y_t|y_{<t},x)$；ROUGE 主要测 n-gram 覆盖，COMET 学习翻译质量估计。对摘要把输出拆成 claims，忠实率 $F=|claims\\ supported|/|claims|$，覆盖率 $C=|source\\ facts\\ covered|/|required\\ facts|$；二者不可互换。",
    formulaNotes:["参考答案是否唯一且完整","评价器是否偏爱长度/模板/同族模型","文档术语表和对话状态是否显式输入","人工评分是否双盲并测一致"],
    evidence:[ev("2004-07-01","ROUGE","https://aclanthology.org/W04-1013/","摘要系统能否通过与人工参考的重叠自动比较？","ROUGE-N/L 等指标计算 n-gram 或最长公共子序列召回。","它支持大规模快速对比并长期成为摘要基准。","提供稳定低成本信号。","重叠不能判定事实支持、遗漏或新颖表达，不能单独作为发布标准。"),ev("2026-03-30","TransGraph","https://aclanthology.org/2026.eacl-long.75/","文档翻译怎样测量跨句实体和术语一致性？","工作把文档中的翻译关系构造成图，围绕跨句实体/术语连接评估全局一致。","EACL 2026 结果显示句级指标会遗漏重要文档级错误。","把翻译评价从句子平均扩展到篇章结构。","新基准覆盖和语言范围有限，图构造本身也可能带误差。" )],
    diagram:"flowchart LR\n S[来源/对话状态] --> G[条件生成]\n G --> P[解析 claims/实体/术语]\n P --> F[来源支持]\n P --> C[覆盖与一致]\n P --> T[任务状态变化]\n F --> J[多指标+人评]\n C --> J\n T --> J",
    caseTitle:"多轮客服摘要与跨语翻译",case:"选 100 段含取消、否定和未决事项的会话，要求中文摘要及英文交接。把输出拆 claim，与原轮次绑定；跟踪金额、状态和产品术语跨语言一致。报告 unsupported claim、遗漏关键行动、术语漂移、人工修订时间和交接成功。",
    protocol:["冻结来源、参考与必要事实清单","比较规则模板、基础生成和证据约束生成","逐 claim 检查支持并追踪文档实体图","让盲评者按 rubric 评分并计算一致"],decisions:["高风险摘要默认附原文证据","翻译维护版本化术语库","对话指标以任务完成/修复而非满意措辞为主","自动指标只作筛查并定期校准"],failures:["用 ROUGE 代表忠实","逐句翻译忽略篇章","Judge 看不到来源却评事实","长答案因覆盖高被奖励","只测成功对话不测修复"],prompt:"把生成输出拆成原子 claims、必要事实、实体/术语和任务状态；逐项给来源证据、忠实/覆盖/一致性判定及不确定，禁止只给总体好坏。",exerciseTitle:"构造一个生成评测矩阵",exercise:"为摘要、翻译或对话任务准备 20 个含否定和状态变化的样本；比较至少三种输出，提交 claim 账本、文档一致图和自动指标误判案例。",misconceptions:["更流畅就更好","参考答案是唯一真值","句级 BLEU/COMET 足够","对话满意度等于任务成功","Judge 可替代来源核验"],quiz:{question:"摘要把‘尚未退款’写成‘已退款’，ROUGE 仍很高，缺少什么？",options:["更大 beam","claim-level 来源支持与状态极性检查","更多同义词"],answer:1,explanation:"词面覆盖无法识别关键事实状态被反转。"},summary:["生成质量是多目标","claim 支持与覆盖需分开","篇章状态不能由句级平均替代","交互必须测真实任务闭环"],mastery:{explain:"流畅、忠实、覆盖与任务成功的冲突",apply:"一份 claim-level 生成评测",boundary:"自动重叠指标会给高分的严重错误"},sources:[u("ROUGE","https://aclanthology.org/W04-1013/"),u("COMET","https://aclanthology.org/2020.emnlp-main.213/"),u("TransGraph 2026","https://aclanthology.org/2026.eacl-long.75/")],
  }),
  chapter({
    prerequisite:"能按语言/社群切片并审计 tokenizer 和评价器。",goals:["区分翻译迁移、跨语言对齐和本地文化有效性","评测低资源、混语、方言与地域知识","建立社区参与、数据权利与失败升级机制"],
    concepts:c([["NLPF22","跨语言迁移","共享表示把高资源监督迁移到其他语言","迁移增益是否伴随负迁移"],["NLPF23","低资源覆盖","数据、token 和评测稀缺共同限制能力声明","怎样用最小本地证据建立基线"],["NLPF24","文化语境","事实常识、礼貌、规范和任务需求随社区变化","本地化是否只是翻译 UI"]]),
    thesis:"语言支持不是能生成几句话，而是目标社区在自己的文本、任务、文化事实和风险下获得可验证服务，并有权指出和修正错误。",
    problem:"一个模型在翻译基准表现不错，却把地方机构、亲属称谓和敏感礼貌关系解释错；英文翻译后答对也不说明能直接处理原语言中的混语、方言和本地事实。",
    mechanismTitle:"共享参数、语言干扰与本地效度",mechanism:"多语言模型通过共享子词和参数产生迁移，但数据量和梯度竞争导致高资源主导。Translate-test 引入翻译误差并抹去文化信号；直接评测要使用母语编写、当地验证的样本。MuBench 分离语言理解任务，LocQA 聚焦当地知识，二者共同限制‘支持 100 种语言’式声明。",
    formula:"对语言 $l$ 的迁移增益 $TG_l=M_l^{multi}-M_l^{mono/base}$，最坏语言 $M_{min}=\\min_lM_l$ 比宏平均更能暴露服务缺口。采样常用 $p_l\\propto n_l^\\alpha$，$\\alpha<1$ 提升低资源占比，但可能造成重复过拟合。",
    formulaNotes:["样本是原生创作还是翻译","标注者与目标社群关系","平均分是否按语种/任务/地区展开","本地知识的时间有效性和争议性"],
    evidence:[ev("2026-05-19","MuBench","https://aclanthology.org/2026.findings-acl.794/","大模型的多语言理解能否在足够广语言和任务上比较？","基准覆盖 61 种语言、多个理解任务和约 390 万样本，按语言与能力维度测量。","作者发现模型之间和语言之间仍存在显著差距，规模不能消除低资源不均衡。","提供 2026 年大规模多语言诊断底座。","自动/现有数据聚合可能继承质量差异，分数不代表文化与真实服务完整性。"),ev("2026-05-17","LocQA","https://aclanthology.org/2026.acl-long.1344/","多语言模型是否真正知道语言社区的地方性事实？","数据由本地语境问题组成，区分可翻译的一般知识与地点/文化相关知识。","结果显示语言流利与当地知识能力明显脱钩。","把本地效度纳入多语言能力声明。","问答只能覆盖部分文化经验；知识变化和社区内部差异需持续维护。" )],
    diagram:"flowchart TD\n H[高资源数据] --> M[共享模型]\n L[低资源/混语/方言] --> M\n M --> S[按语言任务切片]\n S --> T[翻译对照]\n S --> N[原生本地评测]\n N --> C[社区复核]\n C --> D[数据/产品修订]",
    caseTitle:"面向东南亚多语客服",case:"选择中文、英语和两种当地语言，样本由当地客服原生编写，并保留混语。比较直接回答与 translate-test；测意图、实体、当地政策事实、礼貌风险和转人工。发布门槛使用每种语言最低分与严重错误率，不允许平均值补偿。",
    protocol:["与目标社群共同定义任务和禁用场景","构造原生、翻译、混语和方言四类集合","对照直接、翻译和少量本地适配","母语评审严重错误并记录社区分歧"],decisions:["语言能力按任务和地区声明","低资源不足时优先安全缩小范围","UI 翻译与模型本地化分开验收","社区反馈有报酬、授权和撤回机制"],failures:["把机器翻译集当本地数据","用宏平均掩盖最差语言","把国家当单一文化","Tokenizer 覆盖当语义能力","高资源适配造成负迁移不复测"],prompt:"为目标语言设计本地效度评测：区分原生/翻译、一般/地方知识、标准语/混语/方言，列母语评审流程、每语言门槛、严重错误和能力声明边界。",exerciseTitle:"做一个四象限跨语言试验",exercise:"选两种语言各 20 条，交叉一般/本地知识与原生/翻译来源；比较直接回答和翻译链，找出至少五个翻译分高而本地效度失败的样本。",misconceptions:["会翻译等于服务该语言","共享模型必然正迁移","国家等于语言社区","低资源只能等更多数据","平均多语言分能代表公平"],quiz:{question:"模型翻译准确却持续答错当地办事流程，说明什么？",options:["仅需增大词表","语言形式能力与地方知识/文化效度脱钩","温度过低"],answer:1,explanation:"本地服务需要原生任务和社区证据。"},summary:["跨语言迁移可能正也可能负","原生本地评测不可被翻译替代","最坏语言与严重错误优先于平均分","社区参与属于系统机制"],mastery:{explain:"语言覆盖与本地效度的差异",apply:"原生/翻译四象限实验",boundary:"不能声称支持某语言的条件"},sources:[u("MuBench 2026","https://aclanthology.org/2026.findings-acl.794/"),u("LocQA 2026","https://aclanthology.org/2026.acl-long.1344/"),u("FLORES-101","https://aclanthology.org/2022.tacl-1.30/")],
  }),
  chapter({
    prerequisite:"掌握检索漏斗、生成忠实和多语言切片。",goals:["区分上下文容量、检索命中与信息利用","构造位置×长度×语言×干扰因子实验","用证据覆盖和消融决定长上下文或 RAG"],
    concepts:c([["NLPF25","上下文容量","接口可接收的 token 数不等于可可靠利用的信息量","有效长度如何测"],["NLPF26","检索增强","外部检索把相关证据压缩进模型条件","召回与利用哪个是瓶颈"],["NLPF27","长文诊断","位置、密度、顺序、语言和干扰共同影响利用","怎样定位失败层"]]),
    thesis:"长上下文是资源上限，不是能力保证；只有控制证据位置、长度、语言、密度和干扰，才能分辨找不到、没读懂与生成没遵循。",
    problem:"模型能接收 1M tokens，但审查 400 页双语招标书时漏掉中段否决条款。盲目扩大窗口会增加费用和噪声；RAG 也可能因切块丢跨页条件。需要全文、检索、结构化目录和 oracle-evidence 四组。",
    mechanismTitle:"注意力竞争、检索瓶颈与有效上下文",mechanism:"位置编码允许外推不代表训练分布覆盖；大量干扰文档会争夺注意力。RAG 将问题映射到候选块，瓶颈可分为 corpus、chunk、retrieval、rerank、context assembly 与 answer utilization。Oracle evidence 能把检索误差从利用误差中分离。",
    formula:"端到端正确率可分解近似 $P(correct)=P(recall)P(use\\ correct|recalled)P(generate\\ faithful|used)$。MLRBench 的思路是测有效利用而非声明窗口；实验矩阵令 $Y=f(position,length,language,density,distractor,model)$ 并报告交互效应。",
    formulaNotes:["证据是否完整落在一个 chunk","关键条件是单点还是跨段组合","输入长度用各语言真实 token 计量","Judge 是否也会随长度失效"],
    evidence:[ev("2023-07-06","Lost in the Middle","https://aclanthology.org/2024.tacl-1.9/","相关信息在长上下文中的位置会影响使用吗？","控制相关文档在开头、中间和末尾的位置，测试多文档问答与键值检索。","模型常在开头/末尾更好，中间显著下降，展示非均匀位置利用。","建立长上下文位置压力测试范式。","模型代际已变化，具体曲线必须在当前模型和真实任务复测。"),ev("2026-03-31","MLRBench","https://aclanthology.org/2026.eacl-long.290/","现代模型在多语言长上下文中实际利用多少？","覆盖 7 种语言，通过可控长度、位置和任务测有效阅读而非 API 容量。","研究报告多种模型的有效能力常低于标称上下文的 30%，并存在语言差异。","提供截至 2026 的多语言长上下文反证。","基准任务与模型列表有限；30% 是实验结果而非所有系统常数。" )],
    diagram:"flowchart LR\n Q[问题] --> R[检索/目录]\n C[版本化长文] --> R\n R --> A[上下文组装]\n A --> M[模型利用]\n M --> O[带引用答案]\n O --> V[claim 支持]\n V --> D{失败归因}\n D --> R\n D --> A\n D --> M",
    caseTitle:"双语招标书否决条款审查",case:"将关键条款系统移动到 10/50/90% 位置，长度从 8K 到目标上限，加入相似旧版干扰。比较全文、RAG、层级摘要和 oracle evidence；按中英分别报告召回、利用、引用支持、P95 和单位文档成本。",
    protocol:["构造位置×长度×语言×干扰全因子子集","建立 no-context 与 oracle-evidence 上下界","逐层记录召回、重排、组装、利用和生成","对跨块条件、表格和旧版本做专项难例"],decisions:["长文默认分层导航加检索","标称窗口不进入能力宣传","上下文组装保留章节/页码/版本","按失败层决定改 chunk、检索还是模型"],failures:["只做 needle 单点检索","答案对但引用错仍算成功","把 oracle 结果当真实 RAG","忽略语言 token 差异","Judge 与被测模型同样读不完"],prompt:"设计长上下文压力测试：位置 10/50/90%、至少三档长度、两种语言、相关/旧版干扰、跨块组合；加入 no-context、RAG、全文、oracle，并分解召回—利用—忠实。",exerciseTitle:"测出真实有效上下文",exercise:"用一份长文构造 24 个控制样本，移动相同证据并加入干扰；画准确率/支持率随位置与长度变化，给出选全文还是 RAG 的决策。",misconceptions:["窗口大小等于阅读能力","RAG 只要召回率高即可","needle 测试代表复杂推理","更多上下文不会伤害","引用存在就算有依据"],quiz:{question:"Oracle evidence 正确率高、真实 RAG 低，优先修哪层？",options:["生成温度","检索/分块/重排链","扩大模型参数"],answer:1,explanation:"oracle 已证明模型在给定证据时能用，主要瓶颈在证据到达前。"},summary:["容量与有效利用分离","位置和语言必须压力测试","oracle 分离检索与利用瓶颈","端到端答案需 claim 证据支持"],mastery:{explain:"长上下文三段概率分解",apply:"一个全因子压力测试",boundary:"标称窗口不能支持的能力声明"},sources:[u("Lost in the Middle","https://aclanthology.org/2024.tacl-1.9/"),u("MLRBench 2026","https://aclanthology.org/2026.eacl-long.290/"),u("RAG","https://arxiv.org/abs/2005.11401")],
  }),
  chapter({
    prerequisite:"完成 claim 级生成评测、长上下文诊断和数据切片。",goals:["把事实性拆成可核验 claim 与来源","校准自动指标、LLM Judge 和人评偏差","建立线上回归、事故分级和能力声明"],
    concepts:c([["NLPF28","事实性","输出 claim 是否被给定或权威来源支持","回答、引用和时间有效性怎样共同判定"],["NLPF29","评价器校准","自动指标/Judge 是带偏差的测量模型","何时需要盲人评与多评价器"],["NLPF30","生产治理","版本、回归、反馈和事故把评测变成持续控制","什么变化触发阻断或回滚"]]),
    thesis:"评价器不是裁判真理而是另一个模型；事实性需要 claim—evidence 对齐，发布需要把评价器误差与产品风险一起测量。",
    problem:"LLM Judge 偏爱更长、更自信、同家族措辞，可能给有引用但引用不支持的回答高分。若团队不断对 Judge 调 prompt，线上看似进步，实际只是适应评价器。必须有独立 gold、对抗样本和人工仲裁。",
    mechanismTitle:"Claim 分解、证据验证与测量误差",mechanism:"先将回答原子化为可核验 claims，再检索/读取权威来源，判断 entail/contradict/insufficient 和时间有效性。Judge 只承担 rubric 可观察项；与盲人评计算混淆矩阵和校准。线上反馈分无害格式、可恢复任务失败、高风险错误和安全事故，分别进入修复与门禁。",
    formula:"事实精确率 $FP=|supported|/|verifiable\\ claims|$，覆盖率衡量必要事实；Judge 的敏感度/特异度与 Cohen $\\kappa$ 必须按切片报告。若严重错误成本 $C_s$ 远高于普通错误，应最小化 $R=\\sum_kC_kP(e_k)$ 而不是单一平均得分。",
    formulaNotes:["来源权威性、发布日期与适用范围","claim 分解器遗漏是否独立抽查","Judge 是否盲于模型身份和答案顺序","回归集是否冻结且有污染审计"],
    evidence:[ev("2025-05-15","FactBench","https://aclanthology.org/2025.acl-long.1587/","事实性评价器在多种错误和任务上是否可靠？","基准汇集可控事实错误与多领域样本，对评价方法做细粒度比较。","研究显示评价器表现随错误类型显著变化，单一总分掩盖弱点。","提供系统校准事实评价器的基准。","合成/收集错误仍不能覆盖开放世界全部事实，gold 也需审计。"),ev("2025-07-28","Verify with Caution","https://aclanthology.org/2025.findings-acl.1175/","使用 LLM 验证生成事实会引入哪些系统性偏差？","工作分解验证流程并比较提示、模型与证据条件，分析置信与判断错误。","结果表明 verifier 可能被表面线索和自身知识误导，需谨慎使用。","反驳‘再用一个 LLM 检查即可’的简化方案。","模型快速迭代，具体数值会变化；测量框架比排行榜更稳定。"),ev("2025-11-05","FaStFact","https://aclanthology.org/2025.findings-emnlp.1295/","能否兼顾事实评价速度与精细度？","方法围绕 claim 和证据组织更高效的事实检查管线。","论文报告在多个设置下的质量—成本改进。","为大规模回归提供可部署评价方向。","自动化吞吐提升不消除来源质量、长尾 claim 与仲裁需求。" )],
    diagram:"flowchart LR\n O[输出] --> C[原子 claims]\n C --> E[权威证据+时间]\n E --> V[支持/矛盾/不足]\n V --> J[Judge rubric]\n J --> H[盲人评校准]\n H --> R[风险加权门禁]\n R -->|失败| I[事故/回归样本]\n I --> C",
    caseTitle:"带引用的医疗信息问答门禁",case:"禁止诊断，只回答批准的信息范围。每条输出拆 claim，证据限定版本化指南；评价支持、遗漏禁忌、过时来源、无答案拒绝和升级。自动评价每周与双人盲评抽样校准，高风险假阴性直接阻断发布。",
    protocol:["冻结 200 条 gold 与 50 条对抗评价器样本","双人标 claim—evidence 并仲裁","比较规则、NLI 与两种 Judge 的混淆矩阵","设风险加权门禁，演练模型/检索回滚"],decisions:["评价器版本与模型版本同等治理","严重错误采用零/低容忍独立门禁","线上反馈先去隐私再进入错误本体","能力声明写明语种、领域、时效和拒答边界"],failures:["Judge 分数当真值","来源存在但不支持 claim","用模型置信当事实概率","不断调评价 prompt 污染回归集","事故只修个例不补机制测试"],prompt:"将回答拆成原子可核验 claims；对每项给来源、日期、支持/矛盾/不足、引用是否真的覆盖，并标风险。然后设计 Judge 与盲人评校准，不允许用另一个模型的自信替代证据。",exerciseTitle:"校准一个评价器",exercise:"准备 30 个输出，其中刻意加入否定、旧版本、主体错配和引用不支持；让自动 Judge 与两位盲评者判断，计算混淆矩阵并写发布门禁。",misconceptions:["引用等于事实","更强 Judge 就无偏","事实性是一个总分","模型自检能独立验证","离线通过后无需持续回归"],quiz:{question:"Judge 对冗长答案普遍给高分，应如何处理？",options:["要求模型更长","用长度配对反例和盲人评校准，修订 rubric/评价器","只换随机种子"],answer:1,explanation:"先测量并纠正评价器偏差，避免优化错误代理。"},summary:["事实评价以 claim—evidence 为单位","Judge 必须像测量仪器一样校准","风险成本决定门禁","事故样本回流为机制回归"],mastery:{explain:"事实支持与评价器正确性的区别",apply:"一个含混淆矩阵的评价器报告",boundary:"自动 Judge 不得单独批准的发布"},sources:[u("FactBench","https://aclanthology.org/2025.acl-long.1587/"),u("Verify with Caution","https://aclanthology.org/2025.findings-acl.1175/"),u("FaStFact","https://aclanthology.org/2025.findings-emnlp.1295/")],
  }),
];

export default {
  active:[{name:"语言任务本体",action:"把一个需求写成语言事件、语境、输出和动作",evidence:"一页任务卡+10 个反例"},{name:"语料与采样",action:"建立来源、时间、人群和许可台账",evidence:"语料 data statement"},{name:"标注分歧",action:"做双人试标并归因分歧",evidence:"指南 v2+分歧本体"}],
  frontierSignals:["NLP 前沿已从英语平均榜转向多语言、地方知识与真实有效上下文","标称百万 token 不能代替位置×长度×语言利用测试","Byte/动态 patch 重新打开固定 tokenizer 之外的设计空间","事实性评价从答案总分转向 claim—evidence 与评价器校准","高效 encoder 与专用结构模型仍在大量生产任务保持独立价值"],
  projectCriteria:["中英与至少一个低资源/混语切片","版本化语料、授权、标注指南和分歧记录","规则/专用模型/生成或检索三层基线","claim 证据、无法回答和人工接管","质量—成本—延迟—风险与线上回归"],
  branchRules:["先完成 NLPF01—03；任务定义不稳时不得跳到模型","检索任务从 NLPF07—09 跳到 NLPF25—30","抽取任务优先 NLPF10—18，再补事实治理","跨语言产品必须完成 NLPF22—24 和对应 tokenizer 审计"],
  sourceRules:["近三年前沿优先 ACL Anthology、论文/模型卡和官方数据页","经典机制保留原论文但用当前模型重测","模型自报数字标明数据、语言、预算与污染限制","文化/多语言能力必须有目标社群或母语评审证据"],
  ledger:[
    {date:"2024-12-13",label:"Byte Latent Transformer",url:"https://arxiv.org/abs/2412.09871",supports:"动态 byte patch 与 token-free 路线",limit:"特定规模与工程栈"},
    {date:"2024-12-18",label:"ModernBERT",url:"https://arxiv.org/abs/2412.13663",supports:"现代 encoder 质量—效率",limit:"技术报告与自报基准"},
    {date:"2026-03-31",label:"MLRBench",url:"https://aclanthology.org/2026.eacl-long.290/",supports:"七语种有效长上下文低于标称能力",limit:"任务与模型覆盖有限"},
    {date:"2026-05-17",label:"LocQA",url:"https://aclanthology.org/2026.acl-long.1344/",supports:"语言流利与地方知识脱钩",limit:"地方知识持续变化"},
    {date:"2026-05-19",label:"MuBench",url:"https://aclanthology.org/2026.findings-acl.794/",supports:"61 语言、约 390 万样本的理解诊断",limit:"数据质量随语言不均"},
  ],
  conflicts:[{title:"长窗口 vs 有效阅读",body:"API 容量只给资源上限；Lost in the Middle 与 MLRBench 支持位置/语言条件下的显著利用缺口。"},{title:"统一多语言模型 vs 本地服务",body:"共享表示带来迁移，但 MuBench/LocQA 显示语言覆盖不能替代地方知识和社区验证。"}],
  updateTriggers:["ACL/EMNLP/EACL 新基准改变多语言或长上下文结论","主流 tokenizer/byte 架构在等计算下形成新 Pareto","事实评价器在独立人评上显著改变严重错误召回","数据许可、语言社区或产品适用范围变化"],
  overviewSources:[u("MLRBench 2026","https://aclanthology.org/2026.eacl-long.290/"),u("MuBench 2026","https://aclanthology.org/2026.findings-acl.794/"),u("LocQA 2026","https://aclanthology.org/2026.acl-long.1344/")],
  details,
};
