import { defineField, lesson as L } from "./types.ts";
const A="阶段一 · 问题与真实工作",B="阶段二 · 能力边界与评测",C="阶段三 · 原型与可信体验",D="阶段四 · 经济、治理与运营",E="阶段五 · 组织复利";
const S={opp:["Inspired","Jobs to Be Done","AI Index"],work:["Contextual Inquiry","People + AI Guidebook","Human-AI Collaboration"],arch:["Building Effective Agents","MCP","Model Cards"],eval:["NIST TEVV","OpenAI Evals","Human Evaluation"],exp:["Wizard of Oz","Trustworthy Online Experiments","Sequential Testing"],ux:["People + AI Guidebook","Human-AI Interaction Guidelines","Trust Calibration"],econ:["Lean Analytics","AI Index","Queueing Theory"],gov:["NIST AI RMF","ISO/IEC 42001","EU AI Act"],ops:["ML Test Score","Incident Response","SRE"],strat:["Competing in the Age of AI","AI Index","Organizational Learning"]};
const I=[
  "AI 机会必须从用户结果和现有替代开始，模型能力只能解释方案，不应反过来制造需求。",
  "任务价值由频率、单次收益、失败代价和可规模化程度共同决定，不能只看使用次数。",
  "适合 AI 的任务允许概率输出、可获得反馈且能容纳验证；确定规则或不可承受错误应优先别解。",
  "机会论证要把价值、可行、经济和安全假设写成可反证条件，停止也是有效学习。",
  "情境研究观察真实行为、工具切换与例外，用户口述只能作为待验证线索。",
  "服务蓝图把前台体验、后台劳动、系统和责任连接起来，防止局部自动化转移成本。",
  "同一功能对不同能力用户的收益和风险不同，自主度应随任务风险与可验证能力变化。",
  "AI 不是旧界面的插件；流程应围绕新的分工、验证和恢复重新设计。",
  "能力矩阵必须按任务切片、输入条件和版本记录成功、拒绝与失败，而不是列宣传能力。",
  "每增加 RAG、工作流或 Agent 都在购买新故障模式，只有增量证据足以覆盖成本才升级。",
  "模型负责概率推断，工具负责确定执行，状态负责恢复，政策负责不可绕过的边界。",
  "Build/Buy 需要比较能力、总成本、数据权、可观测和退出路径，价格只是其中一项。",
  "评测合同先定义任务单位、评分者、Rubric 和边界，避免‘回答好’随版本任意解释。",
  "黄金集应覆盖主流、长尾、高风险、对抗和时间外样本，并保持与开发决策隔离。",
  "失败本体把低分归因到数据、检索、模型、工具、交互或政策层，才能驱动正确修复。",
  "数据飞轮不是收集所有反馈，而是经采样、授权、复核、去重和版本控制生成回归资产。",
  "假设树按不确定性与后果排序，先验证最可能让项目失败的前提。",
  "Wizard-of-Oz 用人工模拟未实现能力，既验证用户选择，也暴露隐藏运营劳动。",
  "离线、影子、Sandbox 与真实执行逐级增加外部影响，升级必须有明确门禁和回退。",
  "在线实验需要预注册主指标、护栏、样本与停止规则，频繁偷看会制造虚假确定性。",
  "首次体验建立心智模型；夸张演示和模糊文案会在后续制造过度依赖。",
  "不确定性展示必须连接可采取动作：补资料、看证据、并列方案、拒绝或转人工。",
  "真正控制要求关键变量可检查、动作可撤销、请求幂等且失败能恢复，弹窗本身不够。",
  "信任应与正确性匹配；短期速度提升若伴随判断和维护能力下降，需要产品护栏。",
  "指标树把客户结果、任务行为和系统信号连成假设链，底层代理不能取代最终价值。",
  "质量、延迟、成本和风险构成 Pareto 前沿，路由策略应按任务难度和后果选择位置。",
  "单位经济的分母是通过质量门槛的成功任务，分子必须包含人工、重试、失败和平台。",
  "容量设计要看高峰到达、尾延迟和降级后果，定价应绑定客户价值而非 Token。",
  "风险从使用情景和受影响主体开始，平均模型错误率不能表达具体伤害。",
  "数据最小化需要沿模型、检索、日志、工具和供应商画流向，分别定义权限与保留。",
  "高风险动作必须经过独立授权、策略执行和审计，不能依赖模型自我约束。",
  "治理是持续的用途、责任和证据管理，模型、数据、地区或人群变化都会触发重评。",
  "AI 行为由模型、提示、知识、工具和政策共同决定，发布包必须能重放整套组合。",
  "影子和灰度把学习限制在可观察、可回滚的影响半径内，权限也应逐级扩大。",
  "反馈运营要把自然语言抱怨转成任务、失败层和严重度，点赞点踩不足以归因。",
  "AI 事故既包含软件故障，也包含错误建议、越权和人工接管失败，复盘要覆盖社会技术链。",
  "可持续护城河来自嵌入真实工作流的专有约束、分发、信任与学习速度，而非单一模型。",
  "数据只有在权利清晰、标签稀缺、评测有效且能缩短迭代时才形成资产。",
  "AI 产品团队需要共同评审任务、证据、风险与发布，职能边界不能成为责任缝隙。",
  "组合管理用阶段证据分配资源，明确停止、继续和规模化门槛才能避免 Demo 长尾。",
];
export default defineField({slug:"ai-product",title:"AI 产品经理",shortTitle:"AI 产品",prefix:"AIPM",color:"#b13c5a",promise:"把模型演示转化为问题选择、评测合同、可信交互、单位经济、治理和持续学习的产品系统。",project:"从机会访谈到灰度上线，交付一个有离线评测、在线指标、风险登记和退出机制的 AI 产品。"},[
  L(A,"outcome-not-feature","先找结果，不从 AI 功能出发","orientation","用户真正想改善的结果是什么，现有替代为何不够？","结果陈述与非 AI 基线",S.opp),
  L(A,"job-frequency-value","任务频率、价值与失败代价","guided","高频是否一定高价值，低频高风险又应怎样处理？","任务机会评分与访谈证据",S.opp),
  L(A,"ai-suitability","什么问题适合 AI，什么问题不适合","decision","不确定输出、数据需求和审查成本能否被工作流容纳？","AI 适用性门禁与停止理由",S.opp),
  L(A,"opportunity-thesis","写一份可被推翻的机会论证","synthesis","看到什么证据继续投资，看到什么就停止？","机会树、关键假设与反证计划",S.opp),
  L(A,"contextual-inquiry","到现场看用户怎样完成任务","guided","用户说的流程与真实动作、等待和绕路差在哪里？","情境访谈记录与行为证据",S.work),
  L(A,"service-blueprint","把角色、系统与交接画成服务蓝图","mechanism","AI 自动化一步后，成本会转移到谁和哪一步？","主线、例外、交接与责任泳道",S.work),
  L(A,"expertise-segmentation","按能力而非职位设计用户层级","case","新手、熟练者和专家为何需要不同自主度？","能力行为分层与权限梯度",S.work),
  L(A,"workflow-redesign","别把旧流程照搬：重做任务边界","synthesis","AI 出现后哪些步骤应消失、合并或增加验证？","未来工作流与人机责任图",S.work),
  L(B,"capability-matrix","先测能力边界，再画功能清单","guided","模型在哪些任务切片、语言和输入条件下稳定？","能力矩阵与拒绝边界",S.arch),
  L(B,"prompt-rag-workflow-agent","Prompt、RAG、Workflow 与 Agent 阶梯","decision","哪一种已观察失败值得购买更高系统复杂度？","复杂度升级门槛",S.arch),
  L(B,"tool-state-policy","工具、状态与策略必须分层","mechanism","模型能建议什么、工具能执行什么、政策必须拦什么？","系统责任与权限架构图",S.arch),
  L(B,"build-buy-portability","Build、Buy 与可迁移性","decision","供应商变化时，数据、评测和工作流能否带走？","选型记录、锁定风险与退出计划",S.arch),
  L(B,"task-unit-rubric","把‘回答好’改成任务单位与 Rubric","guided","谁在什么条件下依据什么标准判定成功？","任务合同与评分规约",S.eval),
  L(B,"golden-set-slices","黄金集不是一百道平均题","mechanism","主流、长尾、高风险和对抗样本如何共同组成评价集？","分层数据集与覆盖矩阵",S.eval),
  L(B,"failure-taxonomy","失败本体比平均分更能驱动迭代","case","检索失败、推理失败和工具失败该怎样分流？","可归因失败树与责任人",S.eval),
  L(B,"eval-data-flywheel","从线上失败到回归集的数据飞轮","synthesis","哪些反馈可使用，哪些会造成迎合和隐私风险？","采样、复核、版本和污染控制",S.eval),
  L(C,"assumption-tree","先画四类假设树","orientation","最危险的未知是什么，而不是最容易做的功能是什么？","可取性、可行性、持续性与安全假设树",S.exp),
  L(C,"wizard-of-oz","用 Wizard-of-Oz 验证价值","guided","人工幕后服务能否暴露用户选择与真实运营成本？","低保真原型与幕后成本记录",S.exp),
  L(C,"offline-shadow-experiment","离线、影子与 Sandbox 实验","decision","何时只回放历史，何时接真实流量但不执行？","实验阶梯与升级证据",S.exp),
  L(C,"ab-stopping-rules","A/B 测试、护栏与停止规则","derivation","频繁偷看、多指标和稀有伤害怎样制造假阳性？","预注册实验卡与停止门槛",S.exp),
  L(C,"expectation-onboarding","在第一次使用前校准能力预期","concept","演示、文案和示例怎样避免用户误解系统边界？","Onboarding 心智模型测试",S.ux),
  L(C,"uncertainty-evidence","不确定性必须连接证据和下一步","decision","系统不知道时应回答、追问、并列、拒绝还是转人工？","状态—证据—行动矩阵",S.ux),
  L(C,"preview-confirm-undo","预览、确认、撤销与幂等","guided","确认框何时只是责任装饰，何时真的支持判断？","可逆动作流程与故障测试",S.ux),
  L(C,"trust-skill-preservation","信任校准与技能保持","case","用户更快却更不会判断时，产品算成功吗？","过度依赖、低度依赖与技能指标",S.ux),
  L(D,"metric-tree","从客户结果到任务与系统指标","mechanism","哪个领先指标能解释结果变化，而不是替代结果？","三层指标树与因果假设",S.econ),
  L(D,"quality-cost-latency","质量、成本与延迟的 Pareto 前沿","decision","更强模型的收益是否值得 Token、等待和失败恢复？","多方案 Pareto 与路由策略",S.econ),
  L(D,"cost-per-success","算每个成功任务成本，不算每次调用","derivation","人工、重试、检索、工具和赔付怎样进入单位经济？","全成本模型与毛利敏感性",S.econ),
  L(D,"capacity-pricing","容量、限流、降级与定价","case","高峰下哪些请求可降级，哪些必须排队或拒绝？","容量情景、SLO 与价值定价",S.econ),
  L(D,"risk-map","从使用情景开始画 AI 风险图","orientation","谁可能因什么错误受到怎样的伤害？","风险登记与残余风险所有人",S.gov),
  L(D,"data-privacy-security","数据最小化、隐私与攻击面","mechanism","模型、检索、日志和供应商分别看到了什么？","数据流、威胁模型与保留策略",S.gov),
  L(D,"permissions-audit","权限、策略执行与可审计动作","guided","模型建议和执行之间必须经过哪些不可绕过控制？","能力令牌、审批与审计日志",S.gov),
  L(D,"governance-lifecycle","把治理嵌入产品生命周期","synthesis","谁批准用途、模型和数据变化，何时重新评估？","RACI、影响评估与更新门禁",S.gov),
  L(D,"version-release-contract","模型、提示、知识与政策的联合版本","guided","一次发布到底改变了哪几层行为？","发布清单与可重放版本包",S.ops),
  L(D,"canary-rollout","影子、灰度与逐级授权","case","新能力怎样在可观测、可回滚范围内接触用户？","灰度门禁与授权阶梯",S.ops),
  L(D,"feedback-operations","反馈运营：从抱怨到可归因样本","mechanism","点赞点踩为何不足以告诉团队该改哪一层？","反馈分流、抽样与闭环 SLA",S.ops),
  L(D,"ai-incident-review","AI 事故复盘与恢复","case","不确定、第三方和人机交接故障怎样进入事故指挥？","时间线、影响、修复和回归资产",S.ops),
  L(E,"workflow-moat","模型会商品化，工作流怎样形成护城河","concept","哪些专有约束、反馈和分发会随使用越积越厚？","工作流资产图与可复制性审计",S.strat),
  L(E,"evaluation-data-rights","评测资产、数据权利与学习速度","decision","数据多为何不必然形成优势，哪些权利和标签才稀缺？","数据—评测—迭代飞轮",S.strat),
  L(E,"team-operating-model","AI 产品团队的共同语言与责任","guided","产品、领域、设计、模型、工程和风险如何共同决定？","团队接口、评审节奏与决策记录",S.strat),
  L(E,"portfolio-stop-scale","组合管理：何时停止、坚持或规模化","synthesis","有限资源下怎样避免每个 Demo 都变成长尾项目？","投资门槛、退出机制与季度复盘",S.strat),
].map((seed,index)=>({...seed,insight:I[index]})));
