import { defineField, lesson as L } from "./types.ts";
const A="阶段一 · 张量、梯度与稳定训练",B="阶段二 · 结构归纳偏置",C="阶段三 · 基础模型训练",D="阶段四 · 生成与多模态",E="阶段五 · 推理、评测与安全";
const S={grad:["Deep Learning","Autodiff","PyTorch"],opt:["AdamW","BatchNorm","μP"],vision:["ResNet","ViT","ConvNeXt"],seq:["Attention Is All You Need","FlashAttention","Mamba"],scale:["Scaling Laws","Chinchilla","Llama 3"],post:["InstructGPT","DPO","DeepSeek-R1"],gen:["DDPM","DiT","Flow Matching"],multi:["CLIP","Flamingo","World Models"],infer:["LoRA","GPTQ","MoE"],safe:["HELM","Model Cards","AI Safety"]};
const I=[
  "张量不仅有数值和形状，还有轴语义、步幅和设备；广播最危险的是语义错而形状合法。",
  "计算图把值与依赖显式化，局部算子只需保存反向所需状态就能参与整体求导。",
  "反向模式以一次反传累积标量输出对所有参数的梯度，核心收益来自共享中间结果。",
  "自动微分忠实计算程序导数却不保证程序正确，有限差分和不变量测试负责查静默错误。",
  "初始化要让前向激活与反向梯度的方差跨层保持可控，结构和非线性决定缩放规则。",
  "动量累积方向，Adam 缩放坐标，AdamW 解耦衰减；名称相同不代表超参数可直接迁移。",
  "归一化重塑激活统计，残差提供短梯度路径；稳定训练来自两者与初始化的共同作用。",
  "Loss Spike 是数据、数值、优化或并行状态的可观测结果，诊断必须保存批次级因果链。",
  "卷积通过局部连接和权重共享编码平移等变，减少样本需求同时限制全局关系表达。",
  "残差连接让深层学习接近逐步修正，多尺度结构则把空间分辨率与语义抽象重新接合。",
  "ViT 用 Patch Token 和全局注意力弱化视觉先验，因此更依赖数据规模、增强和预训练。",
  "视觉系统的平均准确率会隐藏背景捷径、遮挡、长尾和域变化，错误切片比单分更可行动。",
  "RNN 把历史压缩进递归状态，长路径上的梯度与有限状态容量共同限制远程记忆。",
  "自注意力让每个位置按内容从其他位置取值，Q/K 决定寻址，V 决定被搬运的信息。",
  "Transformer Block 是残差、归一化、注意力和 MLP 的耦合系统，单看注意力无法解释稳定性。",
  "SSM 用固定状态递归压缩历史，注意力保留显式内容寻址；取舍应在任务和硬件上实测。",
  "自监督目标通过遮蔽、预测或对比构造监督，不同目标选择了表示必须保留的信息。",
  "数据清洗、去重和混合配比直接改变能力与偏差，训练数据应像代码一样有版本和审计。",
  "缩放定律是在特定数据与架构上的经验关系，算力最优要求参数和有效 Token 协同增长。",
  "分布式训练把显存问题转成通信与同步问题，效率取决于计算通信重叠和负载平衡。",
  "SFT 用高质量条件示范改变指令行为，但不会自动创造示范未覆盖的知识和验证能力。",
  "奖励模型把偏好压成标量，标注政策、顺序偏差和分布外输入会成为优化可利用的漏洞。",
  "DPO 从偏好对直接估计相对策略，RLHF 在线更新策略；二者都依赖参考分布和偏好质量。",
  "推理后训练能重分配生成计算并优化可验证结果，但更长轨迹不等于机制更忠实。",
  "自回归模型把联合概率拆成条件乘积，训练见真前缀而推理见自身输出，误差会逐步累积。",
  "扩散模型先定义可控加噪过程，再学习逆向去噪；采样质量受噪声日程和求解器共同影响。",
  "Flow Matching 直接拟合概率路径上的速度场，路径与数值积分共同决定效率和误差。",
  "生成评价同时面对逼真、覆盖、条件一致和多样性，任何单一分数都会遗漏一类退化。",
  "对比学习以成对关系塑造共享空间，负样本构造决定模型学到语义还是数据集捷径。",
  "跨模态系统必须区分表示对齐、信息融合和可定位引用，语言流畅不能证明视觉 Grounding。",
  "视频提供时间共变而非完整动作因果，学习可执行动力学还需要动作、接触和干预信号。",
  "世界模型是对观测与动力学的近似；多步规划会放大微小偏差，必须校准不确定性。",
  "LoRA 假设任务更新主要落在低秩子空间，秩、注入位置和数据共同决定适配上限。",
  "量化和剪枝压缩冗余但误差会沿层与时间传播，权重、激活和缓存需要分别评估。",
  "MoE 只让部分专家参与计算，却引入路由、负载与跨设备通信，FLOPs 下降不等于延迟下降。",
  "批处理优化吞吐，缓存复用前缀，推测解码减少串行步骤；三者都可能恶化尾延迟或语义隔离。",
  "公开基准一旦进入训练或反复选择就不再是独立证据，污染审计和私有集必须并存。",
  "探针能证明信息可读出，不自动证明模型在任务中使用它；机制主张需要干预和因果对照。",
  "红队不是一次攻击比赛，而是把威胁模型、攻击样本、修复和回归测试连接成循环。",
  "模型卡应把能力、风险、数据、预算和不适用条件绑定到具体版本，使结论能够被更新。",
];
export default defineField({slug:"deep-learning",title:"深度学习",shortTitle:"深度学习",prefix:"DLF",color:"#6f42c1",promise:"从张量与反向传播一路追到基础模型、生成模型、推理扩展和高效部署，始终保留算力与实验边界。",project:"训练并评估一个可复现的小型多模态模型，交付数据、训练、消融、推理和安全报告。"},[
  L(A,"tensor-shape-stride","张量的形状、步幅与广播","guided","一行广播为何可能算对形状却算错语义？","形状推演、内存布局与单元测试",S.grad),
  L(A,"computation-graph","把神经网络画成计算图","concept","前向值、局部导数与依赖怎样组成可求导程序？","计算图与局部 Jacobian 标注",S.grad),
  L(A,"backprop-chain-rule","反向传播就是复用链式法则","derivation","为何反向模式适合一个标量损失和海量参数？","手算反传与复杂度对照",S.grad),
  L(A,"autodiff-gradient-check","自动微分也会错：做梯度检查","case","数值、原地操作和断图会怎样制造静默梯度错误？","有限差分检查与梯度故障簿",S.grad),
  L(A,"initialization-signal","初始化如何保护信号与梯度","derivation","层数增加时激活和梯度为何会爆炸或消失？","方差传播推导与初始化实验",S.opt),
  L(A,"sgd-momentum-adam","SGD、动量、Adam 与 AdamW","mechanism","自适应步长与解耦权重衰减分别改变了什么？","优化器轨迹和泛化对照",S.opt),
  L(A,"normalization-residual","归一化与残差连接为何让深网可训","mechanism","BatchNorm、LayerNorm 和残差路径各稳定哪一段信号？","层间统计与消融报告",S.opt),
  L(A,"training-failure-diagnosis","从 Loss Spike 到 NaN：训练故障诊断","case","损失尖峰时应先查数据、数值、优化还是并行？","可观测训练面板与故障树",S.opt),
  L(B,"convolution-equivariance","卷积把局部性和平移等变写进结构","derivation","卷积核共享为何减少参数，也限制了能表达的关系？","感受野与等变性实验",S.vision),
  L(B,"resnet-feature-pyramid","残差网络与多尺度特征","mechanism","跳连如何改变深层优化，特征金字塔又解决什么？","ResNet/FPN 特征可视化",S.vision),
  L(B,"vision-transformer","ViT：把图像变成 Token 序列","concept","弱化视觉先验后，数据规模和预训练为何更重要？","CNN/ViT 数据规模对照",S.vision),
  L(B,"vision-error-analysis","别只看 Top-1：视觉错误切片","case","背景、纹理、遮挡与长尾类别会怎样欺骗平均准确率？","反事实图像与切片评测",S.vision),
  L(B,"rnn-sequence-memory","RNN 的状态、记忆与梯度路径","derivation","序列压进固定状态时，哪些信息最先丢失？","展开计算图与记忆压力测试",S.seq),
  L(B,"self-attention","自注意力：内容寻址的信息混合","derivation","Q、K、V 为什么不是三个神秘矩阵？","注意力公式推导与可视化",S.seq),
  L(B,"transformer-block","Transformer Block 的完整数据流","mechanism","残差、归一化、MLP 和位置编码怎样共同工作？","Pre-LN/Post-LN 消融",S.seq),
  L(B,"ssm-attention-tradeoff","SSM 与注意力：状态压缩还是显式检索","decision","长序列质量、吞吐与记忆边界应怎样公平比较？","Attention/SSM Pareto 报告",S.seq),
  L(C,"self-supervised-objectives","自监督目标怎样制造监督信号","concept","掩码、下一词和对比学习各迫使模型保留什么？","目标函数与表示探针",S.scale),
  L(C,"token-data-pipeline","训练数据的清洗、去重与配比","guided","质量过滤和去重怎样同时改变能力、偏差与污染？","数据混合卡与去重审计",S.scale),
  L(C,"scaling-laws-compute","缩放定律与算力最优分配","derivation","固定算力下参数和 Token 应怎样共同增长？","小规模 Scaling 拟合与预算表",S.scale),
  L(C,"distributed-training","数据、张量与流水并行","mechanism","模型放不进一张卡时，通信从哪里成为瓶颈？","显存—通信—吞吐剖析",S.scale),
  L(C,"sft-instruction-data","SFT：用示范重塑条件行为","guided","指令数据的覆盖、格式和质量如何限制模型？","SFT 数据配方与行为回归",S.post),
  L(C,"reward-model-preferences","偏好数据与奖励模型","mechanism","人类比较信号怎样变成标量，又丢失什么？","偏好协议与奖励过拟合测试",S.post),
  L(C,"dpo-rlhf","DPO 与 RLHF 的目标函数","derivation","直接偏好优化和在线策略优化在分布上有何不同？","目标推导与 KL/胜率曲线",S.post),
  L(C,"reasoning-posttraining","推理后训练：过程、结果与验证器","frontier","更长思考何时带来正确性，何时只是更多 Token？","过程/结果奖励与预算评测",S.post),
  L(D,"autoregressive-generation","自回归生成与暴露偏差","derivation","逐 Token 分解似然如何决定训练与采样？","困惑度、采样与序列错误分析",S.gen),
  L(D,"diffusion-denoising","扩散模型：学习逆向去噪","derivation","加噪日程、分数和逆过程怎样连起来？","简化 DDPM 推导与采样实验",S.gen),
  L(D,"flow-matching","Flow Matching：学习概率流速度","frontier","连续流怎样减少采样步骤，又依赖哪些路径？","速度场、路径与求解器对照",S.gen),
  L(D,"generation-evaluation","生成质量、覆盖与可控性的冲突","decision","FID、偏好分和文本对齐为何会给出相反排名？","多指标生成评测卡",S.gen),
  L(D,"contrastive-alignment","对比学习怎样对齐图像与文本","derivation","共享嵌入保留了哪些语义，又抹平了哪些细节？","正负样本与 Retrieval 评测",S.multi),
  L(D,"cross-modal-fusion","跨模态融合、Grounding 与幻觉","mechanism","早融合、交叉注意力和连接器把信息注入哪里？","定位、引用与模态消融",S.multi),
  L(D,"video-action-modeling","从视频表征到动作预测","frontier","观察视觉变化是否足以学习可执行的因果动力学？","视频—动作一致性压力测试",S.multi),
  L(D,"world-model-boundaries","世界模型不是世界：预测闭环的边界","case","像素逼真但动力学错误时，规划器会怎样被误导？","反事实 Rollout 与物理一致性",S.multi),
  L(E,"lora-adapters","LoRA 与参数高效适配","derivation","低秩更新何时足以表达任务变化？","秩—质量—显存消融",S.infer),
  L(E,"quantization-pruning","量化与剪枝：压掉什么信息","mechanism","权重、激活和 KV Cache 精度分别怎样影响误差？","精度—显存—延迟曲线",S.infer),
  L(E,"moe-routing","MoE：稀疏激活不等于系统便宜","mechanism","路由负载、通信和专家容量如何决定真实吞吐？","专家利用率与尾延迟报告",S.infer),
  L(E,"serving-batching-speculation","批处理、缓存与推测解码","decision","吞吐优化为何常常伤害首 Token 与尾延迟？","服务 Pareto 与容量模型",S.infer),
  L(E,"benchmark-contamination","基准污染与选择性过拟合","case","测试集进入训练或开发决策后，分数还代表什么？","污染审计与私有回归集",S.safe),
  L(E,"interpretability-probes","探针、归因与机制解释的证据等级","concept","线性探针读出信息，能否证明模型使用了它？","干预式解释与反例",S.safe),
  L(E,"robustness-red-teaming","鲁棒性、越狱与红队测试","guided","有限攻击样本怎样转化为可维护的风险模型？","攻击树、切片与修复回归",S.safe),
  L(E,"capability-risk-model-card","能力与风险模型卡：让结论可更新","synthesis","模型版本变化时，哪些能力主张必须重新验证？","独立评测、限制与部署门禁",S.safe),
].map((seed,index)=>({...seed,insight:I[index]})));
