import { defineField, lesson as L } from "./types.ts";
const A="阶段一 · 航空系统与飞行基础",B="阶段二 · 飞行器与机载感知",C="阶段三 · 自主飞行闭环",D="阶段四 · 空域服务与规模运行",E="阶段五 · 安全论证与商业化";
const S={sys:["无人驾驶航空器飞行管理暂行条例","民用航空法","ICAO UTM"],flight:["FAA Pilot Handbook","Aircraft Flight Dynamics","Aviation Weather"],vehicle:["Aircraft Design","eVTOL Design","Battery Safety"],sense:["Detect and Avoid","Sensor Fusion","GB 42590"],nav:["Probabilistic Robotics","Visual-Inertial Navigation","GNSS Resilience"],ctrl:["Flight Dynamics and Control","Model Predictive Control","Motion Planning"],utm:["ICAO UTM","ASTM Remote ID","U-space"],fleet:["FAA Vertiport Design","Fleet Management","Maintenance Planning"],swarm:["Multi-Agent Systems","Digital Twin","SORA"],safe:["ARP4761","SORA","NASA AAM"]};
const I=[
  "低空任务是航空器、人员、地面设施、通信、空域服务与第三方共同参与的社会技术系统。",
  "航空器类别、运营主体和飞行活动触发不同规则，产品与运行分类不能互相替代。",
  "ConOps 描述怎样运行，ODD 限定在哪些条件可运行，两者共同定义安全论证边界。",
  "法规证据必须记录法源层级、生效日、适用主体和地域，新闻或试点不能越级外推。",
  "六自由度动力学把力和力矩变成姿态与轨迹，是算法命令与物理运动之间的桥。",
  "性能包线规定可控状态集合，控制器再聪明也不能命令航空器越过结构和气动边界。",
  "低空气象具有局地和瞬态特征，阵风、密度与降水会同时改变升力、能耗和传感。",
  "可执行航程必须扣除风、载荷、老化、备降与法规保留，标称续航只是实验条件。",
  "构型选择是悬停、航程、速度、噪声、设施和失效后果的系统取舍。",
  "Powered-lift 转换区同时改变气动、推进和控制效能，模式切换必须纳入失效分析。",
  "推进效率由桨盘载荷、电机工作点和气动匹配共同决定，峰值功率不等于航程最优。",
  "电池冗余会增加重量和故障组合；热隔离、监测、维护与应急处置必须共同设计。",
  "传感器组合的价值来自互补盲区和独立故障，不是简单叠加标称探测距离。",
  "检测只给瞬时观测，跟踪还需数据关联、运动模型和不确定性才能形成可用航迹。",
  "感知 ODD 要把光照、天气、目标、距离和速度变成切片，平均 mAP 不能证明适航。",
  "DAA 是从探测、跟踪、冲突预测到机动与恢复的时间闭环，延迟预算决定安全余度。",
  "坐标、时间和传感器外参错误会在融合中系统性放大，必须先于算法调参验证。",
  "Kalman 滤波以协方差加权预测和观测，创新一致性负责判断模型是否仍可信。",
  "VIO/SLAM 在局部积分运动并用观测约束漂移，纹理、运动和错误回环决定失效模式。",
  "GNSS 受扰时系统必须根据导航完整性进入预定义降级，而不是继续输出伪精确位置。",
  "级联控制把姿态、速度和位置分在不同带宽，内环稳定是外环性能的前提。",
  "可飞轨迹同时满足动力学、控制、能量和空域约束，几何最短路往往不可执行。",
  "MPC 用滚动预测处理约束，但模型误差和求解超时要求独立围栏与 Fallback。",
  "应急着陆逻辑必须独立于正常规划，并在失链、失能和环境变化下通过 HIL 验证。",
  "C2 安全取决于覆盖、时延、连续性、完整性和恢复，峰值吞吐不能代替链路预算。",
  "Remote ID 在空域透明与隐私安全间取舍，身份、位置和访问角色需分别设计。",
  "UTM 通过交换意图、约束和冲突服务协同交通，并不直接替代航空器飞控。",
  "BVLOS 的核心是探测、通信、程序和应急的组合安全证据，而非单纯飞得更远。",
  "起降点容量受分离、进离场、充电和周转共同限制，停机坪数量不是吞吐量。",
  "周转优化必须同时考虑电池寿命、峰值功率、载荷和准点率，局部最快可能伤害机队。",
  "维修与构型管理要保证每架航空器的硬件、软件和寿命状态可追溯，更新也是适航变化。",
  "机队调度在需求、天气、故障和设施之间动态分配资源，并需要不正常运行恢复策略。",
  "集群协同依赖通信拓扑和局部信息，延迟与失链会改变共识和任务分配可达性。",
  "多机局部避碰可能引发全局死锁，解脱规则必须处理优先权、预测和协同失效。",
  "仿真价值来自假设可追溯、参数校准和场景覆盖，视觉逼真不是验证充分性。",
  "数字孪生只有在数据同步、模型误差和用途边界可量化时才能成为运行证据。",
  "危险分析从后果反推安全目标和独立控制，任务失败率不能替代第三方风险。",
  "安全案例用主张、论证和证据建立可审查链条，并明确残余风险和适用边界。",
  "适航证明产品设计可接受，运行批准证明具体主体在具体场景能安全使用，两者缺一不可。",
  "商业成立取决于单位航次的载荷、利用率、设施、维护、人工与风险成本，而非市场故事。",
];
export default defineField({slug:"low-altitude",title:"物理 AI · 低空智能",shortTitle:"低空智能",prefix:"LAF",color:"#16784f",promise:"把飞行器、感知导航、控制、通信、空域服务、适航和商业运行视为同一个安全关键系统。",project:"一个从任务设计、飞行仿真到风险评估、运行识别和 UTM/UOM 接口的低空巡检数字样机。"},[
  L(A,"mission-system-boundary","从任务而非飞行器画系统边界","orientation","一次低空运行涉及哪些航空器、人员、服务和环境？","任务—系统—责任上下文图",S.sys),
  L(A,"aircraft-operator-airspace","航空器、运营人、空域与飞行活动","concept","产品分类与运行分类为什么不能混为一谈？","主体、对象、活动与许可矩阵",S.sys),
  L(A,"conops-odd","ConOps 与运行设计域","guided","‘能飞’怎样限定为天气、空域、链路和处置条件？","ConOps、ODD 与退出条件",S.sys),
  L(A,"regulatory-evidence-ledger","法规标准如何进入证据账本","decision","新闻、征求意见稿、标准和法律分别支持什么判断？","来源等级、适用范围与更新触发器",S.sys),
  L(A,"forces-six-dof","四种力与六自由度飞行","derivation","升力、重力、推力和阻力怎样形成姿态与轨迹？","六自由度方程与受力图",S.flight),
  L(A,"stability-control-envelope","稳定性、操纵性与性能包线","mechanism","算法命令为何必须被速度、载荷和姿态边界约束？","飞行包线与保护逻辑",S.flight),
  L(A,"weather-wind-density","风、密度、温度与降水","case","地面风不大时，航线中的阵风为何仍危险？","微气象风险与气象门槛",S.flight),
  L(A,"energy-reserve-mission","能量余度与任务可达性","guided","标称续航为何不能直接变成可执行航程？","能量模型、备降与保留策略",S.flight),
  L(B,"uav-configurations","多旋翼、固定翼与复合翼","decision","悬停、航程、速度和起降条件怎样决定构型？","任务—构型 Trade-off 表",S.vehicle),
  L(B,"evtol-powered-lift","eVTOL 与 Powered-lift 转换飞行","mechanism","悬停到巡航的转换为何是控制和适航难点？","模式状态机与失效分析",S.vehicle),
  L(B,"propulsion-efficiency","电机、桨叶与推进效率","derivation","桨盘载荷、转速和噪声怎样共同限制设计？","推进匹配与效率曲线",S.vehicle),
  L(B,"battery-thermal-redundancy","电池热安全与冗余","case","增加冗余为何也增加重量、故障组合和维护负担？","能量系统 FMEA 与热失控隔离",S.vehicle),
  L(B,"sensor-coverage","相机、雷达、LiDAR 与协同监视","decision","传感器在距离、天气、纹理和合作目标上各看不见什么？","覆盖—盲区—资源矩阵",S.sense),
  L(B,"detection-tracking","从检测到多目标跟踪","mechanism","一次识别框怎样变成带速度和不确定性的航迹？","关联、滤波与轨迹质量评测",S.sense),
  L(B,"perception-odd","给感知系统写 ODD","guided","平均 mAP 为什么不能证明它适合航线和速度范围？","场景切片、漏警预算与拒绝条件",S.sense),
  L(B,"daa-decision-loop","探测避让是时间受限的决策闭环","case","发现冲突后，告警、机动和恢复须在多久内完成？","DAA 时间预算与 Encounter 回放",S.sense),
  L(C,"frames-calibration","坐标系、时间同步与标定","guided","厘米级传感器误差为何会变成米级航迹偏差？","坐标链、外参与时间偏差实验",S.nav),
  L(C,"kalman-sensor-fusion","Kalman 滤波与多传感融合","derivation","预测、观测和协方差怎样决定相信谁？","EKF 推导、创新门禁与一致性",S.nav),
  L(C,"vio-slam","视觉惯性里程计与 SLAM","mechanism","纹理贫乏、快速运动和回环错误会怎样累积？","轨迹误差、漂移与回环压力测试",S.nav),
  L(C,"gnss-denied-degradation","GNSS 受扰时的降级与恢复","case","定位置信度下降后应继续、返航、悬停还是迫降？","导航完整性、降级状态机与演练",S.nav),
  L(C,"pid-lqr-cascaded-control","级联 PID、LQR 与内外环","derivation","姿态、速度和位置环为何必须分时间尺度设计？","闭环响应与稳定裕度实验",S.ctrl),
  L(C,"trajectory-generation","从航点到可飞轨迹","mechanism","几何最短路径为何可能违反动力学和舒适性？","约束轨迹与平滑度报告",S.ctrl),
  L(C,"mpc-geofence","MPC、地理围栏与可达集","guided","预测控制怎样在滚动优化中尊重硬边界？","约束违例、可达性与 Fallback",S.ctrl),
  L(C,"emergency-landing","失链、失能与应急着陆","case","正常规划器失效时，独立应急逻辑如何接管？","故障树、备降点与 HIL 演练",S.ctrl),
  L(D,"c2-link-budget","C2 链路预算、时延与连续性","derivation","吞吐足够为何仍不能证明指挥链路可靠？","覆盖、时延、丢包与冗余预算",S.utm),
  L(D,"remote-identification","运行识别：身份、位置与隐私","concept","谁需要识别谁，广播和网络方式各承担什么？","Remote ID 数据与威胁模型",S.utm),
  L(D,"utm-intent-conflict","UTM 如何交换意图与冲突","mechanism","服务提供者怎样在不操纵飞机时管理交通？","意图、约束、冲突与响应状态机",S.utm),
  L(D,"bvlos-contingency","BVLOS 的链路、监视与应急组合","case","超视距不是距离问题，而是哪组安全功能组合问题？","SORA 风险、缓解与 Contingency 表",S.utm),
  L(D,"vertiport-capacity","起降点、进离场与容量","mechanism","一个停机坪怎样因分离、充电和周转成为瓶颈？","Vertiport 流程与容量模型",S.fleet),
  L(D,"charging-turnaround","充换电、载荷与周转","guided","怎样在电池寿命、峰值功率和准点间取舍？","周转甘特图与能源需求",S.fleet),
  L(D,"maintenance-reliability","维修、可靠性与构型管理","case","更新和换件如何保持每架飞机的适航状态？","维修计划、部件寿命与构型账本",S.fleet),
  L(D,"fleet-dispatch","机队调度与不正常运行","decision","天气、故障和需求同时变化时怎样派机和恢复？","调度策略与 Disruption 演练",S.fleet),
  L(D,"swarm-topology-consensus","集群拓扑、共识与任务分配","mechanism","通信局部且延迟变化时，多机怎样保持协同？","拓扑、任务分配与失链实验",S.swarm),
  L(D,"collision-deconfliction","多机冲突探测与解脱","derivation","局部避碰如何避免制造新的全局冲突？","冲突图、优先权与死锁测试",S.swarm),
  L(D,"simulation-fidelity","仿真可信度与场景覆盖","guided","高保真画面为什么不等于有效验证？","模型层级、参数校准与覆盖矩阵",S.swarm),
  L(D,"digital-twin-evidence","数字孪生怎样成为运行证据","frontier","实时同步、预测和回放分别需要怎样的可信度？","孪生边界、数据谱系与故障注入",S.swarm),
  L(E,"hazard-analysis","从危险到安全目标","guided","任务失败怎样沿人员、航空器和第三方后果分级？","FHA、故障树与安全目标",S.safe),
  L(E,"assurance-case","用证据链写安全论证","mechanism","需求、分析、试验和限制怎样共同支持一个主张？","Claim–Argument–Evidence 案例",S.safe),
  L(E,"certification-operations","适航批准与运行批准不是一回事","decision","产品证据与具体运营场景的责任边界在哪里？","批准路径与合规差距表",S.safe),
  L(E,"unit-economics-scale","单位航次经济与规模化边界","synthesis","载荷、利用率、设施、维护和安全成本怎样决定场景成立？","单位航次模型与规模化门槛",S.safe),
].map((seed,index)=>({...seed,insight:I[index]})));
