import { defineField, lesson as L } from "./types.ts";

const A="阶段一 · 问题、数据与泛化", B="阶段二 · 可解释强基线", C="阶段三 · 表示、训练与选型", D="阶段四 · 因果、可信与鲁棒", E="阶段五 · 生产闭环";
const S={found:["ESL","ISLR","Model Cards"],data:["Datasheets for Datasets","WILDS","Data Leakage"],linear:["GLM","Maximum Likelihood","Calibration"],tree:["Random Forests","XGBoost","CatBoost"],repr:["Kernel Methods","SVM","UMAP"],opt:["PRML","Bayesian Optimization","Nested CV"],auto:["auto-sklearn","AutoGluon","TabPFN"],causal:["Causal Inference: What If","Double ML","CausalML"],trust:["Conformal Prediction","Fairness and Machine Learning","NIST AI RMF"],prod:["ML Test Score","Data Cascades","NIST AI RMF"]};
const I=[
  "学习问题必须绑定决策者、预测时点、对象、可用信息和动作，否则高分也没有可行动含义。",
  "样本是一项观测事件，特征只能来自决策前，标签则需要明确发生窗口和成熟时间。",
  "损失函数把某类误差变成训练信号，但业务代价还取决于阈值、容量和后续动作。",
  "经验风险只描述已见样本；泛化判断必须依靠独立数据、容量约束、基线和反例。",
  "数据不是静态表，而是抽样、业务筛选、测量与反馈共同形成的生成过程。",
  "缺失值和错误标签常由流程机制产生；把它们当随机噪声会系统性偏向容易观测的人群。",
  "切分协议是在模拟未来使用：时间、实体或空间相关性存在时，随机切分会偷走难度。",
  "泄漏可以发生在采集、特征、预处理、调参和人工选择任何一环，必须沿谱系攻击。",
  "最小二乘是把目标投影到特征张成空间；残差结构是在告诉你线性假设漏掉了什么。",
  "广义线性模型由响应分布、线性预测子和链接函数组成，三者共同决定概率含义。",
  "排序能力与概率校准互不等价；可靠概率需要在独立分布上用 proper scoring rule 检查。",
  "阈值属于决策政策而非模型常数，它应随错判成本、资源容量和人群约束重新计算。",
  "决策树用轴对齐贪心切分近似分段函数，易解释但对样本扰动和深度高度敏感。",
  "Bagging 通过平均不完全相关的高方差模型降方差；树越像，平均带来的收益越小。",
  "Boosting 沿函数空间的负梯度逐轮加模型，学习率、树容量与轮数共同控制偏差和过拟合。",
  "归因描述模型在当前数据上的行为，不是变量的因果贡献；相关与代理特征会重分配重要性。",
  "特征尺度和度量先定义了相似性，算法只是在这个被选择的几何空间中工作。",
  "KNN 的有效性依赖局部平滑和足够密度；高维下最近邻也可能远且不可靠。",
  "SVM 用间隔控制复杂度，核函数只提供隐式内积；核宽度决定模型眼中的邻域。",
  "PCA 保留线性方差，UMAP 优先局部邻域；二维可视化不能单独证明真实群体存在。",
  "条件数和曲率决定梯度沿不同方向的有效步长，同一最优点也可能呈现完全不同训练难度。",
  "随机梯度既是估计误差也是隐式正则；优化器比较必须同时固定批量、学习率计划和预算。",
  "正则化不是免费防过拟合，而是用可控偏差换取方差、稀疏性、平滑性或稳定性。",
  "超参数搜索也是训练过程；嵌套验证把模型选择和最终性能估计隔离，避免验证集过拟合。",
  "特征流水线必须把每个拟合步骤限制在训练折，并保证训练和服务共享同一语义版本。",
  "AutoML 自动化的是候选与搜索，不会替你修正错误目标、泄漏切分或不可接受的成本。",
  "表格基础模型把合成任务先验摊销到一次推断，优势取决于新任务是否落在预训练先验内。",
  "模型选择是质量、校准、延迟、成本、可解释和维护性的多目标决策，不是排行榜取第一。",
  "预测描述条件相关，因果问题询问干预后的反事实；两者需要不同数据和识别假设。",
  "DAG 的价值是暴露条件独立与不可观测假设，错误调整碰撞点会主动制造偏差。",
  "随机化平衡潜在混杂，但干扰、流失、执行偏差和多重检验仍会破坏实验解释。",
  "Double ML 用交叉拟合削弱高维干扰估计偏差，却不能替代因果识别和重叠条件。",
  "偶然不确定性来自结果随机性，认知不确定性来自模型知识不足，两者需要不同处置。",
  "共形预测依赖交换性给出边际覆盖承诺；分布偏移和条件覆盖不能被一个总体数字掩盖。",
  "公平指标对应不同价值判断且常互相冲突，必须把伤害、群体和决策权写进政策。",
  "鲁棒性不是对所有变化不变，而是在预先定义的偏移族内保持性能或可靠拒绝。",
  "可复现要求数据、代码、环境、模型、阈值和配置共同版本化，并能重放单次预测。",
  "影子与金丝雀发布把真实输入和真实影响分开，让系统先证明可观察、可回滚。",
  "监测必须覆盖输入、表示、输出、性能和业务反馈；无标签时代理信号只能触发调查。",
  "模型事故的长期价值来自把失败变成回归样本、监控规则、发布门禁和责任改进。",
];

export default defineField({slug:"machine-learning",title:"机器学习",shortTitle:"机器学习",prefix:"MLF",color:"#176b87",promise:"从可证伪的问题定义出发，掌握数据、模型、泛化、因果、不确定性和生产闭环，而不是只会调包。",project:"一套能解释数据切分、基线、校准、偏移、因果边界与上线监控的风险预测系统。",fieldSummary:{text:"机器学习板块学习总结",link:"/fields/machine-learning/summary"},stageSummaries:[{stage:A,text:"阶段总结 · 从业务问题到可信实验",link:"/fields/machine-learning/stage-1-review"},{stage:B,text:"阶段总结 · 建立一条可解释强基线",link:"/fields/machine-learning/stage-2-review"},{stage:C,text:"阶段总结 · 从表示设计到模型选型",link:"/fields/machine-learning/stage-3-review"},{stage:D,text:"阶段总结 · 从预测分数到可信行动",link:"/fields/machine-learning/stage-4-review"},{stage:E,text:"阶段总结 · 让模型在生产中持续可控",link:"/fields/machine-learning/stage-5-review"}]},[
  L(A,"business-question-to-ml-task","从业务愿望到可证伪任务","orientation","一句‘预测流失’怎样变成有对象、有时点、有动作的学习问题？","问题定义卡与非机器学习基线",S.found),
  L(A,"samples-features-labels","样本、特征与标签不是三张表","concept","观测单位和预测时点写错，会怎样改变模型真正学习的对象？","样本单位—标签窗口—特征截止图",S.found),
  L(A,"loss-and-decision-cost","损失函数在替谁承担代价","derivation","训练损失为什么不能直接代表业务决策质量？","损失—指标—行动成本映射",S.found),
  L(A,"erm-generalization-baseline","经验风险、泛化与最小基线","synthesis","模型在训练集上变好后，凭什么相信它能面对未来？","基线、学习曲线与泛化检查",S.found),
  L(A,"data-generating-process","先画数据是怎样被世界生成的","orientation","数据表的每一行是自然出现的，还是被业务流程筛选出来的？","数据生成过程与选择机制图",S.data),
  L(A,"labels-missingness-bias","标签、缺失与偏差从哪里来","case","没有标签和标签为零为何是两种完全不同的事实？","标注规范、缺失机制与偏差清单",S.data),
  L(A,"time-group-spatial-splits","时间、群组与空间切分","guided","随机切分在哪些任务上会系统性高估泛化？","三种切分协议与基线差异报告",S.data),
  L(A,"leakage-audit","做一次端到端泄漏审计","case","未来信息会沿哪些数据、特征和调参通道悄悄进入训练？","数据谱系、泄漏攻击与修复回归集",S.data),
  L(B,"linear-regression-geometry","线性回归的几何与残差","derivation","最小二乘究竟投影了什么，残差图又在反驳什么？","闭式解、残差诊断与异常点实验",S.linear),
  L(B,"likelihood-and-glm","从似然走到广义线性模型","mechanism","分布假设、链接函数和线性预测子怎样连成一个概率模型？","似然推导与 GLM 选择表",S.linear),
  L(B,"logistic-calibration","逻辑回归、排序与校准","guided","AUC 很高的概率为什么仍可能不可信？","可靠性图、Brier/NLL 与重校准实验",S.linear),
  L(B,"thresholds-and-costs","阈值不是 0.5：把概率变成行动","decision","审核容量和错判成本变化时，最优阈值为什么也应变化？","成本曲线、拒绝区与阈值策略",S.linear),
  L(B,"decision-tree-partitions","决策树如何切开特征空间","mechanism","一次贪心分裂如何换来可解释规则，又失去什么？","手算分裂、剪枝与稳定性实验",S.tree),
  L(B,"bagging-random-forest","Bagging 与随机森林为什么降方差","derivation","许多相关的树平均以后，误差会在什么条件下下降？","树间相关、袋外误差与方差对照",S.tree),
  L(B,"boosting-xgboost-catboost","Boosting：沿着损失梯度加树","mechanism","串行拟合残差为何能降低偏差，又为何容易被泄漏放大？","XGBoost/CatBoost 预算公平消融",S.tree),
  L(B,"feature-importance-shap","特征重要性为什么经常撒谎","case","相关特征、代理变量和分布变化会怎样改写 SHAP 排名？","三种归因对照与不可外推清单",S.tree),
  L(C,"scaling-distance-similarity","尺度与距离定义了模型眼中的世界","concept","欧氏、余弦和领域距离分别把什么当成相似？","度量合同与尺度敏感性实验",S.repr),
  L(C,"knn-local-learning","KNN 与局部学习的有效半径","guided","最近邻很近，是否意味着它足够像？","邻域纯度、维度灾难与拒绝阈值",S.repr),
  L(C,"svm-kernel-margin","SVM、间隔与核技巧","derivation","不显式升维时，核函数怎样改变可分边界？","软间隔推导与核参数对照",S.repr),
  L(C,"pca-umap-visualization","PCA 与 UMAP：漂亮图不等于真实结构","case","二维簇能支持哪些结论，不能支持哪些结论？","保真度、多种子稳定性与反例图",S.repr),
  L(C,"optimization-landscape","优化目标、曲率与条件数","derivation","同一损失函数为什么会有截然不同的训练难度？","等高线、条件数与收敛轨迹实验",S.opt),
  L(C,"sgd-optimizers","SGD、动量与自适应优化","mechanism","噪声梯度何时帮助泛化，何时制造不稳定？","优化器—批量—学习率消融",S.opt),
  L(C,"regularization-bias-variance","正则化如何购买偏差并减少方差","concept","L1、L2、早停和数据增强分别约束了什么？","正则路径与偏差—方差报告",S.opt),
  L(C,"nested-cv-hpo","嵌套交叉验证与无泄漏调参","guided","验证集被反复使用后为什么也会过拟合？","嵌套 CV、搜索预算与选择协议",S.opt),
  L(C,"feature-pipeline-contract","把特征工程写成可重放流水线","guided","训练与服务的同名特征为何仍可能不是同一个量？","拟合边界、特征契约与回放测试",S.auto),
  L(C,"automl-search-budget","AutoML 搜索了什么，又遗漏了什么","decision","自动搜索怎样在固定预算内公平比较，而不偷看测试集？","搜索空间、预算与停止门禁",S.auto),
  L(C,"tabular-foundation-models","表格基础模型的先验从哪里来","frontier","TabPFN 的一次前向预测在哪些数据上可视为摊销推断？","TFM/GBDT/线性模型边界对照",S.auto),
  L(C,"model-selection-pareto","模型选型不是排行榜：画出 Pareto 前沿","decision","质量、延迟、成本、可解释和维护性冲突时怎样选？","多目标选择记录与淘汰理由",S.auto),
  L(D,"prediction-vs-causation","预测问题与因果问题的分水岭","orientation","知道谁会购买，为什么不能告诉你优惠券发给谁？","预测目标与干预目标对照卡",S.causal),
  L(D,"dag-identification","用 DAG 写出不可见的假设","mechanism","后门路径、碰撞点和中介变量为什么决定能否识别？","因果图、调整集与反例",S.causal),
  L(D,"randomized-experiments","随机实验、功效与停止规则","guided","A/B 测试何时仍会因干扰、流失和多重检验而失真？","预注册、功效分析与实验报告",S.causal),
  L(D,"heterogeneous-effects-dml","异质处理效应与 Double ML","frontier","机器学习怎样估计谁受益，同时避免把拟合能力当因果识别？","交叉拟合、uplift 与敏感性分析",S.causal),
  L(D,"aleatoric-epistemic-calibration","两类不确定性与校准边界","concept","数据本身的噪声与模型不知道的部分应怎样分别处理？","不确定性来源图与校准切片",S.trust),
  L(D,"conformal-prediction","共形预测：为单次预测给出覆盖承诺","derivation","有限样本覆盖率依赖哪些交换性条件？","预测集、覆盖率与集合宽度实验",S.trust),
  L(D,"fairness-subgroup-errors","公平不是一个指标：看群体误差与伤害","decision","不同公平定义互相冲突时，谁来决定可接受取舍？","群体切片、阈值政策与影响说明",S.trust),
  L(D,"distribution-shift-stress","分布偏移与鲁棒性压力测试","case","模型面对新医院、新城市或新政策时会先从哪里坏？","偏移矩阵、拒绝策略与再训练触发器",S.trust),
  L(E,"reproducibility-registry","版本化数据、代码、模型与阈值","guided","半年后怎样精确重放一次预测及其训练依据？","可复现实验包与模型登记卡",S.prod),
  L(E,"serving-shadow-canary","服务、影子流量与灰度发布","case","离线优秀的模型怎样在不伤害用户时接触真实流量？","影子对照、金丝雀门禁与回滚演练",S.prod),
  L(E,"monitoring-drift","监测输入、输出、性能与业务反馈","mechanism","没有即时标签时，哪些信号能提示模型正在失效？","漂移仪表盘与分层告警",S.prod),
  L(E,"ml-incidents-learning-loop","从模型事故回到学习飞轮","synthesis","一次事故怎样变成数据、评测、SOP 和组织能力的复利？","事故复盘、回归样本与更新路线",S.prod),
].map((seed,index)=>({...seed,insight:I[index]})));
