import { defineField, lesson as L } from "./types.ts";
const A="阶段一 · 语言、语料与切分",B="阶段二 · 表示与序列建模",C="阶段三 · 预训练与结构化任务",D="阶段四 · 生成与多语言",E="阶段五 · 检索、事实与治理";
const S={task:["Speech and Language Processing","Data Statements","Responsible NLP"],tok:["BPE","SentencePiece","ByT5"],sem:["Distributional Semantics","word2vec","Sentence-BERT"],seq:["Seq2Seq","BERT","T5"],adapt:["GPT-3","T5","DPO"],struct:["CoNLL","Universal Dependencies","Structured Generation"],gen:["ROUGE","COMET","Dialogue Evaluation"],multi:["FLORES","Masakhane","Multilingual Evaluation"],rag:["RAG","Lost in the Middle","Long Context Evaluation"],eval:["FActScore","LLM-as-a-Judge","Model Cards"]};
const I=[
  "语言形式的含义依赖语境、说话者和共同知识，任务必须明确系统能看到哪些上下文。",
  "NLP 任务定义应把语言现象转成输入、输出、评价单位和拒绝条件，而不是笼统要求理解。",
  "语料由平台、抽样、许可与社会群体共同塑造，可获得不等于有代表性或有权使用。",
  "标注分歧可能反映真实歧义和价值差异，强行多数表决会删除任务本身的重要结构。",
  "词是理论单位而非跨语言自然常数，形态和书写系统决定可接受的分割假设。",
  "BPE 以频繁符号合并压缩序列，词表越大未必越好，因为稀有组合和跨域变化仍存在。",
  "Tokenizer 决定序列长度、成本和上下文份额，语言间膨胀率是产品公平与容量问题。",
  "字节级建模消除未知词但延长序列并把分词负担交给网络，质量和效率需共同比较。",
  "分布假设用共现近似语义相关，却不能从相似向量推出事实、逻辑或因果关系。",
  "负采样把完整词表预测变成判别任务，采样分布直接塑造向量空间中的邻域。",
  "上下文表示让同一表面词在不同句子中获得不同向量，层次和任务决定可读出的语义。",
  "句向量检索依赖训练过的相似性；Hard Negative 用来区分语言相近但事实或意图不同。",
  "RNN 建模上下文，CRF 对标签序列做联合归一化，从而把结构约束放进解码。",
  "双向编码器同时利用左右上下文，适合理解任务，却不能天然承担自回归生成。",
  "解码器按历史输出预测下一项，教师强制带来的训练推理差异会放大早期错误。",
  "架构选择取决于输入是否完整、输出是否开放、是否需要生成和端到端延迟，而非潮流。",
  "语言模型目标学习条件分布，迁移能力来自数据和参数共享，但不保证任务指令或事实可靠。",
  "上下文学习对示例选择、顺序和格式敏感，提示应像代码一样做回归和版本化。",
  "适配方式是在知识更新、行为改变、数据量、成本和可回退性之间选择，不是越深越好。",
  "偏好优化重塑回答分布，也可能把主流标注者的风格和价值放大为系统默认。",
  "分类性能上限由标签本体决定；互斥、层级、开放集和拒绝类必须先于模型设计。",
  "实体抽取的边界与嵌套需要明确匹配协议，否则相同输出会因评分口径得到不同结论。",
  "关系和事件把实体连接成带角色、时间和跨句依赖的结构，局部分类不足以保证一致。",
  "结构化生成必须依次通过语法、Schema、实体引用和业务规则，JSON 合法只是第一层。",
  "解码算法改变搜索与随机性而不改变模型分布，质量、多样性和可重复性会互相制约。",
  "摘要忠实度要求每个主张能被原文支持，覆盖、压缩和措辞流畅都不能替代蕴含检查。",
  "对话系统必须显式管理目标、槽位、承诺和工具状态，语言历史不能可靠充当事务状态。",
  "文档翻译需要跨句维护术语、指代和语域，逐句高分仍可能产生整体冲突。",
  "跨语言迁移依赖共享表示和数据重叠，语言距离与资源不均会造成非对称收益。",
  "低资源包含数据、工具、正字法、领域和社区权力问题，仅翻译高资源数据不能补齐。",
  "混语与方言是正常语言实践，标准语测试会系统性漏掉真实用户的输入分布。",
  "文化评价需要本地情境、价值和社区参与，翻译现有题库不能证明文化适用性。",
  "检索质量由切分、索引、查询和召回共同决定，块既要可找又要保留证据上下文。",
  "重排优化候选顺序，证据覆盖关注回答所需事实是否齐全；Top-k 相似不等于充分。",
  "长上下文窗口是容量声明，利用能力还受位置、干扰、推理跨度和语言影响。",
  "RAG、长上下文和微调分别解决知识访问、上下文容量和行为适配，应按更新与引用需求选。",
  "事实性评价应先把回答拆成原子主张，再检查证据支持、冲突、遗漏和引用位置。",
  "自动指标擅长规模与一致性，人评擅长情境与价值判断；两者的不一致本身也是证据。",
  "LLM Judge 受位置、长度、风格和自偏好影响，必须用盲评、交换和人类样本校准。",
  "生产 NLP 的学习闭环要控制反馈偏差、隐私和数据污染，让失败进入可追溯回归集。",
];
export default defineField({slug:"nlp",title:"自然语言处理（NLP）",shortTitle:"NLP",prefix:"NLPF",color:"#a34b12",promise:"把语言现象、数据标注、表示学习、生成、跨语言与真实交互重新连成一条线，不把 NLP 缩成调用大模型。",project:"一个中文优先、可追溯、可拒答、跨语言可评测的领域文本理解与生成系统。"},[
  L(A,"language-ambiguity-context","语言为什么天然含糊：歧义与语境","concept","同一句话在不同说话人、时间和关系中为何不是同一个输入？","歧义类型与上下文需求表",S.task),
  L(A,"task-formulation","把语言需求写成可评价任务","orientation","‘理解文档’怎样拆成分类、抽取、检索或生成？","任务本体与输入输出合同",S.task),
  L(A,"corpus-sampling-rights","语料从哪里来：抽样、权利与代表性","case","可抓取文本为什么不等于可训练、可发布的数据？","语料卡、许可与代表性审计",S.task),
  L(A,"annotation-disagreement","标注分歧不是噪声：建模多种解释","guided","标注员不一致时，何时仲裁、保留分布或重写任务？","标注指南与分歧模型",S.task),
  L(A,"words-morphemes-writing-systems","词、词素与文字系统","concept","中文、黏着语和拼音文字为何不能共享一种‘词’假设？","跨语言切分现象图",S.tok),
  L(A,"bpe-sentencepiece","BPE 与 SentencePiece 如何学词表","derivation","频次合并怎样在词表大小和序列长度间取舍？","手算 BPE 与词表实验",S.tok),
  L(A,"tokenization-cost-fairness","Tokenizer 的成本与语言公平","case","同一句话为何在不同语言中消耗不同 Token 与上下文？","多语言膨胀率与成本审计",S.tok),
  L(A,"byte-level-models","字节级模型与开放词汇边界","frontier","绕开固定词表能解决什么，又把难度移到哪里？","Token/byte 质量—延迟对照",S.tok),
  L(B,"distributional-hypothesis","词义从上下文分布中来","concept","相似上下文能捕捉哪些语义，不能捕捉哪些事实？","共现矩阵与语义反例",S.sem),
  L(B,"word2vec-negative-sampling","word2vec 与负采样","derivation","预测上下文为何会产生可用的词向量空间？","Skip-gram 目标与邻域实验",S.sem),
  L(B,"contextual-embeddings","从静态词向量到上下文表示","mechanism","同一个词的表示怎样随句子变化？","词义消歧探针与层间对照",S.sem),
  L(B,"sentence-embedding-retrieval","句向量、相似度与 Hard Negative","guided","高余弦相似为什么仍可能检索到错误事实？","检索集、难负例与阈值报告",S.sem),
  L(B,"rnn-lstm-crf","RNN、LSTM 与 CRF 的序列约束","mechanism","局部标签为什么需要联合解码？","BiLSTM-CRF 基线与边界错误",S.seq),
  L(B,"encoder-bidirectional","编码器如何聚合双向上下文","concept","BERT 式掩码预训练为何适合理解任务？","编码器分类/抽取探针",S.seq),
  L(B,"decoder-autoregressive","解码器如何逐步生成","derivation","教师强制训练为何导致推理时暴露偏差？","解码策略与错误传播实验",S.seq),
  L(B,"encoder-decoder-choice","Encoder、Decoder 还是 Encoder–Decoder","decision","应依据哪些信息流和延迟约束选择架构？","架构选择树与公平基线",S.seq),
  L(C,"language-model-objectives","语言模型目标与涌现行为","derivation","最大化下一 Token 概率为何能产生任务迁移？","目标函数、提示敏感与能力边界",S.adapt),
  L(C,"prompting-in-context","提示与上下文学习","guided","示例顺序、格式和标签词为何会改变结果？","提示消融与稳定性报告",S.adapt),
  L(C,"peft-finetuning","PEFT、全量微调与灾难性遗忘","decision","数据量、域偏移和部署约束如何决定适配方式？","零样本—RAG—PEFT—全调阶梯",S.adapt),
  L(C,"preference-alignment","偏好优化与语言行为边界","frontier","奖励流畅和有用时，事实与少数语言会发生什么？","偏好集切片与行为回归",S.adapt),
  L(C,"classification-label-space","分类首先是标签空间设计","orientation","类别互斥、层级和开放集假设怎样改变评价？","标签本体与拒绝类",S.struct),
  L(C,"ner-boundary-matching","实体边界、嵌套与匹配协议","guided","预测含义正确但 Span 差一个字符时应怎样计分？","边界错误本体与 Span 评测",S.struct),
  L(C,"relations-events","关系与事件抽取","mechanism","局部实体如何组合成跨句、带角色的结构？","Schema、约束与图一致性检查",S.struct),
  L(C,"constrained-generation","约束生成与输出校验器","case","JSON 合法为什么仍不等于语义和业务约束正确？","语法、Schema、实体与政策四层校验",S.struct),
  L(D,"decoding-strategies","贪心、束搜索与采样","derivation","搜索更充分为什么不一定让文本更好？","解码参数—质量—多样性实验",S.gen),
  L(D,"summarization-faithfulness","摘要的覆盖与忠实度","case","语句都来自原文时，摘要为何仍可能歪曲结论？","事实单元、遗漏与归因评测",S.gen),
  L(D,"dialogue-state-repair","对话状态、承诺与修复","mechanism","多轮助手怎样记住目标又不伪造已完成的动作？","状态机、承诺账本与修复路径",S.gen),
  L(D,"document-translation","文档级翻译与一致性","guided","句句正确为何仍会在术语、指代和语气上失败？","术语库、篇章一致性与 COMET/人评",S.gen),
  L(D,"cross-lingual-transfer","跨语言迁移从共享表示中来","mechanism","高资源语言能力怎样迁移，又会在哪里失真？","零样本迁移与语言距离切片",S.multi),
  L(D,"low-resource-data","低资源不只是数据少","case","正字法、领域、数字鸿沟和标注权力怎样共同限制模型？","社区数据计划与风险说明",S.multi),
  L(D,"code-switching-dialects","混语、方言与非标准书写","guided","标准语基准为何会隐藏真实交互失败？","混语集、音译与方言压力测试",S.multi),
  L(D,"cultural-evaluation","文化语境不能只靠翻译基准","frontier","当地用户认为什么是正确、冒犯或有用，如何进入评价？","文化情境任务与社区评审",S.multi),
  L(E,"retrieval-indexing","检索流水线：切分、索引与召回","guided","文档怎样切块才能既被找到又保留证据语境？","分块、混合检索与召回基线",S.rag),
  L(E,"reranking-evidence","重排与证据覆盖","mechanism","Top-k 相似文段为何会遗漏完整证据链？","难负例、重排与覆盖率",S.rag),
  L(E,"long-context-utilization","能放进去不等于能用：长上下文利用","case","关键信息位置、干扰项和长度怎样改变模型？","位置—长度—干扰矩阵",S.rag),
  L(E,"rag-or-long-context","RAG、长上下文还是微调","decision","知识更新、引用、延迟和隐私约束下该怎样选？","方案 Pareto 与升级门槛",S.rag),
  L(E,"claim-evidence-factuality","把回答拆成 Claim–Evidence","guided","总体事实正确怎样落实到每个可验证主张？","主张账本、证据蕴含与引用覆盖",S.eval),
  L(E,"metrics-human-evaluation","自动指标与人评分别看见什么","decision","BLEU、ROUGE、模型裁判和专家人评如何组合？","多方法评价协议与不一致分析",S.eval),
  L(E,"judge-bias-calibration","LLM Judge 的偏差与校准","case","位置、长度、自偏好和提示会怎样扭曲裁判分数？","盲评、交换顺序与人类校准",S.eval),
  L(E,"production-nlp-governance","把语言失败变成持续学习闭环","synthesis","线上反馈怎样避免只奖励迎合、热门语言和容易样本？","失败本体、抽样复核与版本回归",S.eval),
].map((seed,index)=>({...seed,insight:I[index]})));
