import { defineField, lesson as L } from "./types.ts";
const A="阶段一 · 具身任务与物理基础",B="阶段二 · 控制、感知与状态",C="阶段三 · 导航与操作",D="阶段四 · 机器人学习与基础模型",E="阶段五 · 仿真、安全与部署";
const S={sys:["Introduction to Robotics","Probabilistic Robotics","NIST Test Methods"],kin:["Modern Robotics","Robotics: Modelling, Planning and Control","Rigid Body Dynamics"],ctrl:["Robot Modeling and Control","Impedance Control","MPC"],per:["Multiple View Geometry","PointNet","State Estimation for Robotics"],nav:["Probabilistic Robotics","ORB-SLAM3","Nav2"],man:["Robotic Manipulation","GraspNet","Diffusion Policy"],learn:["Reinforcement Learning","Behavior Cloning","Offline RL"],vla:["RT-2","OpenVLA","π0"],sim:["Domain Randomization","World Models","Simulation"],safe:["ISO 10218","ISO/TS 15066","NIST Robotics"]};
const I=[
  "机器人任务由本体能力、环境可观测性、动作约束和成功标准共同定义，语义目标本身不可执行。",
  "感知—规划—行动必须闭环运行，因为动作会改变环境，也会暴露新的状态与误差。",
  "驱动、实时控制、中间件和任务策略处在不同时间尺度，各层接口必须定义保证与失败。",
  "机器人基准要规定任务分布、初始化、重复次数和失败类型，成功视频只是一个样本。",
  "刚体位姿属于 SE(3)，旋转不满足普通向量加法，坐标链必须按顺序组合。",
  "逆运动学可能多解、无解或靠近关节极限，解支选择要考虑连续性和后续任务。",
  "Jacobian 映射关节与末端微分运动，奇异值揭示某些方向失去速度或力能力。",
  "刚体动力学把运动、质量和外力联系到关节力矩，是控制、仿真和安全限幅的基础。",
  "反馈稳定性取决于闭环极点和裕度，瞬时误差下降并不能排除振荡或延迟失稳。",
  "轨迹优化在动力学和碰撞约束内寻找整段运动，路径几何只是其中一个目标。",
  "阻抗控制塑造力与位移关系，让机器人在接触不确定时表现为可控机械顺应。",
  "Whole-body Control 同时协调多接触与多任务，优先级和硬约束决定冲突时的行为。",
  "相机和深度误差经投影与坐标变换传播到三维操作，标定精度必须按任务评估。",
  "点云、体素、网格和隐式场在精度、更新、拓扑和内存上各有取舍，没有通用最佳。",
  "物体识别只回答是什么，安全操作还需要三维位姿、几何、遮挡和不确定性。",
  "Belief State 用分布表达部分可观测性，规划与控制应依据置信而非伪精确单值。",
  "里程计积分局部运动必然漂移，地图与外部观测负责提供长期约束。",
  "回环检测增加远距离约束，错误回环会全局扭曲地图，因此需要鲁棒验证。",
  "全局规划处理拓扑和长期可达，局部规划处理动态安全，两者必须共享状态与恢复语义。",
  "导航可靠性包含知道失败、停止、重新定位和重规划，而不是只统计到达成功。",
  "力闭合描述抓取抵抗扰动的几何条件，候选外观得分不能替代接触稳定性。",
  "接触丰富操作的状态会随摩擦、形变和装配变化，力觉与触觉让策略闭环修正。",
  "任务规划给出语义动作，运动规划验证几何可执行性，联合推理避免符号计划落空。",
  "长程任务要用检查点和可恢复子目标限制误差传播，并在失败时局部重规划。",
  "示范数据通常偏向成功和熟练操作，覆盖恢复、失败与初始状态比单纯增加数量更重要。",
  "行为克隆在训练分布内拟合动作，闭环产生的新状态会累积误差并离开数据支持域。",
  "奖励设计把长期目标变成优化信号，代理指标和稀疏反馈都会诱发投机或信用分配困难。",
  "离线和仿真学习限制真实试错，但部署前必须验证数据支持、模型偏差和安全升级门槛。",
  "VLA 把视觉、语言和动作表示成统一条件序列，动作分块与频率决定控制精度和延迟。",
  "跨本体数据必须对齐坐标、频率、动作语义和质量，不同机器人轨迹不能直接拼接。",
  "语义泛化说明理解新指令或物体，物理泛化还要求几何、动力学与接触行为正确。",
  "端到端 VLA 提供共享表示，模块化系统提供可验证边界，混合设计常更适合安全部署。",
  "仿真器是对传感、动力学和接触的近似，使用目的决定哪些误差必须校准。",
  "域随机化用参数分布覆盖现实变化，范围太窄不迁移、太宽则浪费容量并模糊任务。",
  "合成数据的价值取决于长尾场景覆盖、物理一致和去重，生成数量不能替代真实验证。",
  "世界模型的多步误差会被规划策略选择性放大，反事实 Rollout 必须校准和回放。",
  "风险评估关注速度、力、夹点、意外启动和人员暴露，任务成功不能抵消危险过程。",
  "独立安全层要在学习策略之外监控状态并执行限幅、屏障或急停，避免同源失效。",
  "人机协作安全还依赖动作可预测、意图可理解和交接可恢复，技术限幅只是底线。",
  "现场验收必须覆盖环境变化、维护、操作员和更新管理，让安全证据在运行中持续有效。",
];
export default defineField({slug:"robotics",title:"物理 AI · 机器人",shortTitle:"机器人",prefix:"RBF",color:"#8a4f14",promise:"把机械本体、状态估计、控制、规划、学习、VLA 与物理安全连接起来，拒绝只看机器人演示视频。",project:"一个能在仿真与真实/半实物环境间复现的移动操作机器人任务，包含安全壳、数据与评测报告。"},[
  L(A,"task-environment-embodiment","任务、环境与本体必须一起定义","orientation","‘收拾桌面’怎样落成状态、动作和完成条件？","任务—本体—环境合同",S.sys),
  L(A,"sense-plan-act","感知—规划—行动闭环","mechanism","机器人为何必须不断用新观测修正计划？","闭环数据流与状态机",S.sys),
  L(A,"hardware-software-boundary","从执行器到任务层的系统边界","concept","驱动、实时控制、中间件和策略各保证什么？","硬件—软件分层与接口表",S.sys),
  L(A,"task-benchmark","把演示改写成可重复基准","guided","一次成功视频为什么不能说明可靠性？","任务分布、试验次数与失败分类",S.sys),
  L(A,"frames-transforms","坐标系、齐次变换与李群","derivation","位姿组合为何不能把欧拉角直接相加？","SE(3) 变换链与手眼标定",S.kin),
  L(A,"forward-inverse-kinematics","正运动学与逆运动学","guided","同一末端位姿为何可能有多组关节解或无解？","IK 求解、工作空间与解支选择",S.kin),
  L(A,"jacobian-singularity","Jacobian、速度映射与奇异性","derivation","末端微小运动为何可能需要无限关节速度？","奇异值、可操作度与避奇异策略",S.kin),
  L(A,"rigid-body-dynamics","刚体动力学与逆动力学","mechanism","质量、惯量、科氏力和重力怎样变成关节力矩？","动力学验证与能量检查",S.kin),
  L(B,"feedback-stability","反馈控制与稳定性","derivation","误差变小为什么仍可能振荡、超调甚至失稳？","阶跃响应、频域与稳定裕度",S.ctrl),
  L(B,"trajectory-optimization","轨迹生成与约束优化","mechanism","从 A 到 B 的路径怎样满足速度、力矩和碰撞约束？","轨迹优化与约束违例报告",S.ctrl),
  L(B,"force-impedance-control","力控制与阻抗控制","guided","接触任务为何不能只追位置误差？","位置—力权衡与接触实验",S.ctrl),
  L(B,"whole-body-control","Whole-body Control 与多任务优先级","decision","平衡、末端、视线和避障冲突时谁优先？","任务层级、约束与降级策略",S.ctrl),
  L(B,"camera-depth-calibration","相机、深度与标定误差","guided","像素准确为什么仍会抓偏几厘米？","内外参、深度误差与传播实验",S.per),
  L(B,"point-cloud-3d-representation","点云、体素、网格与隐式表示","decision","几何精度、更新速度和内存怎样决定表示选择？","三维表示 Pareto 对照",S.per),
  L(B,"detection-pose-estimation","检测、分割与六维位姿","mechanism","识别物体后还缺哪些信息才能安全操作？","遮挡、对称与位姿不确定性",S.per),
  L(B,"belief-state-uncertainty","机器人需要 Belief，不只需要状态值","derivation","部分可观测下怎样把不确定性带入规划和控制？","状态分布、一致性与拒绝门槛",S.per),
  L(C,"odometry-mapping","里程计、地图与漂移","mechanism","局部运动估计为何必然累积误差？","轨迹误差与漂移来源图",S.nav),
  L(C,"loop-closure-graph","回环检测与位姿图优化","derivation","一次错误回环为什么能扭曲整张地图？","图优化、鲁棒核与假回环测试",S.nav),
  L(C,"global-local-planning","全局规划与局部避障","decision","地图最短路和实时安全动作怎样协同？","规划器接口与动态障碍基准",S.nav),
  L(C,"navigation-recovery","定位丢失、堵塞与恢复行为","case","导航失败时机器人怎样知道自己失败并恢复？","失败检测、恢复树与可复位基准",S.nav),
  L(C,"grasp-geometry","抓取几何、力闭合与候选生成","derivation","看起来抓住为何不代表受扰后仍稳定？","抓取质量与扰动实验",S.man),
  L(C,"contact-rich-manipulation","接触丰富操作与反馈","mechanism","插接、开门和擦拭为何需要边做边感知？","接触状态机与力/触觉反馈",S.man),
  L(C,"task-and-motion-planning","任务规划与运动规划如何接上","mechanism","语义动作序列怎样避免落到不可执行姿态？","符号—几何联合计划",S.man),
  L(C,"long-horizon-recovery","长程操作中的失败恢复","case","一步偏差怎样沿二十步任务累积，何时重规划？","检查点、回退与成功分解",S.man),
  L(D,"demonstration-data","示范数据的覆盖与遥操作偏差","case","人类只演示成功轨迹时，机器人从哪里学会恢复？","数据覆盖图与失败示范计划",S.learn),
  L(D,"behavior-cloning-covariate-shift","行为克隆与协变量偏移","derivation","训练误差很低的策略为何滚动几步就崩？","闭环 Rollout 与 DAgger 对照",S.learn),
  L(D,"rl-reward-exploration","奖励、探索与信用分配","mechanism","任务目标怎样变成不被策略钻空子的奖励？","奖励分解、约束与 Reward Hacking 测试",S.learn),
  L(D,"offline-online-learning","离线 RL、仿真训练与有限在线更新","decision","物理试错昂贵时，怎样组合保守学习和安全探索？","数据支持域与升级门禁",S.learn),
  L(D,"language-action-tokenization","语言、视觉与动作怎样进入同一模型","mechanism","连续控制被离散或分块后会损失什么？","动作表示与时序延迟分析",S.vla),
  L(D,"robot-data-mixtures","跨任务、跨本体的数据混合","guided","不同频率、坐标和控制接口的数据怎样共同训练？","数据标准化与混合配方",S.vla),
  L(D,"vla-generalization","语义泛化不等于物理泛化","case","认得新物体为何仍可能抓不住、搬不稳？","语义—几何—动力学三层评测",S.vla),
  L(D,"modular-vs-end-to-end","模块化系统还是端到端 VLA","decision","可解释、数据规模、延迟和安全约束下怎样选？","基线对照与混合架构门禁",S.vla),
  L(E,"simulator-validity","仿真器的有效性边界","orientation","画面逼真为什么可能比动力学正确更不重要？","仿真假设、参数与校准账本",S.sim),
  L(E,"domain-randomization","域随机化与系统辨识","guided","随机范围太窄或太宽分别怎样伤害迁移？","参数分布、辨识与真实验证",S.sim),
  L(E,"synthetic-data","合成数据、生成场景与覆盖","frontier","更多生成样本能否覆盖真实世界的长尾物理事件？","场景生成、去重与覆盖矩阵",S.sim),
  L(E,"world-model-planning","世界模型中的规划与反事实","frontier","预测 Rollout 的小偏差何时会被规划反复放大？","多步误差、校准与真实回放",S.sim),
  L(E,"hazard-risk-assessment","危险识别与风险评估","guided","任务成功外，速度、力、夹点和意外启动如何评价？","危险清单、风险等级与控制层次",S.safe),
  L(E,"independent-safety-layer","独立安全层与运行时监护","mechanism","学习策略越界时，谁能在毫秒内拦住它？","安全 PLC、屏障函数与急停测试",S.safe),
  L(E,"human-robot-interaction","意图、可预测性与人机协作","case","动作技术上安全，为何人仍会害怕或误判？","可理解运动、交接与人因实验",S.safe),
  L(E,"deployment-acceptance","从实验室演示到现场验收","synthesis","环境、维护和操作员变化怎样进入持续安全案例？","验收基准、变更管理与事故闭环",S.safe),
].map((seed,index)=>({...seed,insight:I[index]})));
