import { updatedAt } from "./field-config.mjs";

const book = (field, id, title, authors, year, publisher, topics, authorityReason, officialUrl, accessStatus, downloadUrl = null, license = null, kind = "book") => ({
  id: `book:${field}:${id}`,
  field,
  kind,
  title,
  authors,
  year,
  publisher,
  topics,
  official_url: officialUrl,
  authority_reason: authorityReason,
  access: {
    status: accessStatus,
    download_url: downloadUrl,
    license,
    local_path: null,
    sha256: null,
    bytes: null,
    checked_at: null
  },
  updated_at: updatedAt
});

export const booksByField = {
  "machine-learning": [
    book("machine-learning", "esl-2e", "The Elements of Statistical Learning", ["Trevor Hastie", "Robert Tibshirani", "Jerome Friedman"], 2009, "Springer", ["statistical-learning", "supervised-learning", "unsupervised-learning"], "统计学习领域公认的研究生级经典教材，长期用于顶尖大学课程。", "https://hastie.su.domains/ElemStatLearn/", "open_fulltext", "https://hastie.su.domains/Papers/ESLII.pdf", "author-provided"),
    book("machine-learning", "islr-2e", "An Introduction to Statistical Learning (2nd ed.)", ["Gareth James", "Daniela Witten", "Trevor Hastie", "Robert Tibshirani"], 2021, "Springer", ["statistical-learning", "applied-ml", "model-evaluation"], "由 ESL 作者团队编写的应用型权威入门教材，配套课程和实验广泛使用。", "https://www.statlearning.com/", "open_fulltext", "https://hastie.su.domains/ISLR2/ISLRv2_corrected_June_2023.pdf.download.html", "author-provided"),
    book("machine-learning", "islp", "An Introduction to Statistical Learning with Applications in Python", ["Gareth James", "Daniela Witten", "Trevor Hastie", "Robert Tibshirani", "Jonathan Taylor"], 2023, "Springer", ["applied-ml", "python", "model-evaluation"], "ISL 官方 Python 版本，适合把统计学习原理落实为可复现实验。", "https://www.statlearning.com/", "open_fulltext", "https://hastie.su.domains/ISLP/ISLP_website.pdf.download.html", "author-provided"),
    book("machine-learning", "understanding-ml", "Understanding Machine Learning: From Theory to Algorithms", ["Shai Shalev-Shwartz", "Shai Ben-David"], 2014, "Cambridge University Press", ["learning-theory", "generalization", "optimization"], "机器学习理论课程常用教材，系统覆盖 PAC、在线学习、核方法与优化。", "https://www.cs.huji.ac.il/~shais/UnderstandingMachineLearning/", "open_fulltext", "https://www.cs.huji.ac.il/~shais/UnderstandingMachineLearning/understanding-machine-learning-theory-algorithms.pdf", "author-provided"),
    book("machine-learning", "mathematics-for-ml", "Mathematics for Machine Learning", ["Marc Peter Deisenroth", "A. Aldo Faisal", "Cheng Soon Ong"], 2020, "Cambridge University Press", ["linear-algebra", "calculus", "probability"], "面向机器学习的数学前置教材，作者提供合法开放版本。", "https://mml-book.github.io/", "open_fulltext", "https://mml-book.github.io/book/mml-book.pdf", "CC-BY-NC-SA"),
    book("machine-learning", "probml-intro", "Probabilistic Machine Learning: An Introduction", ["Kevin P. Murphy"], 2022, "MIT Press", ["probabilistic-modeling", "bayesian-methods", "deep-learning"], "Murphy 的现代概率机器学习教材，覆盖经典方法与深度学习并提供持续更新资源。", "https://probml.github.io/pml-book/book1.html", "official_online"),
    book("machine-learning", "probml-advanced", "Probabilistic Machine Learning: Advanced Topics", ["Kevin P. Murphy"], 2023, "MIT Press", ["probabilistic-modeling", "causal-inference", "generative-models"], "概率机器学习进阶卷，覆盖结构化概率模型、因果与现代生成方法。", "https://probml.github.io/pml-book/book2.html", "official_online"),
    book("machine-learning", "bayesian-reasoning", "Bayesian Reasoning and Machine Learning", ["David Barber"], 2012, "Cambridge University Press", ["bayesian-methods", "graphical-models", "inference"], "系统连接贝叶斯推断、图模型与机器学习，作者公开完整教材。", "https://web4.cs.ucl.ac.uk/staff/D.Barber/textbook/090310.pdf", "open_fulltext", "https://web4.cs.ucl.ac.uk/staff/D.Barber/textbook/090310.pdf", "author-provided"),
    book("machine-learning", "fairness-ml", "Fairness and Machine Learning", ["Solon Barocas", "Moritz Hardt", "Arvind Narayanan"], 2023, "fairmlbook.org", ["fairness", "accountability", "decision-systems"], "算法公平领域的开放教材，作者均为该领域的重要研究者。", "https://fairmlbook.org/", "open_fulltext", "https://fairmlbook.org/pdf/fairmlbook.pdf", "author-provided"),
    book("machine-learning", "causal-what-if", "Causal Inference: What If", ["Miguel A. Hernán", "James M. Robins"], 2024, "Chapman & Hall/CRC", ["causal-inference", "experimentation", "observational-data"], "现代因果推断的权威开放教材，强调目标试验与可识别假设；最新版从作者官方页面阅读。", "https://hsph.harvard.edu/miguel-hernan/causal-inference-book/2015", "official_online")
  ],
  "deep-learning": [
    book("deep-learning", "deep-learning-book", "Deep Learning", ["Ian Goodfellow", "Yoshua Bengio", "Aaron Courville"], 2016, "MIT Press", ["neural-networks", "optimization", "generative-models"], "现代深度学习的经典系统教材，由领域奠基研究者编写。", "https://www.deeplearningbook.org/", "official_online"),
    book("deep-learning", "d2l", "Dive into Deep Learning", ["Aston Zhang", "Zachary C. Lipton", "Mu Li", "Alexander J. Smola"], 2023, "Cambridge University Press", ["neural-networks", "implementation", "transformers"], "将数学、代码和现代架构结合的开放教材，持续维护且适合动手学习。", "https://d2l.ai/", "open_fulltext", "https://d2l.ai/d2l-en.pdf", "CC-BY-SA"),
    book("deep-learning", "understanding-dl", "Understanding Deep Learning", ["Simon J. D. Prince"], 2023, "MIT Press", ["foundations", "optimization", "generative-models"], "现代深度学习教材，图示与练习强调从机制建立理解。", "https://udlbook.github.io/udlbook/", "official_online"),
    book("deep-learning", "nndl", "Neural Networks and Deep Learning", ["Michael Nielsen"], 2015, "Determination Press", ["neural-networks", "backpropagation", "optimization"], "以直觉和推导讲解神经网络、反向传播与正则化的开放在线教材。", "http://neuralnetworksanddeeplearning.com/", "official_online"),
    book("deep-learning", "geometric-dl", "Geometric Deep Learning: Grids, Groups, Graphs, Geodesics, and Gauges", ["Michael M. Bronstein", "Joan Bruna", "Taco Cohen", "Petar Veličković"], 2021, "authors", ["geometric-learning", "graphs", "symmetry"], "几何深度学习统一视角的权威开放在线专著，由该方向核心研究者编写。", "https://geometricdeeplearning.com/book", "official_online"),
    book("deep-learning", "probml-intro", "Probabilistic Machine Learning: An Introduction", ["Kevin P. Murphy"], 2022, "MIT Press", ["probabilistic-modeling", "deep-learning", "uncertainty"], "用概率视角连接经典机器学习与现代神经网络。", "https://probml.github.io/pml-book/book1.html", "official_online"),
    book("deep-learning", "probml-advanced", "Probabilistic Machine Learning: Advanced Topics", ["Kevin P. Murphy"], 2023, "MIT Press", ["generative-models", "latent-variables", "causal-models"], "覆盖变分推断、生成模型和高级概率方法的现代进阶教材。", "https://probml.github.io/pml-book/book2.html", "official_online"),
    book("deep-learning", "mathematics-for-ml", "Mathematics for Machine Learning", ["Marc Peter Deisenroth", "A. Aldo Faisal", "Cheng Soon Ong"], 2020, "Cambridge University Press", ["linear-algebra", "calculus", "probability"], "深度学习所需线性代数、微积分和概率的可靠前置。", "https://mml-book.github.io/", "open_fulltext", "https://mml-book.github.io/book/mml-book.pdf", "CC-BY-NC-SA"),
    book("deep-learning", "slp3", "Speech and Language Processing (3rd ed. draft)", ["Dan Jurafsky", "James H. Martin"], 2026, "authors", ["transformers", "language-models", "speech"], "NLP 与语言模型课程的权威持续更新教材，覆盖 Transformer 和大模型。", "https://web.stanford.edu/~jurafsky/slp3/", "open_fulltext", "https://web.stanford.edu/~jurafsky/slp3/ed3book_aug26.pdf", "author-provided"),
    book("deep-learning", "generative-dl", "Generative Deep Learning (2nd ed.)", ["David Foster"], 2023, "O'Reilly", ["generative-models", "vae", "gan", "diffusion"], "面向实践系统梳理主要深度生成模型的专业教材。", "https://www.oreilly.com/library/view/generative-deep-learning/9781098134174/", "commercial")
  ],
  nlp: [
    book("nlp", "slp3", "Speech and Language Processing (3rd ed. draft)", ["Dan Jurafsky", "James H. Martin"], 2026, "authors", ["nlp-foundations", "language-models", "speech"], "NLP 领域最广泛采用的综合教材之一，第三版持续更新现代语言模型内容。", "https://web.stanford.edu/~jurafsky/slp3/", "open_fulltext", "https://web.stanford.edu/~jurafsky/slp3/ed3book_aug26.pdf", "author-provided"),
    book("nlp", "nltk-book", "Natural Language Processing with Python", ["Steven Bird", "Ewan Klein", "Edward Loper"], 2009, "O'Reilly", ["nlp-foundations", "corpora", "annotation"], "NLTK 官方教材，长期用于 NLP 入门与语料实践。", "https://www.nltk.org/book/", "official_online"),
    book("nlp", "ir-book", "Introduction to Information Retrieval", ["Christopher D. Manning", "Prabhakar Raghavan", "Hinrich Schütze"], 2008, "Cambridge University Press", ["information-retrieval", "ranking", "evaluation"], "信息检索领域经典教材，是理解搜索与 RAG 的重要基础。", "https://nlp.stanford.edu/IR-book/", "open_fulltext", "https://nlp.stanford.edu/IR-book/pdf/irbookonlinereading.pdf", "author-provided"),
    book("nlp", "fsnlp", "Foundations of Statistical Natural Language Processing", ["Christopher D. Manning", "Hinrich Schütze"], 1999, "MIT Press", ["statistical-nlp", "language-modeling", "parsing"], "统计 NLP 奠基教材，对概率语言建模与经典方法影响深远。", "https://nlp.stanford.edu/fsnlp/", "commercial"),
    book("nlp", "nn-methods", "Neural Network Methods for Natural Language Processing", ["Yoav Goldberg"], 2017, "Morgan & Claypool", ["neural-nlp", "embeddings", "sequence-models"], "由重要 NLP 研究者编写，系统连接表示学习与神经 NLP。", "https://www.morganclaypool.com/doi/abs/10.2200/S00762ED1V01Y201703HLT037", "commercial"),
    book("nlp", "nlp-transformers", "Natural Language Processing with Transformers", ["Lewis Tunstall", "Leandro von Werra", "Thomas Wolf"], 2022, "O'Reilly", ["transformers", "hugging-face", "fine-tuning"], "由 Hugging Face 核心成员编写的现代 Transformer 实践教材。", "https://www.oreilly.com/library/view/natural-language-processing/9781098136789/", "commercial"),
    book("nlp", "text-mining-r", "Text Mining with R", ["Julia Silge", "David Robinson"], 2017, "O'Reilly", ["text-mining", "statistics", "visualization"], "开放在线文本挖掘教材，强调可复现数据分析。", "https://www.tidytextmining.com/", "official_online"),
    book("nlp", "annotation-ml", "Natural Language Annotation for Machine Learning", ["James Pustejovsky", "Amber Stubbs"], 2012, "O'Reilly", ["annotation", "corpora", "task-design"], "系统讲解语言数据标注、标签体系与质量控制。", "https://www.oreilly.com/library/view/natural-language-annotation/9781449332693/", "commercial"),
    book("nlp", "linguistic-fundamentals-1", "Linguistic Fundamentals for Natural Language Processing: 100 Essentials from Morphology and Syntax", ["Emily M. Bender"], 2013, "Morgan & Claypool", ["linguistics", "morphology", "syntax"], "为 NLP 工程师补足形态与句法基础的专业教材。", "https://www.morganclaypool.com/doi/abs/10.2200/S00493ED1V01Y201303HLT020", "commercial"),
    book("nlp", "ethics-nlp", "Ethics in Natural Language Processing", ["Dirk Hovy"], 2022, "Morgan & Claypool", ["ethics", "bias", "responsible-nlp"], "由计算社会科学与 NLP 研究者编写，专门讨论语言技术的伦理、偏差和社会影响。", "https://www.morganclaypool.com/doi/abs/10.2200/S01183ED1V01Y202208HLT056", "commercial")
  ],
  "ai-product": [
    book("ai-product", "human-centered-ai", "Human-Centered AI", ["Ben Shneiderman"], 2022, "Oxford University Press", ["human-centered-ai", "reliability", "governance"], "由 HCI 领域权威学者提出以高自动化与高人类控制并行的系统框架。", "https://global.oup.com/academic/product/human-centered-ai-9780192845290", "commercial"),
    book("ai-product", "designing-ml-systems", "Designing Machine Learning Systems", ["Chip Huyen"], 2022, "O'Reilly", ["product-architecture", "data", "deployment"], "系统覆盖从问题定义、数据到部署监控的 ML 产品工程实践。", "https://www.oreilly.com/library/view/designing-machine-learning/9781098107956/", "commercial"),
    book("ai-product", "ai-engineering", "AI Engineering", ["Chip Huyen"], 2025, "O'Reilly", ["foundation-models", "evaluation", "product-development"], "面向基础模型时代的应用构建、评测和迭代，是当前 AI 产品工程的重要新教材。", "https://www.oreilly.com/library/view/ai-engineering/9781098166298/", "commercial"),
    book("ai-product", "building-ml-apps", "Building Machine Learning Powered Applications", ["Emmanuel Ameisen"], 2020, "O'Reilly", ["problem-framing", "prototyping", "iteration"], "从产品问题到部署的端到端实践书，强调错误分析和迭代。", "https://www.oreilly.com/library/view/building-machine-learning/9781492045106/", "commercial"),
    book("ai-product", "inspired", "INSPIRED: How to Create Tech Products Customers Love", ["Marty Cagan"], 2017, "Wiley", ["product-discovery", "teams", "strategy"], "现代科技产品管理的行业经典，用于建立产品发现和团队责任基础。", "https://www.svpg.com/inspired-how-to-create-products-customers-love/", "commercial"),
    book("ai-product", "continuous-discovery", "Continuous Discovery Habits", ["Teresa Torres"], 2021, "Product Talk", ["discovery", "experimentation", "user-research"], "持续发现方法的代表作，适合约束 AI 功能从真实机会而非演示出发。", "https://www.producttalk.org/continuous-discovery-habits/", "commercial"),
    book("ai-product", "prediction-machines", "Prediction Machines", ["Ajay Agrawal", "Joshua Gans", "Avi Goldfarb"], 2018, "Harvard Business Review Press", ["economics", "decision-making", "strategy"], "由经济学者从预测成本与决策互补资产解释 AI 产品价值。", "https://www.predictionmachines.ai/", "commercial"),
    book("ai-product", "power-and-prediction", "Power and Prediction", ["Ajay Agrawal", "Joshua Gans", "Avi Goldfarb"], 2022, "Harvard Business Review Press", ["system-redesign", "economics", "organization"], "进一步讨论 AI 从点工具到系统级工作流重构的经济逻辑。", "https://www.powerandprediction.com/", "commercial"),
    book("ai-product", "pair-guidebook", "People + AI Guidebook", ["Google PAIR"], 2019, "Google", ["ai-ux", "trust", "human-ai-interaction"], "Google PAIR 基于 HAI 研究整理的公开设计手册，包含真实交互模式和工作表。", "https://pair.withgoogle.com/guidebook/", "official_online", null, null, "handbook"),
    book("ai-product", "nist-ai-rmf", "Artificial Intelligence Risk Management Framework (AI RMF 1.0)", ["NIST"], 2023, "National Institute of Standards and Technology", ["risk-management", "governance", "measurement"], "美国 NIST 正式风险管理框架，为 AI 产品治理、测量与责任分配提供权威公共基线。", "https://www.nist.gov/itl/ai-risk-management-framework", "open_fulltext", "https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.100-1.pdf", "US-government-work", "handbook")
  ],
  "low-altitude": [
    book("low-altitude", "introduction-uas", "Introduction to Unmanned Aircraft Systems", ["Richard K. Barnhart", "Stephen B. Hottman", "Douglas M. Marshall", "Eric Shappee"], 2016, "CRC Press", ["uas-system", "operations", "regulation"], "UAS 系统、运行与监管的综合性专业教材。", "https://www.routledge.com/Introduction-to-Unmanned-Aircraft-Systems/Barnhart-Hottman-Marshall-Shappee/p/book/9781482263954", "commercial"),
    book("low-altitude", "small-uas", "Small Unmanned Aircraft: Theory and Practice", ["Randal W. Beard", "Timothy W. McLain"], 2012, "Princeton University Press", ["flight-dynamics", "control", "planning"], "小型无人机动力学、估计、控制和规划领域的经典教材。", "https://press.princeton.edu/books/hardcover/9780691149219/small-unmanned-aircraft", "commercial"),
    book("low-altitude", "uas-design", "Unmanned Aircraft Systems: UAVS Design, Development and Deployment", ["Reg Austin"], 2010, "Wiley", ["aircraft-design", "systems-engineering", "deployment"], "从构型、载荷、通信到运行系统性介绍 UAS 的经典工程专著。", "https://www.wiley.com/en-us/Unmanned+Aircraft+Systems%3A+UAVS+Design%2C+Development+and+Deployment-p-9780470664797", "commercial"),
    book("low-altitude", "advances-uas", "Handbook of Unmanned Aerial Vehicles", ["Kimon P. Valavanis", "George J. Vachtsevanos"], 2015, "Springer", ["uas-handbook", "control", "applications"], "覆盖无人机设计、控制、感知、通信和应用的大型权威手册。", "https://link.springer.com/referencework/10.1007/978-90-481-9707-1", "commercial", null, null, "handbook"),
    book("low-altitude", "aircraft-control-simulation", "Aircraft Control and Simulation", ["Brian L. Stevens", "Frank L. Lewis", "Eric N. Johnson"], 2015, "Wiley", ["flight-control", "simulation", "guidance"], "飞行器建模、制导与控制的标准研究生教材。", "https://www.wiley.com/en-us/Aircraft+Control+and+Simulation%2C+3rd+Edition-p-9781118870983", "commercial"),
    book("low-altitude", "fundamentals-aerodynamics", "Fundamentals of Aerodynamics", ["John D. Anderson"], 2017, "McGraw-Hill", ["aerodynamics", "flight", "performance"], "航空航天专业广泛采用的空气动力学经典教材。", "https://www.mheducation.com/highered/product/fundamentals-aerodynamics-anderson.html", "commercial"),
    book("low-altitude", "faa-phak", "Pilot's Handbook of Aeronautical Knowledge", ["Federal Aviation Administration"], 2023, "FAA", ["flight-principles", "weather", "operations"], "FAA 官方航空知识手册，覆盖飞行原理、气象、导航与运行基础。", "https://www.faa.gov/regulations_policies/handbooks_manuals/aviation/phak", "open_fulltext", "https://www.faa.gov/regulations_policies/handbooks_manuals/aviation/faa-h-8083-25c.pdf", "US-government-work", "handbook"),
    book("low-altitude", "faa-remote-pilot", "Remote Pilot – Small Unmanned Aircraft Systems Study Guide", ["Federal Aviation Administration"], 2016, "FAA", ["remote-pilot", "airspace", "weather", "operations"], "FAA 官方小型无人机远程驾驶员学习指南，适合建立空域和运行基础。", "https://www.faa.gov/regulations_policies/handbooks_manuals/aviation", "open_fulltext", "https://www.faa.gov/sites/faa.gov/files/regulations_policies/handbooks_manuals/aviation/remote_pilot_study_guide.pdf", "US-government-work", "handbook"),
    book("low-altitude", "easa-uas-rules", "Easy Access Rules for Unmanned Aircraft Systems", ["European Union Aviation Safety Agency"], 2026, "EASA", ["regulation", "operations", "risk"], "EASA 官方汇编的无人机规则与可接受符合性方法，是欧洲运行框架的权威入口。", "https://www.easa.europa.eu/en/document-library/easy-access-rules/easy-access-rules-unmanned-aircraft-systems-regulations-eu", "official_online", null, null, "handbook"),
    book("low-altitude", "jarus-sora", "Specific Operations Risk Assessment (SORA)", ["Joint Authorities for Rulemaking on Unmanned Systems"], 2024, "JARUS", ["risk-assessment", "operations", "safety-case"], "多国监管机构共同维护的特定类无人机运行风险评估方法。", "https://www.jarus-rpas.org/sora", "official_online", null, null, "handbook")
  ],
  robotics: [
    book("robotics", "modern-robotics", "Modern Robotics: Mechanics, Planning, and Control", ["Kevin M. Lynch", "Frank C. Park"], 2017, "Cambridge University Press", ["kinematics", "dynamics", "planning", "control"], "现代机器人学核心教材，配套公开视频、代码和作者开放 PDF。", "https://modernrobotics.northwestern.edu/", "open_fulltext", "https://hades.mech.northwestern.edu/images/archive/8/81/20170504034538!MR-largefont.pdf", "author-provided"),
    book("robotics", "planning-algorithms", "Planning Algorithms", ["Steven M. LaValle"], 2006, "Cambridge University Press", ["motion-planning", "search", "control"], "机器人运动规划与算法领域的经典开放教材。", "https://lavalle.pl/planning/", "open_fulltext", "https://lavalle.pl/planning/book.pdf", "author-provided"),
    book("robotics", "underactuated", "Underactuated Robotics", ["Russ Tedrake"], 2026, "MIT", ["dynamics", "control", "optimization"], "MIT 持续维护的研究生课程教材，覆盖非线性动力学、控制与轨迹优化。", "https://underactuated.csail.mit.edu/", "official_online"),
    book("robotics", "state-estimation", "State Estimation for Robotics", ["Timothy D. Barfoot"], 2017, "Cambridge University Press", ["state-estimation", "lie-groups", "slam"], "机器人状态估计与 Lie 群方法的重要研究生教材。", "http://asrl.utias.utoronto.ca/~tdb/bib/barfoot_ser17.pdf", "open_fulltext", "http://asrl.utias.utoronto.ca/~tdb/bib/barfoot_ser17.pdf", "author-provided"),
    book("robotics", "math-robotic-manipulation", "A Mathematical Introduction to Robotic Manipulation", ["Richard M. Murray", "Zexiang Li", "S. Shankar Sastry"], 1994, "CRC Press", ["manipulation", "kinematics", "control"], "操作机器人几何、运动学与控制的经典数学教材，作者提供开放版本。", "https://www.cds.caltech.edu/~murray/books/MLS/pdf/mlsw.pdf", "open_fulltext", "https://www.cds.caltech.edu/~murray/books/MLS/pdf/mlsw.pdf", "author-provided"),
    book("robotics", "probabilistic-robotics", "Probabilistic Robotics", ["Sebastian Thrun", "Wolfram Burgard", "Dieter Fox"], 2005, "MIT Press", ["localization", "mapping", "planning"], "概率机器人、定位与 SLAM 领域的奠基性教材。", "https://mitpress.mit.edu/9780262201629/probabilistic-robotics/", "commercial"),
    book("robotics", "springer-handbook", "Springer Handbook of Robotics (2nd ed.)", ["Bruno Siciliano", "Oussama Khatib"], 2016, "Springer", ["robotics-handbook", "control", "perception", "hri"], "覆盖机器人学主要分支的旗舰参考手册，由全球领域专家共同编写。", "https://link.springer.com/referencework/10.1007/978-3-319-32552-1", "commercial", null, null, "handbook"),
    book("robotics", "robotics-vision-control", "Robotics, Vision and Control", ["Peter Corke"], 2023, "Springer", ["robotics", "computer-vision", "control"], "把机器人建模、视觉和控制与可运行工具箱结合的权威实践教材。", "https://link.springer.com/book/10.1007/978-3-031-06469-2", "commercial"),
    book("robotics", "autonomous-mobile-robots", "Introduction to Autonomous Mobile Robots (2nd ed.)", ["Roland Siegwart", "Illah R. Nourbakhsh", "Davide Scaramuzza"], 2011, "MIT Press", ["mobile-robots", "localization", "navigation"], "自主移动机器人感知、定位与导航的经典综合教材。", "https://mitpress.mit.edu/9780262015356/introduction-to-autonomous-mobile-robots/", "commercial"),
    book("robotics", "principles-robot-motion", "Principles of Robot Motion", ["Howie Choset", "Kevin M. Lynch", "Seth Hutchinson", "George Kantor", "Wolfram Burgard", "Lydia E. Kavraki", "Sebastian Thrun"], 2005, "MIT Press", ["motion-planning", "localization", "control"], "由规划与概率机器人重要学者共同编写的机器人运动教材。", "https://mitpress.mit.edu/9780262033275/principles-of-robot-motion/", "commercial")
  ]
};
